# 1. Read Libraries and Data

In [2]:
import pandas as pd
import numpy as np

import optuna
import tensorflow as tf

""" Sequential -  It allows you to create a model by simply adding layers one after another.
This is used for building simple neural networks where the flow of data is straightforward, 
from input to output, through a series of layers."""
from tensorflow.keras.models import Sequential

"""Dense is a fully connected layer, also known as a dense layer, in a neural network.
Each neuron in a dense layer receives input from all neurons in the previous layer."""
from tensorflow.keras.layers import Dense

"""Optimizers computes adaptive learning rates for each parameter"""
from tensorflow.keras.optimizers import SGD, Adam, RMSprop, Adagrad, Adadelta, Nadam

from sklearn.metrics import r2_score

data = pd.read_csv(r"C:/Users/aksta/Desktop/Salary_Data.csv")

data

C:\Users\aksta\AppData\Local\Programs\Python\Python314\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28.0,Female,Master's,Data Analyst,3.0,65000.0
2,45.0,Male,PhD,Senior Manager,15.0,150000.0
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0
4,52.0,Male,Master's,Director,20.0,200000.0
...,...,...,...,...,...,...
6699,49.0,Female,PhD,Director of Marketing,20.0,200000.0
6700,32.0,Male,High School,Sales Associate,3.0,50000.0
6701,30.0,Female,Bachelor's Degree,Financial Manager,4.0,55000.0
6702,46.0,Male,Master's Degree,Marketing Manager,14.0,140000.0
6703,26.0,Female,High School,Sales Executive,1.0,35000.0

# 2. Descriptive Statistics

In [3]:
data.describe(include='all')

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
count,6702.000000,6702,6701,6702,6701.000000,6699.000000
unique,NaN,3,7,193,NaN,NaN
top,NaN,Male,Bachelor's Degree,Software Engineer,NaN,NaN
freq,NaN,3674,2267,518,NaN,NaN
mean,33.620859,NaN,NaN,NaN,8.094687,115326.964771
std,7.614633,NaN,NaN,NaN,6.059003,52786.183911
min,21.000000,NaN,NaN,NaN,0.000000,350.000000
25%,28.000000,NaN,NaN,NaN,3.000000,70000.000000
50%,32.000000,NaN,NaN,NaN,7.000000,115000.000000
75%,38.000000,NaN,NaN,NaN,12.000000,160000.000000
max,62.000000,NaN,NaN,NaN,34.000000,250000.000000

# 3. Check missing values and drop them

In [4]:
data.isna().sum()

data.dropna(inplace=True)

# 4. Clean the Education Level column by merging category names into one using np.where .

In [5]:
data['Education Level'] = np.where(data['Education Level'] == "Bachelor's", "Bachelor's Degree", data['Education Level'])
data['Education Level'] = np.where(data['Education Level'] == "Master's", "Master's Degree", data['Education Level'])
data['Education Level'] = np.where(data['Education Level'] == "phD", "PhD", data['Education Level'])

data['Education Level'].value_counts()

Education Level
Bachelor's Degree    3021
Master's Degree      1860
PhD                  1369
High School           448
Name: count, dtype: int64

# 5. Create two new features from the Job Title column: 

- 1. the mean experience (exp_mean_by_job) for each job title
- 2. the number of unique education levels (edu_nunique_by_job) for each job title
- 3. then drop the Job Title column.

In [6]:
data['exp_mean_by_job'] = data.groupby('Job Title')['Years of Experience'].transform('mean')
data['edu_nunique_by_job'] = data.groupby('Job Title')['Education Level'].transform('nunique')

data.drop('Job Title', axis=1, inplace=True)

data

,Age,Gender,Education Level,Years of Experience,Salary,exp_mean_by_job,edu_nunique_by_job
0,32.0,Male,Bachelor's Degree,5.0,90000.0,4.449807,2
1,28.0,Female,Master's Degree,3.0,65000.0,4.969697,2
2,45.0,Male,PhD,15.0,150000.0,17.500000,1
3,36.0,Female,Bachelor's Degree,7.0,60000.0,1.428571,2
4,52.0,Male,Master's Degree,20.0,200000.0,20.000000,1
...,...,...,...,...,...,...,...
6699,49.0,Female,PhD,20.0,200000.0,12.068182,3
6700,32.0,Male,High School,3.0,50000.0,1.428571,2
6701,30.0,Female,Bachelor's Degree,4.0,55000.0,10.694030,4
6702,46.0,Male,Master's Degree,14.0,140000.0,9.454902,3
6703,26.0,Female,High School,1.0,35000.0,2.184211,2

# 6. Declare target and inputs and Split data using train_test_split

In [7]:
from sklearn.model_selection import train_test_split

inputs = data.drop('Salary', axis=1)
target = data['Salary']

X_train, X_test, y_train, y_test = train_test_split(inputs, target, test_size=0.2, random_state=42)

# 7. Using LabelEncoder convert categorics to numerical

In [8]:
from sklearn.preprocessing import LabelEncoder

encoders = {}
for i in X_train.select_dtypes(include=['object', 'string']).columns:
    le = LabelEncoder()
    X_train[i] = le.fit_transform(X_train[i])
    encoders[i] = le

for i in X_test.columns:
    if i in encoders:
        le = encoders[i]
        X_test[i] = le.transform(X_test[i])

display(X_train)
display(X_test)

,Age,Gender,Education Level,Years of Experience,exp_mean_by_job,edu_nunique_by_job
3426,39.0,1,2,10.0,7.809524,2
1552,38.0,0,2,10.0,6.065574,3
6021,35.0,0,3,12.0,11.226667,1
4461,30.0,0,1,1.0,1.253521,1
3286,23.0,0,0,1.0,4.449807,2
...,...,...,...,...,...,...
3776,29.0,1,0,4.0,4.449807,2
5195,38.0,0,2,14.0,13.531250,1
5230,25.0,1,0,1.0,1.274510,1
5395,27.0,1,0,1.0,1.274510,1
862,25.0,0,0,2.0,4.969697,2

,Age,Gender,Education Level,Years of Experience,exp_mean_by_job,edu_nunique_by_job
1883,36.0,1,2,9.0,6.065574,3
2630,27.0,0,2,4.0,4.149378,3
498,25.0,0,2,1.0,4.969697,2
5973,28.0,0,0,3.0,3.113636,1
4108,29.0,1,0,5.0,3.200000,2
...,...,...,...,...,...,...
2830,26.0,0,2,3.0,4.149378,3
6154,28.0,0,0,3.0,3.113636,1
4940,28.0,0,3,6.0,12.068182,3
135,39.0,0,0,10.0,9.000000,1
3688,26.0,1,0,3.0,3.200000,2

# 8. Scale inputs using StandartScaler

In [9]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

# Fit only on training data
scaler.fit(X_train)

# Transform train and test
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Convert back to DataFrames
X_train_scaled = pd.DataFrame(
    X_train_scaled,
    columns=X_train.columns,
    index=X_train.index
)

X_test_scaled = pd.DataFrame(
    X_test_scaled,
    columns=X_test.columns,
    index=X_test.index
)

display(X_train_scaled)
display(X_test_scaled)

,Age,Gender,Education Level,Years of Experience,exp_mean_by_job,edu_nunique_by_job
3426,0.707334,0.895071,0.624867,0.315738,-0.067456,-0.534691
1552,0.575653,-1.097364,0.624867,0.315738,-0.455648,0.493989
6021,0.180612,-1.097364,1.443458,0.648068,0.693177,-1.563370
4461,-0.477790,-1.097364,-0.193724,-1.179746,-1.526779,-1.563370
3286,-1.399553,-1.097364,-1.012315,-1.179746,-0.815307,-0.534691
...,...,...,...,...,...,...
3776,-0.609471,0.895071,-1.012315,-0.681251,-0.815307,-0.534691
5195,0.575653,-1.097364,0.624867,0.980398,1.206162,-1.563370
5230,-1.136192,0.895071,-1.012315,-1.179746,-1.522107,-1.563370
5395,-0.872832,0.895071,-1.012315,-1.179746,-1.522107,-1.563370
862,-1.136192,-1.097364,-1.012315,-1.013581,-0.699583,-0.534691

,Age,Gender,Education Level,Years of Experience,exp_mean_by_job,edu_nunique_by_job
1883,0.312293,0.895071,0.624867,0.149573,-0.455648,0.493989
2630,-0.872832,-1.097364,0.624867,-0.681251,-0.882181,0.493989
498,-1.136192,-1.097364,0.624867,-1.179746,-0.699583,-0.534691
5973,-0.741151,-1.097364,-1.012315,-0.847416,-1.112730,-1.563370
4108,-0.609471,0.895071,-1.012315,-0.515087,-1.093506,-0.534691
...,...,...,...,...,...,...
2830,-1.004512,-1.097364,0.624867,-0.847416,-0.882181,0.493989
6154,-0.741151,-1.097364,-1.012315,-0.847416,-1.112730,-1.563370
4940,-0.741151,-1.097364,1.443458,-0.348922,0.880493,0.493989
135,0.707334,-1.097364,-1.012315,0.315738,0.197536,-1.563370
3688,-1.004512,0.895071,-1.012315,-0.847416,-1.093506,-0.534691

# 9. Create ANN model for regression use with best hyperparameters using Optuna

- Last dense layer's activation function has to be relu
- loss='mae'
- metrics=['mae']
- metrics inside optuna and evaluate function has to be r2_score

In [10]:
def create_model(trial):
    # Building artificial neural network
    model = Sequential()

     # we add 2 hidden layers and 1 output layer
    model.add(Dense(units=trial.suggest_int('units_layer1', 16, 128), activation='relu'))
    model.add(Dense(units=trial.suggest_int('units_layer2', 16, 128), activation='relu'))
    model.add(Dense(units=1, activation='relu'))

    # Suggest hyperparameters for the optimizer
    optimizer_name = trial.suggest_categorical('optimizer', ['adam', 'rmsprop'])
    learning_rate = trial.suggest_float('learning_rate', 1e-2, 1.0, log=True)
    
    if optimizer_name == 'adam':
        optimizer = Adam(learning_rate=learning_rate)
    elif optimizer_name == 'rmsprop':
        optimizer = RMSprop(learning_rate=learning_rate)

    model.compile(optimizer=optimizer, loss='mae', metrics=['mae'])
    
    return model

def optimal(trial):
    
    # Suggest the number of epochs and batch size
    epochs = trial.suggest_int('epochs', 50, 200)
    batch_size = trial.suggest_int('batch_size', 16, 64)
    
    model = create_model(trial)
    
    history = model.fit(X_train_scaled, y_train, epochs=epochs, batch_size=batch_size)
    
    y_pred = model.predict(X_test_scaled)
    score = r2_score(y_test, y_pred)
    
    return score

study = optuna.create_study(direction='maximize')
study.optimize(optimal, n_trials=30)

print(f"Best trial: {study.best_trial.value}")
print(f"Best hyperparameters: {study.best_trial.params}")

best_params = study.best_trial.params

best_params

[I 2026-10-20 12:52:05,120] A new study created in memory with name: no-name-9fb87f78-8b38-4039-b497-8c4f770e973f

Epoch 1/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 76406.8281 - mae: 76406.8281
Epoch 2/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24854.6914 - mae: 24854.6914
Epoch 3/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21298.6973 - mae: 21298.6973
Epoch 4/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20847.5586 - mae: 20847.5586
Epoch 5/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20610.7598 - mae: 20610.7598
Epoch 6/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20441.1562 - mae: 20441.1562
Epoch 7/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 20327.0273 - mae: 20327.0273
Epoch 8/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20221.9355 - mae: 20221.9355
Epoch 9/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20121.0742 - mae: 20121.0742
Epoch 10/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 20039.2109 - mae: 20039.2109
Epoch 11/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 19980.8711 - mae: 19980.8711
Epoch 12/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 19963.0273 - mae: 19963.0273
Epoch 13/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19862.5645 - mae: 19862.5645
Epoch 14/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19792.6934 - mae: 19792.6934
Epoch 15/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19732.6094 - mae: 19732.6094
Epoch 16/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19691.9297 - mae: 19691.9297
Epoch 17/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19637.2754 - mae: 19637.2754
Epoch 18/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19576.8535 - mae: 19576.8535
Epoch 19/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 19541.5371 - mae: 19541.5371
Epoch 20/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 19487.2676 - mae: 19487.2676
Epoch 21/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19451.7930 - mae: 19451.7930
Epoch 22/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 19379.6484 - mae: 19379.6484
Epoch 23/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 19378.7559 - mae: 19378.7559
Epoch 24/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 19316.5352 - mae: 19316.5352
Epoch 25/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 19254.6445 - mae: 19254.6445
Epoch 26/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 19251.7148 - mae: 19251.7148
Epoch 27/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 19208.1621 - mae: 19208.1621
Epoch 28/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 19200.7832 - mae: 19200.7832
Epoch 29/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 19153.5254 - mae: 19153.5254
Epoch 30/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 19126.3359 - mae: 19126.3359
Epoch 31/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19099.5781 - mae: 19099.5781
Epoch 32/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19077.9219 - mae: 19077.9219
Epoch 33/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19097.4082 - mae: 19097.4082
Epoch 34/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 19047.7168 - mae: 19047.7168
Epoch 35/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19043.0957 - mae: 19043.0957
Epoch 36/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19063.9023 - mae: 19063.9023
Epoch 37/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19031.6602 - mae: 19031.6602
Epoch 38/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19050.7168 - mae: 19050.7168
Epoch 39/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18972.4785 - mae: 18972.4785
Epoch 40/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 18997.8125 - mae: 18997.8125
Epoch 41/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18939.5137 - mae: 18939.5137
Epoch 42/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18962.8867 - mae: 18962.8867
Epoch 43/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 18902.0508 - mae: 18902.0508
Epoch 44/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 18873.9902 - mae: 18873.9902
Epoch 45/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 18871.3008 - mae: 18871.3008
Epoch 46/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18867.6895 - mae: 18867.6895
Epoch 47/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18852.5078 - mae: 18852.5078
Epoch 48/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 18850.9883 - mae: 18850.9883
Epoch 49/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18786.4062 - mae: 18786.4062
Epoch 50/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 18806.7598 - mae: 18806.7598
Epoch 51/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18809.0938 - mae: 18809.0938
Epoch 52/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18816.5332 - mae: 18816.5332
Epoch 53/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18798.9199 - mae: 18798.9199
Epoch 54/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18790.1953 - mae: 18790.1953
Epoch 55/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 18786.3730 - mae: 18786.3730
Epoch 56/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 18742.2852 - mae: 18742.2852
Epoch 57/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 18758.6348 - mae: 18758.6348
Epoch 58/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 18778.6152 - mae: 18778.6152
Epoch 59/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 18802.7832 - mae: 18802.7832
Epoch 60/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18750.1016 - mae: 18750.1016
Epoch 61/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 18734.5332 - mae: 18734.5332
Epoch 62/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18732.2891 - mae: 18732.2891
Epoch 63/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 18716.2734 - mae: 18716.2734
Epoch 64/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18712.3906 - mae: 18712.3906
Epoch 65/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18609.2793 - mae: 18609.2793
Epoch 66/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18189.4551 - mae: 18189.4551
Epoch 67/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17741.8242 - mae: 17741.8242
Epoch 68/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 17407.5332 - mae: 17407.5332
Epoch 69/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 17163.7090 - mae: 17163.7090
Epoch 70/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 16948.8652 - mae: 16948.8652
Epoch 71/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16805.1211 - mae: 16805.1211
Epoch 72/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 16658.8145 - mae: 16658.8145
Epoch 73/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16521.4551 - mae: 16521.4551
Epoch 74/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16319.0127 - mae: 16319.0127
Epoch 75/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16074.7441 - mae: 16074.7441
Epoch 76/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15938.6201 - mae: 15938.6201
Epoch 77/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15782.5068 - mae: 15782.5068
Epoch 78/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15595.1104 - mae: 15595.1104
Epoch 79/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15451.4102 - mae: 15451.4102
Epoch 80/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 15294.1348 - mae: 15294.1348
Epoch 81/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 15140.9170 - mae: 15140.9170
Epoch 82/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 15020.0234 - mae: 15020.0234
Epoch 83/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 14938.0557 - mae: 14938.0557
Epoch 84/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 14772.7480 - mae: 14772.7480
Epoch 85/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 14696.9795 - mae: 14696.9795
Epoch 86/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14594.0498 - mae: 14594.0498
Epoch 87/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 14537.1719 - mae: 14537.1719
Epoch 88/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 14309.5518 - mae: 14309.5518
Epoch 89/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14260.1699 - mae: 14260.1699
Epoch 90/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 14156.9990 - mae: 14156.9990
Epoch 91/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 14043.9551 - mae: 14043.9551
Epoch 92/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14034.1309 - mae: 14034.1309
Epoch 93/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13896.6689 - mae: 13896.6689
Epoch 94/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13808.9658 - mae: 13808.9658
Epoch 95/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13775.0322 - mae: 13775.0322
Epoch 96/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13692.7500 - mae: 13692.7500
Epoch 97/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13567.9414 - mae: 13567.9414
Epoch 98/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13535.5176 - mae: 13535.5176
Epoch 99/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13481.7227 - mae: 13481.7227
Epoch 100/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13450.3057 - mae: 13450.3057
Epoch 101/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13413.1074 - mae: 13413.1074
Epoch 102/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13245.5420 - mae: 13245.5420
Epoch 103/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13128.0107 - mae: 13128.0107
Epoch 104/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13286.3535 - mae: 13286.3535
Epoch 105/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13068.1953 - mae: 13068.1953
Epoch 106/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13005.4980 - mae: 13005.4980
Epoch 107/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 12965.0166 - mae: 12965.0166
Epoch 108/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 12906.0527 - mae: 12906.0527
Epoch 109/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 12828.1387 - mae: 12828.1387
Epoch 110/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12617.9678 - mae: 12617.9678
Epoch 111/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12605.4229 - mae: 12605.4229
Epoch 112/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 12563.1328 - mae: 12563.1328
Epoch 113/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12692.2178 - mae: 12692.2178
Epoch 114/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12518.8418 - mae: 12518.8418
Epoch 115/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12367.9922 - mae: 12367.9922
Epoch 116/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 12388.4170 - mae: 12388.4170
Epoch 117/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 12228.4990 - mae: 12228.4990
Epoch 118/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12212.7051 - mae: 12212.7051
Epoch 119/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 12129.4561 - mae: 12129.4561
Epoch 120/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12149.4590 - mae: 12149.4590
Epoch 121/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11935.7383 - mae: 11935.7383
Epoch 122/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11857.1816 - mae: 11857.1816
Epoch 123/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11830.7969 - mae: 11830.7969
Epoch 124/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11637.3398 - mae: 11637.3398
Epoch 125/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11642.3760 - mae: 11642.3760
Epoch 126/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11452.2588 - mae: 11452.2588
Epoch 127/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11467.6465 - mae: 11467.6465
Epoch 128/128
84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11377.0117 - mae: 11377.0117
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

[I 2026-10-20 12:52:46,123] Trial 0 finished with value: 0.8757333911043061 and parameters: {'epochs': 128, 'batch_size': 64, 'units_layer1': 118, 'units_layer2': 98, 'optimizer': 'adam', 'learning_rate': 0.029103708184859606}. Best is trial 0 with value: 0.8757333911043061.

Epoch 1/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 28366.7852 - mae: 28366.7852
Epoch 2/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 21628.4043 - mae: 21628.4043
Epoch 3/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20021.3730 - mae: 20021.3730
Epoch 4/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19234.8086 - mae: 19234.8086
Epoch 5/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18825.0684 - mae: 18825.0703
Epoch 6/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18465.9551 - mae: 18465.9570
Epoch 7/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 17252.5605 - mae: 17252.5605
Epoch 8/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 16145.3809 - mae: 16145.3809
Epoch 9/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 15233.4688 - mae: 15233.4688
Epoch 10/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15125.2500 - mae: 15125.2500
Epoch 11/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 14212.5391 - mae: 14212.5391
Epoch 12/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 14215.0830 - mae: 14215.0830
Epoch 13/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 14021.9873 - mae: 14021.9873
Epoch 14/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 13823.2188 - mae: 13823.2188
Epoch 15/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 13657.3213 - mae: 13657.3213
Epoch 16/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12866.0938 - mae: 12866.0938
Epoch 17/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12593.9980 - mae: 12593.9980
Epoch 18/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12151.4883 - mae: 12151.4883
Epoch 19/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12450.5850 - mae: 12450.5850
Epoch 20/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 12261.3936 - mae: 12261.3936
Epoch 21/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 11761.6143 - mae: 11761.6143
Epoch 22/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 11990.8213 - mae: 11990.8213
Epoch 23/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12115.4863 - mae: 12115.4863
Epoch 24/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11456.2959 - mae: 11456.2959
Epoch 25/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11268.8232 - mae: 11268.8232
Epoch 26/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11280.1455 - mae: 11280.1455
Epoch 27/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11087.7852 - mae: 11087.7852
Epoch 28/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10922.8848 - mae: 10922.8848
Epoch 29/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11590.0283 - mae: 11590.0293
Epoch 30/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 10703.5537 - mae: 10703.5537
Epoch 31/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 10085.7070 - mae: 10085.7070
Epoch 32/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 10380.7236 - mae: 10380.7236
Epoch 33/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 10694.0244 - mae: 10694.0244
Epoch 34/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 10178.1377 - mae: 10178.1377
Epoch 35/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 10191.8525 - mae: 10191.8525
Epoch 36/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 10378.4395 - mae: 10378.4395
Epoch 37/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 10029.1855 - mae: 10029.1855
Epoch 38/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 10235.4082 - mae: 10235.4082
Epoch 39/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 9761.6465 - mae: 9761.6475
Epoch 40/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 9697.8779 - mae: 9697.8779
Epoch 41/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9252.3906 - mae: 9252.3906
Epoch 42/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 9182.4619 - mae: 9182.4619
Epoch 43/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9282.2910 - mae: 9282.2900
Epoch 44/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9457.9336 - mae: 9457.9336
Epoch 45/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9128.2402 - mae: 9128.2402
Epoch 46/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9187.1992 - mae: 9187.1992
Epoch 47/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 9363.6074 - mae: 9363.6074
Epoch 48/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 9376.5176 - mae: 9376.5176
Epoch 49/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9396.9375 - mae: 9396.9375
Epoch 50/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9237.8760 - mae: 9237.8760
Epoch 51/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8979.3320 - mae: 8979.3320
Epoch 52/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 8857.3984 - mae: 8857.3984
Epoch 53/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8702.6768 - mae: 8702.6768
Epoch 54/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8859.1113 - mae: 8859.1113
Epoch 55/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 9347.3906 - mae: 9347.3906
Epoch 56/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9323.4434 - mae: 9323.4434
Epoch 57/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8770.1025 - mae: 8770.1025
Epoch 58/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8669.7725 - mae: 8669.7725
Epoch 59/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8563.5674 - mae: 8563.5674
Epoch 60/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9156.5225 - mae: 9156.5225
Epoch 61/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9290.4297 - mae: 9290.4297
Epoch 62/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8465.6260 - mae: 8465.6260
Epoch 63/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8820.7812 - mae: 8820.7803
Epoch 64/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8787.8877 - mae: 8787.8896
Epoch 65/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8622.0986 - mae: 8622.0986
Epoch 66/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8808.1318 - mae: 8808.1318
Epoch 67/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8257.0059 - mae: 8257.0059
Epoch 68/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8953.0264 - mae: 8953.0264
Epoch 69/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8489.9951 - mae: 8489.9951
Epoch 70/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8589.3838 - mae: 8589.3838
Epoch 71/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8713.6270 - mae: 8713.6270
Epoch 72/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8273.1934 - mae: 8273.1934
Epoch 73/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8608.6562 - mae: 8608.6562
Epoch 74/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8505.2695 - mae: 8505.2695
Epoch 75/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8299.8389 - mae: 8299.8389
Epoch 76/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8369.5928 - mae: 8369.5928
Epoch 77/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8363.2881 - mae: 8363.2881
Epoch 78/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8371.0889 - mae: 8371.0889
Epoch 79/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8513.7686 - mae: 8513.7686
Epoch 80/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8105.0132 - mae: 8105.0132
Epoch 81/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8435.8496 - mae: 8435.8496
Epoch 82/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8452.8779 - mae: 8452.8779
Epoch 83/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 8271.7754 - mae: 8271.7754
Epoch 84/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8562.2432 - mae: 8562.2432
Epoch 85/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8139.1377 - mae: 8139.1377
Epoch 86/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 8195.8066 - mae: 8195.8066
Epoch 87/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8018.2344 - mae: 8018.2354
Epoch 88/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8175.0308 - mae: 8175.0308
Epoch 89/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8695.0918 - mae: 8695.0918
Epoch 90/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8629.0449 - mae: 8629.0449
Epoch 91/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8450.4316 - mae: 8450.4316
Epoch 92/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8360.8467 - mae: 8360.8467
Epoch 93/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8206.5781 - mae: 8206.5781
Epoch 94/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8384.2139 - mae: 8384.2139
Epoch 95/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8418.7119 - mae: 8418.7119
Epoch 96/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8204.7051 - mae: 8204.7051
Epoch 97/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8385.8857 - mae: 8385.8857
Epoch 98/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 8113.3779 - mae: 8113.3779
Epoch 99/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 8033.0547 - mae: 8033.0547
Epoch 100/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7991.4043 - mae: 7991.4043
Epoch 101/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7688.1128 - mae: 7688.1128
Epoch 102/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7848.7314 - mae: 7848.7314
Epoch 103/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8246.0049 - mae: 8246.0049
Epoch 104/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8306.6543 - mae: 8306.6543
Epoch 105/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8505.3359 - mae: 8505.3350
Epoch 106/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8387.2979 - mae: 8387.2979
Epoch 107/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8141.1274 - mae: 8141.1274
Epoch 108/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7923.3257 - mae: 7923.3257
Epoch 109/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8109.4355 - mae: 8109.4355
Epoch 110/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7969.5034 - mae: 7969.5034
Epoch 111/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7941.3379 - mae: 7941.3379
Epoch 112/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7979.2007 - mae: 7979.2007
Epoch 113/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7714.7803 - mae: 7714.7803
Epoch 114/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8154.2827 - mae: 8154.2827
Epoch 115/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7795.6753 - mae: 7795.6753
Epoch 116/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8568.7354 - mae: 8568.7354
Epoch 117/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7867.8979 - mae: 7867.8979
Epoch 118/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8138.7661 - mae: 8138.7661
Epoch 119/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7936.3091 - mae: 7936.3091
Epoch 120/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7865.0557 - mae: 7865.0557
Epoch 121/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7911.7134 - mae: 7911.7134
Epoch 122/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7987.3208 - mae: 7987.3208
Epoch 123/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7856.7393 - mae: 7856.7393
Epoch 124/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7958.7817 - mae: 7958.7817
Epoch 125/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8080.1943 - mae: 8080.1943
Epoch 126/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7978.9512 - mae: 7978.9512
Epoch 127/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7972.4795 - mae: 7972.4795
Epoch 128/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7955.7075 - mae: 7955.7075
Epoch 129/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7592.9722 - mae: 7592.9736
Epoch 130/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7912.3569 - mae: 7912.3569
Epoch 131/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7940.3779 - mae: 7940.3784
Epoch 132/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7803.2466 - mae: 7803.2466
Epoch 133/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8165.0928 - mae: 8165.0928
Epoch 134/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7739.9746 - mae: 7739.9731
Epoch 135/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8057.3413 - mae: 8057.3413
Epoch 136/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7794.9092 - mae: 7794.9092
Epoch 137/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7950.4233 - mae: 7950.4233
Epoch 138/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7715.3901 - mae: 7715.3901
Epoch 139/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7989.5874 - mae: 7989.5874
Epoch 140/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8396.1914 - mae: 8396.1914
Epoch 141/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7841.6333 - mae: 7841.6333
Epoch 142/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7948.0889 - mae: 7948.0889
Epoch 143/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7890.9614 - mae: 7890.9614
Epoch 144/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7702.3823 - mae: 7702.3823
Epoch 145/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7615.3857 - mae: 7615.3857
Epoch 146/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7932.5874 - mae: 7932.5874
Epoch 147/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7715.0161 - mae: 7715.0161
Epoch 148/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7959.6260 - mae: 7959.6260
Epoch 149/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7841.7866 - mae: 7841.7866
Epoch 150/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7867.1606 - mae: 7867.1606
Epoch 151/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7897.1504 - mae: 7897.1504
Epoch 152/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7860.0342 - mae: 7860.0342
Epoch 153/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7751.7769 - mae: 7751.7769
Epoch 154/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7833.9985 - mae: 7833.9985
Epoch 155/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7865.3887 - mae: 7865.3887
Epoch 156/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7600.5776 - mae: 7600.5776
Epoch 157/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7657.5952 - mae: 7657.5952
Epoch 158/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7520.1309 - mae: 7520.1309
Epoch 159/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7680.0493 - mae: 7680.0493
Epoch 160/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7615.3257 - mae: 7615.3257
Epoch 161/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7947.8833 - mae: 7947.8833
Epoch 162/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8421.1221 - mae: 8421.1230
Epoch 163/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7654.6016 - mae: 7654.6001
Epoch 164/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7829.0894 - mae: 7829.0894
Epoch 165/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8091.1401 - mae: 8091.1401
Epoch 166/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7985.7603 - mae: 7985.7603
Epoch 167/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7689.7266 - mae: 7689.7266
Epoch 168/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7815.2305 - mae: 7815.2305
Epoch 169/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7578.4287 - mae: 7578.4287
Epoch 170/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7785.9058 - mae: 7785.9058
Epoch 171/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8386.7861 - mae: 8386.7861
Epoch 172/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7575.3496 - mae: 7575.3506
Epoch 173/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7972.8213 - mae: 7972.8213
Epoch 174/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8120.4346 - mae: 8120.4346
Epoch 175/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7957.5220 - mae: 7957.5215
Epoch 176/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7643.2588 - mae: 7643.2588
Epoch 177/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7536.0352 - mae: 7536.0352
Epoch 178/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7643.1641 - mae: 7643.1641
Epoch 179/179
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7961.0122 - mae: 7961.0122
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

[I 2026-10-20 12:54:21,393] Trial 1 finished with value: 0.927542719015739 and parameters: {'epochs': 179, 'batch_size': 25, 'units_layer1': 107, 'units_layer2': 66, 'optimizer': 'adam', 'learning_rate': 0.5219038590537444}. Best is trial 1 with value: 0.927542719015739.

Epoch 1/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 110612.8438 - mae: 110612.8438
Epoch 2/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 74838.4766 - mae: 74838.4766
Epoch 3/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 40763.0938 - mae: 40763.0977
Epoch 4/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 31355.9805 - mae: 31355.9805
Epoch 5/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 24485.4121 - mae: 24485.4121
Epoch 6/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 22046.3789 - mae: 22046.3789
Epoch 7/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 21343.3984 - mae: 21343.3984
Epoch 8/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21071.7637 - mae: 21071.7637
Epoch 9/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20903.2246 - mae: 20903.2266
Epoch 10/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20796.9961 - mae: 20796.9961
Epoch 11/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20697.7734 - mae: 20697.7734
Epoch 12/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20620.0137 - mae: 20620.0137
Epoch 13/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20553.0781 - mae: 20553.0781
Epoch 14/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20507.8711 - mae: 20507.8711
Epoch 15/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20469.6191 - mae: 20469.6191
Epoch 16/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20432.9785 - mae: 20432.9785
Epoch 17/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20399.4824 - mae: 20399.4824
Epoch 18/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20363.4141 - mae: 20363.4141
Epoch 19/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20322.3672 - mae: 20322.3672
Epoch 20/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20282.5195 - mae: 20282.5195
Epoch 21/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20247.2891 - mae: 20247.2910
Epoch 22/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20207.4570 - mae: 20207.4570
Epoch 23/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20165.7266 - mae: 20165.7266
Epoch 24/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20124.5254 - mae: 20124.5254
Epoch 25/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20077.9746 - mae: 20077.9746
Epoch 26/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20033.2500 - mae: 20033.2500
Epoch 27/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19981.1445 - mae: 19981.1445
Epoch 28/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19928.0098 - mae: 19928.0098
Epoch 29/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19867.5527 - mae: 19867.5527
Epoch 30/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19805.1680 - mae: 19805.1680
Epoch 31/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19725.4160 - mae: 19725.4160
Epoch 32/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19637.0879 - mae: 19637.0879
Epoch 33/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19556.0762 - mae: 19556.0762
Epoch 34/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19453.9961 - mae: 19453.9961
Epoch 35/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19357.0801 - mae: 19357.0801
Epoch 36/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19242.0996 - mae: 19242.0996
Epoch 37/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 19100.8340 - mae: 19100.8340
Epoch 38/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18972.3516 - mae: 18972.3516
Epoch 39/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18826.4102 - mae: 18826.4102
Epoch 40/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18675.2832 - mae: 18675.2832
Epoch 41/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 18536.2754 - mae: 18536.2754
Epoch 42/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 18405.5840 - mae: 18405.5840
Epoch 43/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18269.5254 - mae: 18269.5254
Epoch 44/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 18132.0098 - mae: 18132.0098
Epoch 45/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 17998.7988 - mae: 17998.7988
Epoch 46/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17874.0547 - mae: 17874.0547
Epoch 47/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17761.6074 - mae: 17761.6074
Epoch 48/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17664.0352 - mae: 17664.0352
Epoch 49/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17550.3750 - mae: 17550.3750
Epoch 50/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17464.7637 - mae: 17464.7637
Epoch 51/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17376.6504 - mae: 17376.6504
Epoch 52/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17308.8535 - mae: 17308.8535
Epoch 53/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17233.3926 - mae: 17233.3926
Epoch 54/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 17172.1211 - mae: 17172.1211
Epoch 55/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17109.0918 - mae: 17109.0918
Epoch 56/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17059.9746 - mae: 17059.9746
Epoch 57/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17011.3164 - mae: 17011.3164
Epoch 58/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16958.1504 - mae: 16958.1504
Epoch 59/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16903.8125 - mae: 16903.8125
Epoch 60/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16854.3047 - mae: 16854.3047
Epoch 61/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16807.6328 - mae: 16807.6328
Epoch 62/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 16764.5000 - mae: 16764.4980
Epoch 63/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16710.7852 - mae: 16710.7852
Epoch 64/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16665.1445 - mae: 16665.1445
Epoch 65/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16623.6953 - mae: 16623.6953
Epoch 66/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16576.5059 - mae: 16576.5059
Epoch 67/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16534.6152 - mae: 16534.6152
Epoch 68/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16498.3164 - mae: 16498.3164
Epoch 69/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16451.2422 - mae: 16451.2422
Epoch 70/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16406.6855 - mae: 16406.6855
Epoch 71/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 16364.0195 - mae: 16364.0195
Epoch 72/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16311.5654 - mae: 16311.5654
Epoch 73/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16260.0332 - mae: 16260.0332
Epoch 74/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16205.1074 - mae: 16205.1074
Epoch 75/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16154.8770 - mae: 16154.8740
Epoch 76/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 16105.4004 - mae: 16105.4004
Epoch 77/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16059.1172 - mae: 16059.1172
Epoch 78/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16010.6709 - mae: 16010.6709
Epoch 79/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15959.1553 - mae: 15959.1562
Epoch 80/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15908.0391 - mae: 15908.0391
Epoch 81/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15851.9834 - mae: 15851.9834
Epoch 82/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15805.6904 - mae: 15805.6904
Epoch 83/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 15755.6240 - mae: 15755.6240
Epoch 84/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15713.6309 - mae: 15713.6309
Epoch 85/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15671.2744 - mae: 15671.2744
Epoch 86/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 15627.0713 - mae: 15627.0713
Epoch 87/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15577.4844 - mae: 15577.4844
Epoch 88/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15526.7471 - mae: 15526.7471
Epoch 89/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15475.8428 - mae: 15475.8428
Epoch 90/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15425.3574 - mae: 15425.3574
Epoch 91/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15380.2734 - mae: 15380.2734
Epoch 92/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15336.7402 - mae: 15336.7402
Epoch 93/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15292.5947 - mae: 15292.5947
Epoch 94/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15241.0215 - mae: 15241.0215
Epoch 95/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15198.7178 - mae: 15198.7178
Epoch 96/96
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15157.1650 - mae: 15157.1650
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

[I 2026-10-20 12:54:52,091] Trial 2 finished with value: 0.8322787426500745 and parameters: {'epochs': 96, 'batch_size': 45, 'units_layer1': 55, 'units_layer2': 37, 'optimizer': 'rmsprop', 'learning_rate': 0.01109214732449919}. Best is trial 1 with value: 0.927542719015739.

Epoch 1/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 33545.2461 - mae: 33545.2461
Epoch 2/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 21748.9141 - mae: 21748.9121
Epoch 3/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 21322.7500 - mae: 21322.7500
Epoch 4/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 21033.0938 - mae: 21033.0938
Epoch 5/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20889.4102 - mae: 20889.4102
Epoch 6/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 20848.1094 - mae: 20848.1094
Epoch 7/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20663.5059 - mae: 20663.5059
Epoch 8/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20544.5352 - mae: 20544.5352
Epoch 9/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20036.0625 - mae: 20036.0625
Epoch 10/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19431.8770 - mae: 19431.8770
Epoch 11/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 18942.6523 - mae: 18942.6523
Epoch 12/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18774.3477 - mae: 18774.3477
Epoch 13/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 18671.3066 - mae: 18671.3066
Epoch 14/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18558.5488 - mae: 18558.5488
Epoch 15/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18302.7207 - mae: 18302.7207
Epoch 16/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 18197.0684 - mae: 18197.0684
Epoch 17/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17983.7070 - mae: 17983.7070
Epoch 18/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17609.5371 - mae: 17609.5371
Epoch 19/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17136.8086 - mae: 17136.8086
Epoch 20/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16781.3887 - mae: 16781.3887
Epoch 21/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16531.2324 - mae: 16531.2324
Epoch 22/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 16314.3760 - mae: 16314.3770
Epoch 23/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 16117.8887 - mae: 16117.8887
Epoch 24/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 15918.9814 - mae: 15918.9814
Epoch 25/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15761.3203 - mae: 15761.3203
Epoch 26/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 15587.0820 - mae: 15587.0820
Epoch 27/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 15496.4688 - mae: 15496.4688
Epoch 28/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 15340.6768 - mae: 15340.6768
Epoch 29/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 15253.4277 - mae: 15253.4277
Epoch 30/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15225.7705 - mae: 15225.7705
Epoch 31/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 15035.5342 - mae: 15035.5342
Epoch 32/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 15078.3535 - mae: 15078.3516
Epoch 33/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15026.9307 - mae: 15026.9307
Epoch 34/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15008.9873 - mae: 15008.9873
Epoch 35/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14942.3535 - mae: 14942.3535
Epoch 36/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14723.8135 - mae: 14723.8135
Epoch 37/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14731.5146 - mae: 14731.5146
Epoch 38/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14787.1865 - mae: 14787.1865
Epoch 39/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14689.7666 - mae: 14689.7666
Epoch 40/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14611.7520 - mae: 14611.7520
Epoch 41/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14497.4561 - mae: 14497.4561
Epoch 42/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14401.8115 - mae: 14401.8115
Epoch 43/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14478.5566 - mae: 14478.5566
Epoch 44/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14305.3633 - mae: 14305.3633
Epoch 45/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14274.6982 - mae: 14274.6982
Epoch 46/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14220.8750 - mae: 14220.8750
Epoch 47/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14139.0654 - mae: 14139.0654
Epoch 48/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 14138.9941 - mae: 14138.9951
Epoch 49/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13965.3291 - mae: 13965.3291
Epoch 50/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 13775.1426 - mae: 13775.1426
Epoch 51/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13722.2871 - mae: 13722.2871
Epoch 52/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13603.2969 - mae: 13603.2969
Epoch 53/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13645.3018 - mae: 13645.3018
Epoch 54/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13427.1836 - mae: 13427.1836
Epoch 55/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13442.8994 - mae: 13442.8994
Epoch 56/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13242.8623 - mae: 13242.8623
Epoch 57/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13231.0771 - mae: 13231.0771
Epoch 58/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13205.5615 - mae: 13205.5615
Epoch 59/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13115.6406 - mae: 13115.6406
Epoch 60/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13084.0225 - mae: 13084.0225
Epoch 61/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 12979.7432 - mae: 12979.7432
Epoch 62/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12908.4375 - mae: 12908.4375
Epoch 63/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12790.7217 - mae: 12790.7217
Epoch 64/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12760.3340 - mae: 12760.3330
Epoch 65/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12772.1211 - mae: 12772.1211
Epoch 66/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12547.1963 - mae: 12547.1963
Epoch 67/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12491.2314 - mae: 12491.2314
Epoch 68/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12527.0234 - mae: 12527.0234
Epoch 69/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12352.3145 - mae: 12352.3145
Epoch 70/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 12389.0264 - mae: 12389.0264
Epoch 71/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12410.9521 - mae: 12410.9521
Epoch 72/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12276.7480 - mae: 12276.7480
Epoch 73/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12083.1953 - mae: 12083.1953
Epoch 74/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12140.5752 - mae: 12140.5752
Epoch 75/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12051.8896 - mae: 12051.8896
Epoch 76/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11934.7939 - mae: 11934.7939
Epoch 77/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11944.5029 - mae: 11944.5029
Epoch 78/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11864.1953 - mae: 11864.1953
Epoch 79/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11851.4277 - mae: 11851.4277
Epoch 80/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11677.5234 - mae: 11677.5234
Epoch 81/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11773.4521 - mae: 11773.4521
Epoch 82/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11756.7559 - mae: 11756.7539
Epoch 83/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11595.9648 - mae: 11595.9658
Epoch 84/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11604.5420 - mae: 11604.5420
Epoch 85/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11716.3359 - mae: 11716.3359
Epoch 86/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11514.9492 - mae: 11514.9492
Epoch 87/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11548.5654 - mae: 11548.5654
Epoch 88/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11467.1533 - mae: 11467.1533
Epoch 89/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11526.7363 - mae: 11526.7363
Epoch 90/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11369.8525 - mae: 11369.8525
Epoch 91/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11348.8135 - mae: 11348.8135
Epoch 92/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11380.9111 - mae: 11380.9111
Epoch 93/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11277.2598 - mae: 11277.2598
Epoch 94/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11220.3213 - mae: 11220.3213
Epoch 95/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11245.6279 - mae: 11245.6279
Epoch 96/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11172.8564 - mae: 11172.8564
Epoch 97/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11113.5674 - mae: 11113.5674
Epoch 98/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11112.8135 - mae: 11112.8135
Epoch 99/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 11107.7227 - mae: 11107.7227
Epoch 100/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11045.9004 - mae: 11045.9004
Epoch 101/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11077.6572 - mae: 11077.6572
Epoch 102/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11009.5723 - mae: 11009.5723
Epoch 103/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10983.5703 - mae: 10983.5703
Epoch 104/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10970.2549 - mae: 10970.2549
Epoch 105/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10920.5215 - mae: 10920.5215
Epoch 106/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10771.9824 - mae: 10771.9824
Epoch 107/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10843.2500 - mae: 10843.2500
Epoch 108/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10777.5283 - mae: 10777.5283
Epoch 109/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10713.7744 - mae: 10713.7744
Epoch 110/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10596.5146 - mae: 10596.5146
Epoch 111/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10615.7178 - mae: 10615.7178
Epoch 112/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10633.1807 - mae: 10633.1807
Epoch 113/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10498.5986 - mae: 10498.5986
Epoch 114/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10497.2920 - mae: 10497.2920
Epoch 115/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10464.1660 - mae: 10464.1660
Epoch 116/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10342.3115 - mae: 10342.3115
Epoch 117/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10410.7432 - mae: 10410.7432
Epoch 118/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10402.9521 - mae: 10402.9521
Epoch 119/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10195.7002 - mae: 10195.7002
Epoch 120/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10300.9844 - mae: 10300.9844
Epoch 121/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10226.5723 - mae: 10226.5723
Epoch 122/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10126.4297 - mae: 10126.4287
Epoch 123/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10180.0166 - mae: 10180.0166
Epoch 124/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10146.6133 - mae: 10146.6133
Epoch 125/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10083.6660 - mae: 10083.6660
Epoch 126/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10020.0391 - mae: 10020.0391
Epoch 127/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10036.7744 - mae: 10036.7744
Epoch 128/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9909.8135 - mae: 9909.8135
Epoch 129/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9988.4980 - mae: 9988.4980
Epoch 130/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9904.8525 - mae: 9904.8525
Epoch 131/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9909.6523 - mae: 9909.6523
Epoch 132/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9812.2012 - mae: 9812.2012
Epoch 133/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9799.9600 - mae: 9799.9600
Epoch 134/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9724.7148 - mae: 9724.7148
Epoch 135/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9668.3691 - mae: 9668.3691
Epoch 136/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9698.4043 - mae: 9698.4043
Epoch 137/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9699.1611 - mae: 9699.1611
Epoch 138/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9593.0186 - mae: 9593.0186
Epoch 139/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9593.7207 - mae: 9593.7207
Epoch 140/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9609.8975 - mae: 9609.8975
Epoch 141/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9555.1816 - mae: 9555.1816
Epoch 142/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9471.7646 - mae: 9471.7646
Epoch 143/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9460.2832 - mae: 9460.2832
Epoch 144/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9405.7832 - mae: 9405.7832
Epoch 145/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9453.7666 - mae: 9453.7666
Epoch 146/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9435.3730 - mae: 9435.3730
Epoch 147/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9320.6777 - mae: 9320.6777
Epoch 148/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9289.9893 - mae: 9289.9893
Epoch 149/149
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9294.9980 - mae: 9294.9980
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step

[I 2026-10-20 12:55:35,517] Trial 3 finished with value: 0.9095702348141268 and parameters: {'epochs': 149, 'batch_size': 48, 'units_layer1': 20, 'units_layer2': 60, 'optimizer': 'rmsprop', 'learning_rate': 0.1514248944828618}. Best is trial 1 with value: 0.927542719015739.

Epoch 1/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 95020.5859 - mae: 95020.5859
Epoch 2/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 39527.1133 - mae: 39527.1133
Epoch 3/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 25776.1699 - mae: 25776.1699
Epoch 4/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21811.7832 - mae: 21811.7832
Epoch 5/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 21157.3340 - mae: 21157.3340
Epoch 6/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20969.5820 - mae: 20969.5820
Epoch 7/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20838.7988 - mae: 20838.7988
Epoch 8/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20737.2969 - mae: 20737.2969
Epoch 9/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20657.0488 - mae: 20657.0488
Epoch 10/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20589.4336 - mae: 20589.4336
Epoch 11/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20526.9824 - mae: 20526.9824
Epoch 12/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20475.4766 - mae: 20475.4766
Epoch 13/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20421.9023 - mae: 20421.9023
Epoch 14/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20378.2148 - mae: 20378.2148
Epoch 15/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20330.4590 - mae: 20330.4590
Epoch 16/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20272.4316 - mae: 20272.4316
Epoch 17/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20202.2090 - mae: 20202.2090
Epoch 18/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20169.4102 - mae: 20169.4102
Epoch 19/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20110.9922 - mae: 20110.9922
Epoch 20/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20052.2480 - mae: 20052.2480
Epoch 21/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20012.1680 - mae: 20012.1680
Epoch 22/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19959.5723 - mae: 19959.5723
Epoch 23/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19920.9863 - mae: 19920.9863
Epoch 24/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19881.5020 - mae: 19881.5020
Epoch 25/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19844.3516 - mae: 19844.3516
Epoch 26/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19808.2793 - mae: 19808.2793
Epoch 27/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19778.9199 - mae: 19778.9199
Epoch 28/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19737.3594 - mae: 19737.3594
Epoch 29/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19686.4121 - mae: 19686.4121
Epoch 30/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19600.1309 - mae: 19600.1309
Epoch 31/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19502.7344 - mae: 19502.7344
Epoch 32/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19387.4453 - mae: 19387.4453
Epoch 33/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 19243.8770 - mae: 19243.8770
Epoch 34/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19086.0039 - mae: 19086.0039
Epoch 35/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18910.6777 - mae: 18910.6777
Epoch 36/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18732.3281 - mae: 18732.3281
Epoch 37/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18537.5410 - mae: 18537.5410
Epoch 38/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18360.6855 - mae: 18360.6875
Epoch 39/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18176.5078 - mae: 18176.5078
Epoch 40/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18016.8555 - mae: 18016.8535
Epoch 41/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17817.1992 - mae: 17817.1992
Epoch 42/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17638.4121 - mae: 17638.4121
Epoch 43/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17500.5996 - mae: 17500.5996
Epoch 44/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17387.8418 - mae: 17387.8418
Epoch 45/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 17293.2871 - mae: 17293.2871
Epoch 46/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17222.6699 - mae: 17222.6699
Epoch 47/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17137.2754 - mae: 17137.2754
Epoch 48/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17103.6484 - mae: 17103.6484
Epoch 49/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17049.3379 - mae: 17049.3379
Epoch 50/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17000.9082 - mae: 17000.9082
Epoch 51/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 16956.8711 - mae: 16956.8711
Epoch 52/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16919.4746 - mae: 16919.4746
Epoch 53/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16876.0039 - mae: 16876.0039
Epoch 54/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16849.9102 - mae: 16849.9102
Epoch 55/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16810.1387 - mae: 16810.1387
Epoch 56/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16773.1562 - mae: 16773.1562
Epoch 57/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16735.7188 - mae: 16735.7188
Epoch 58/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16704.1367 - mae: 16704.1367
Epoch 59/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16664.8535 - mae: 16664.8535
Epoch 60/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16646.6406 - mae: 16646.6406
Epoch 61/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16616.8281 - mae: 16616.8281
Epoch 62/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16583.4531 - mae: 16583.4531
Epoch 63/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16547.0039 - mae: 16547.0039
Epoch 64/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16515.1914 - mae: 16515.1914
Epoch 65/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16486.2598 - mae: 16486.2598
Epoch 66/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16454.7285 - mae: 16454.7285
Epoch 67/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16414.1387 - mae: 16414.1387
Epoch 68/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16372.5947 - mae: 16372.5947
Epoch 69/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16332.7852 - mae: 16332.7852
Epoch 70/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16290.0967 - mae: 16290.0967
Epoch 71/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16255.1162 - mae: 16255.1162
Epoch 72/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16213.9707 - mae: 16213.9707
Epoch 73/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16174.5088 - mae: 16174.5088
Epoch 74/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16115.0176 - mae: 16115.0176
Epoch 75/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16060.3838 - mae: 16060.3838
Epoch 76/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16004.9033 - mae: 16004.9033
Epoch 77/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15947.1133 - mae: 15947.1133
Epoch 78/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15885.5420 - mae: 15885.5420
Epoch 79/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15840.0615 - mae: 15840.0615
Epoch 80/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15783.5654 - mae: 15783.5654
Epoch 81/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 15725.0898 - mae: 15725.0898
Epoch 82/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15648.6768 - mae: 15648.6768
Epoch 83/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15612.0400 - mae: 15612.0400
Epoch 84/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15541.0566 - mae: 15541.0566
Epoch 85/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 15484.1748 - mae: 15484.1748
Epoch 86/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15434.6572 - mae: 15434.6572
Epoch 87/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15377.1865 - mae: 15377.1865
Epoch 88/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15335.5137 - mae: 15335.5137
Epoch 89/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15282.5273 - mae: 15282.5273
Epoch 90/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 15227.2217 - mae: 15227.2207
Epoch 91/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 15169.0781 - mae: 15169.0781
Epoch 92/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15120.6660 - mae: 15120.6660
Epoch 93/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15057.3350 - mae: 15057.3350
Epoch 94/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15003.2041 - mae: 15003.2041
Epoch 95/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14946.3506 - mae: 14946.3506
Epoch 96/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14883.7920 - mae: 14883.7920
Epoch 97/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14808.7090 - mae: 14808.7090
Epoch 98/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14720.5186 - mae: 14720.5186
Epoch 99/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 14612.5273 - mae: 14612.5273
Epoch 100/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14544.4453 - mae: 14544.4453
Epoch 101/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14443.6641 - mae: 14443.6641
Epoch 102/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14358.1572 - mae: 14358.1572
Epoch 103/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 14275.8730 - mae: 14275.8730
Epoch 104/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 14191.2949 - mae: 14191.2949
Epoch 105/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14107.2715 - mae: 14107.2715
Epoch 106/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14042.9102 - mae: 14042.9102
Epoch 107/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13977.2539 - mae: 13977.2539
Epoch 108/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13911.5459 - mae: 13911.5459
Epoch 109/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13849.2197 - mae: 13849.2197
Epoch 110/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13789.7021 - mae: 13789.7021
Epoch 111/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13734.2217 - mae: 13734.2217
Epoch 112/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13686.9189 - mae: 13686.9189
Epoch 113/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13635.0439 - mae: 13635.0439
Epoch 114/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13593.1328 - mae: 13593.1328
Epoch 115/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13535.3340 - mae: 13535.3340
Epoch 116/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13482.4453 - mae: 13482.4453
Epoch 117/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13456.4209 - mae: 13456.4209
Epoch 118/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13398.8232 - mae: 13398.8232
Epoch 119/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13350.9443 - mae: 13350.9443
Epoch 120/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13327.1328 - mae: 13327.1328
Epoch 121/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13278.2754 - mae: 13278.2754
Epoch 122/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13244.0312 - mae: 13244.0312
Epoch 123/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13211.4717 - mae: 13211.4717
Epoch 124/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13171.1221 - mae: 13171.1221
Epoch 125/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13130.5430 - mae: 13130.5430
Epoch 126/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13098.0664 - mae: 13098.0664
Epoch 127/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13066.4785 - mae: 13066.4785
Epoch 128/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13041.2109 - mae: 13041.2109
Epoch 129/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12998.5801 - mae: 12998.5801
Epoch 130/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12961.5947 - mae: 12961.5947
Epoch 131/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12931.6162 - mae: 12931.6162
Epoch 132/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 12893.7754 - mae: 12893.7754
Epoch 133/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12847.7539 - mae: 12847.7539
Epoch 134/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12827.3535 - mae: 12827.3535
Epoch 135/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12798.7578 - mae: 12798.7578
Epoch 136/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12757.0381 - mae: 12757.0381
Epoch 137/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 12717.5234 - mae: 12717.5234
Epoch 138/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12685.3711 - mae: 12685.3711
Epoch 139/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12650.9043 - mae: 12650.9043
Epoch 140/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 12607.2881 - mae: 12607.2881
Epoch 141/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 12600.4795 - mae: 12600.4795
Epoch 142/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12557.2900 - mae: 12557.2900
Epoch 143/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12549.5547 - mae: 12549.5547
Epoch 144/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 12510.8008 - mae: 12510.8008
Epoch 145/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12476.6396 - mae: 12476.6396
Epoch 146/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12447.9697 - mae: 12447.9697
Epoch 147/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12420.4658 - mae: 12420.4658
Epoch 148/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12402.4375 - mae: 12402.4375
Epoch 149/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12368.3682 - mae: 12368.3682
Epoch 150/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 12349.6104 - mae: 12349.6104
Epoch 151/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 12322.3691 - mae: 12322.3691
Epoch 152/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12297.1172 - mae: 12297.1172
Epoch 153/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12252.7109 - mae: 12252.7109
Epoch 154/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12237.1689 - mae: 12237.1689
Epoch 155/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12207.6035 - mae: 12207.6035
Epoch 156/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12185.3613 - mae: 12185.3613
Epoch 157/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12148.8008 - mae: 12148.8008
Epoch 158/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12117.2588 - mae: 12117.2588
Epoch 159/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12118.9141 - mae: 12118.9141
Epoch 160/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12070.3057 - mae: 12070.3057
Epoch 161/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12054.2588 - mae: 12054.2588
Epoch 162/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12023.7812 - mae: 12023.7812
Epoch 163/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11992.2275 - mae: 11992.2275
Epoch 164/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11980.8828 - mae: 11980.8828
Epoch 165/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11984.4570 - mae: 11984.4570
Epoch 166/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11939.4609 - mae: 11939.4609
Epoch 167/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11917.9346 - mae: 11917.9346
Epoch 168/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11930.8184 - mae: 11930.8184
Epoch 169/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11882.7578 - mae: 11882.7578
Epoch 170/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11833.8682 - mae: 11833.8682
Epoch 171/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11838.9990 - mae: 11838.9990
Epoch 172/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11806.5820 - mae: 11806.5820
Epoch 173/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11805.5068 - mae: 11805.5068
Epoch 174/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11805.7559 - mae: 11805.7559
Epoch 175/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11776.5635 - mae: 11776.5635
Epoch 176/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11756.0615 - mae: 11756.0615
Epoch 177/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11728.4229 - mae: 11728.4238
Epoch 178/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11703.3516 - mae: 11703.3516
Epoch 179/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11723.9961 - mae: 11723.9961
Epoch 180/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11697.7012 - mae: 11697.7012
Epoch 181/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11631.5938 - mae: 11631.5938
Epoch 182/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11657.6113 - mae: 11657.6113
Epoch 183/183
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11635.9248 - mae: 11635.9248
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step

[I 2026-10-20 12:56:25,594] Trial 4 finished with value: 0.8877539060387801 and parameters: {'epochs': 183, 'batch_size': 56, 'units_layer1': 102, 'units_layer2': 51, 'optimizer': 'rmsprop', 'learning_rate': 0.016783983846530362}. Best is trial 1 with value: 0.927542719015739.

Epoch 1/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 31872.7344 - mae: 31872.7344
Epoch 2/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 21680.5273 - mae: 21680.5273
Epoch 3/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20914.4062 - mae: 20914.4062
Epoch 4/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20378.8594 - mae: 20378.8594
Epoch 5/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20328.3027 - mae: 20328.3027
Epoch 6/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20131.8105 - mae: 20131.8105
Epoch 7/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20417.1484 - mae: 20417.1484
Epoch 8/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19758.4199 - mae: 19758.4199
Epoch 9/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18709.8281 - mae: 18709.8281
Epoch 10/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18765.8984 - mae: 18765.8984
Epoch 11/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17860.2910 - mae: 17860.2910
Epoch 12/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17204.8906 - mae: 17204.8906
Epoch 13/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 16562.0996 - mae: 16562.0996
Epoch 14/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 16279.9160 - mae: 16279.9160
Epoch 15/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 15644.6230 - mae: 15644.6230
Epoch 16/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 15035.4805 - mae: 15035.4805
Epoch 17/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14741.2471 - mae: 14741.2471
Epoch 18/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14580.5596 - mae: 14580.5596
Epoch 19/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13927.6816 - mae: 13927.6816
Epoch 20/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 13971.7510 - mae: 13971.7510
Epoch 21/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 13467.0693 - mae: 13467.0693
Epoch 22/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 13464.8252 - mae: 13464.8252
Epoch 23/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 12350.8965 - mae: 12350.8965
Epoch 24/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12314.0361 - mae: 12314.0361
Epoch 25/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12397.3555 - mae: 12397.3555
Epoch 26/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 12293.0781 - mae: 12293.0781
Epoch 27/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 11693.6816 - mae: 11693.6816
Epoch 28/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11516.4922 - mae: 11516.4922
Epoch 29/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 11447.4893 - mae: 11447.4893
Epoch 30/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 11387.2002 - mae: 11387.2002
Epoch 31/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11046.9111 - mae: 11046.9111
Epoch 32/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10928.1279 - mae: 10928.1279
Epoch 33/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11019.5479 - mae: 11019.5479
Epoch 34/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10507.5957 - mae: 10507.5957
Epoch 35/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10754.8066 - mae: 10754.8066
Epoch 36/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10356.5439 - mae: 10356.5439
Epoch 37/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10556.0830 - mae: 10556.0830
Epoch 38/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10354.9902 - mae: 10354.9902
Epoch 39/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10094.2891 - mae: 10094.2891
Epoch 40/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10244.3350 - mae: 10244.3350
Epoch 41/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9719.7344 - mae: 9719.7344
Epoch 42/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9843.6807 - mae: 9843.6807
Epoch 43/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9749.9131 - mae: 9749.9131
Epoch 44/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9650.8389 - mae: 9650.8389
Epoch 45/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9551.6113 - mae: 9551.6113
Epoch 46/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9460.7588 - mae: 9460.7588
Epoch 47/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9371.4922 - mae: 9371.4922
Epoch 48/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9515.9092 - mae: 9515.9092
Epoch 49/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9279.5537 - mae: 9279.5537
Epoch 50/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 9199.6807 - mae: 9199.6807
Epoch 51/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8953.3867 - mae: 8953.3867
Epoch 52/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9096.1885 - mae: 9096.1885
Epoch 53/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9001.1719 - mae: 9001.1719
Epoch 54/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8940.1006 - mae: 8940.1006
Epoch 55/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9032.9346 - mae: 9032.9346
Epoch 56/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9284.5273 - mae: 9284.5273
Epoch 57/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8362.3506 - mae: 8362.3506
Epoch 58/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8519.0098 - mae: 8519.0098
Epoch 59/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8595.9736 - mae: 8595.9736
Epoch 60/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 8507.5957 - mae: 8507.5957
Epoch 61/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 8450.0078 - mae: 8450.0078
Epoch 62/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 8686.8604 - mae: 8686.8604
Epoch 63/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 8352.8701 - mae: 8352.8701
Epoch 64/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8192.3232 - mae: 8192.3232
Epoch 65/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 8210.1885 - mae: 8210.1885
Epoch 66/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8102.1523 - mae: 8102.1523
Epoch 67/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 8162.3628 - mae: 8162.3628
Epoch 68/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 8310.3555 - mae: 8310.3555
Epoch 69/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8076.4854 - mae: 8076.4854
Epoch 70/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 8089.6284 - mae: 8089.6284
Epoch 71/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8021.6426 - mae: 8021.6426
Epoch 72/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7947.2466 - mae: 7947.2466
Epoch 73/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 8124.9062 - mae: 8124.9062
Epoch 74/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7844.8862 - mae: 7844.8862
Epoch 75/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8025.0361 - mae: 8025.0361
Epoch 76/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7813.3413 - mae: 7813.3413
Epoch 77/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7720.1562 - mae: 7720.1562
Epoch 78/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 8163.2290 - mae: 8163.2290
Epoch 79/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7770.5996 - mae: 7770.5996
Epoch 80/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8170.1978 - mae: 8170.1978
Epoch 81/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7656.4277 - mae: 7656.4277
Epoch 82/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7589.7153 - mae: 7589.7153
Epoch 83/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7439.1699 - mae: 7439.1699
Epoch 84/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7766.9961 - mae: 7766.9966
Epoch 85/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7817.6582 - mae: 7817.6582
Epoch 86/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7560.7129 - mae: 7560.7129
Epoch 87/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7898.8286 - mae: 7898.8286
Epoch 88/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7529.1514 - mae: 7529.1514
Epoch 89/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7231.8701 - mae: 7231.8701
Epoch 90/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7434.4634 - mae: 7434.4634
Epoch 91/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7198.4458 - mae: 7198.4458
Epoch 92/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7231.6260 - mae: 7231.6260
Epoch 93/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7467.6572 - mae: 7467.6572
Epoch 94/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7295.8330 - mae: 7295.8330
Epoch 95/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7139.2100 - mae: 7139.2100
Epoch 96/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7259.9844 - mae: 7259.9844
Epoch 97/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6976.4346 - mae: 6976.4346
Epoch 98/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7119.0430 - mae: 7119.0430
Epoch 99/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7132.3950 - mae: 7132.3950
Epoch 100/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7102.1470 - mae: 7102.1470
Epoch 101/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7212.8345 - mae: 7212.8345
Epoch 102/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7152.5239 - mae: 7152.5239
Epoch 103/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7030.6226 - mae: 7030.6226
Epoch 104/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6842.0225 - mae: 6842.0225
Epoch 105/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7027.7153 - mae: 7027.7153
Epoch 106/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6771.3848 - mae: 6771.3848
Epoch 107/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6842.3965 - mae: 6842.3965
Epoch 108/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6694.0625 - mae: 6694.0625
Epoch 109/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7030.3052 - mae: 7030.3052
Epoch 110/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6822.7031 - mae: 6822.7031
Epoch 111/111
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7031.0024 - mae: 7031.0024
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

[I 2026-10-20 12:57:13,176] Trial 5 finished with value: 0.9347050753213417 and parameters: {'epochs': 111, 'batch_size': 35, 'units_layer1': 114, 'units_layer2': 78, 'optimizer': 'adam', 'learning_rate': 0.1765246477377277}. Best is trial 5 with value: 0.9347050753213417.

Epoch 1/55
104/104 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 64787.9961 - mae: 64787.9961
Epoch 2/55
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 22121.6152 - mae: 22121.6152
Epoch 3/55
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 21110.0605 - mae: 21110.0605
Epoch 4/55
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20830.1895 - mae: 20830.1895
Epoch 5/55
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20649.5449 - mae: 20649.5469
Epoch 6/55
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20563.9082 - mae: 20563.9082
Epoch 7/55
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20436.2227 - mae: 20436.2227
Epoch 8/55
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20307.5918 - mae: 20307.5918
Epoch 9/55
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20205.3789 - mae: 20205.3789
Epoch 10/55
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20140.4961 - mae: 20140.4941
Epoch 11/55
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20005.1641 - mae: 20005.1641
Epoch 12/55
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19912.6172 - mae: 19912.6172
Epoch 13/55
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19861.4941 - mae: 19861.4941
Epoch 14/55
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19771.7656 - mae: 19771.7656
Epoch 15/55
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19763.3379 - mae: 19763.3379
Epoch 16/55
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19686.6387 - mae: 19686.6387
Epoch 17/55
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19531.3574 - mae: 19531.3574
Epoch 18/55
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18966.2910 - mae: 18966.2910
Epoch 19/55
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18314.1523 - mae: 18314.1523
Epoch 20/55
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17981.7715 - mae: 17981.7715
Epoch 21/55
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17597.8867 - mae: 17597.8867
Epoch 22/55
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17295.9609 - mae: 17295.9609
Epoch 23/55
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17050.4883 - mae: 17050.4883
Epoch 24/55
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16905.3379 - mae: 16905.3379
Epoch 25/55
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16723.7051 - mae: 16723.7051
Epoch 26/55
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16627.6562 - mae: 16627.6562
Epoch 27/55
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16482.5176 - mae: 16482.5176
Epoch 28/55
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16428.8574 - mae: 16428.8574
Epoch 29/55
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16318.7119 - mae: 16318.7119
Epoch 30/55
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16258.1123 - mae: 16258.1123
Epoch 31/55
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16086.5938 - mae: 16086.5938
Epoch 32/55
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15912.7148 - mae: 15912.7148
Epoch 33/55
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15744.6094 - mae: 15744.6094
Epoch 34/55
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15559.2236 - mae: 15559.2236
Epoch 35/55
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15492.7119 - mae: 15492.7119
Epoch 36/55
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15323.3457 - mae: 15323.3457
Epoch 37/55
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15217.6592 - mae: 15217.6592
Epoch 38/55
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15079.3477 - mae: 15079.3477
Epoch 39/55
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 15014.7266 - mae: 15014.7266
Epoch 40/55
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15120.3564 - mae: 15120.3564
Epoch 41/55
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14878.9111 - mae: 14878.9111
Epoch 42/55
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14814.3545 - mae: 14814.3545
Epoch 43/55
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14710.9053 - mae: 14710.9053
Epoch 44/55
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14688.9258 - mae: 14688.9258
Epoch 45/55
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14567.5859 - mae: 14567.5859
Epoch 46/55
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14550.0938 - mae: 14550.0938
Epoch 47/55
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14500.0137 - mae: 14500.0137
Epoch 48/55
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14437.9922 - mae: 14437.9932
Epoch 49/55
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14399.2832 - mae: 14399.2832
Epoch 50/55
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14304.8418 - mae: 14304.8418
Epoch 51/55
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14261.2275 - mae: 14261.2275
Epoch 52/55
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14392.6445 - mae: 14392.6465
Epoch 53/55
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14109.8965 - mae: 14109.8965
Epoch 54/55
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14112.3672 - mae: 14112.3672
Epoch 55/55
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14063.6943 - mae: 14063.6943
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

[I 2026-10-20 12:57:27,485] Trial 6 finished with value: 0.8601610624235685 and parameters: {'epochs': 55, 'batch_size': 52, 'units_layer1': 51, 'units_layer2': 80, 'optimizer': 'adam', 'learning_rate': 0.05251011888113145}. Best is trial 5 with value: 0.9347050753213417.

Epoch 1/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 27930.3086 - mae: 27930.3086
Epoch 2/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 21980.1621 - mae: 21980.1621
Epoch 3/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 21526.6855 - mae: 21526.6855
Epoch 4/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 21325.4785 - mae: 21325.4785
Epoch 5/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20861.7773 - mae: 20861.7773
Epoch 6/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19944.5703 - mae: 19944.5703
Epoch 7/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19441.6328 - mae: 19441.6328
Epoch 8/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18953.1621 - mae: 18953.1621
Epoch 9/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18418.0254 - mae: 18418.0254
Epoch 10/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17661.5371 - mae: 17661.5371
Epoch 11/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17141.7324 - mae: 17141.7324
Epoch 12/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16827.9141 - mae: 16827.9141
Epoch 13/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16388.2363 - mae: 16388.2363
Epoch 14/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16149.5605 - mae: 16149.5605
Epoch 15/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15870.8057 - mae: 15870.8057
Epoch 16/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15529.9512 - mae: 15529.9512
Epoch 17/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 15166.0293 - mae: 15166.0293
Epoch 18/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 15024.8555 - mae: 15024.8555
Epoch 19/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14723.4561 - mae: 14723.4561
Epoch 20/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14518.4385 - mae: 14518.4385
Epoch 21/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14207.8809 - mae: 14207.8809
Epoch 22/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13986.3975 - mae: 13986.3975
Epoch 23/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13724.6777 - mae: 13724.6777
Epoch 24/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13468.7061 - mae: 13468.7061
Epoch 25/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13372.1982 - mae: 13372.1982
Epoch 26/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13163.9033 - mae: 13163.9033
Epoch 27/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13009.4287 - mae: 13009.4287
Epoch 28/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12980.1387 - mae: 12980.1387
Epoch 29/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12809.9902 - mae: 12809.9902
Epoch 30/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12551.4639 - mae: 12551.4639
Epoch 31/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12533.6025 - mae: 12533.6025
Epoch 32/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12206.4502 - mae: 12206.4502
Epoch 33/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12121.1045 - mae: 12121.1045
Epoch 34/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11974.0518 - mae: 11974.0518
Epoch 35/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11913.5840 - mae: 11913.5840
Epoch 36/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11735.3965 - mae: 11735.3965
Epoch 37/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11505.3574 - mae: 11505.3574
Epoch 38/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11423.6846 - mae: 11423.6846
Epoch 39/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11276.4209 - mae: 11276.4209
Epoch 40/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11198.3125 - mae: 11198.3125
Epoch 41/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10947.4453 - mae: 10947.4453
Epoch 42/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10965.0654 - mae: 10965.0654
Epoch 43/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10913.8975 - mae: 10913.8975
Epoch 44/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10657.9033 - mae: 10657.9033
Epoch 45/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10666.7783 - mae: 10666.7783
Epoch 46/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10523.0732 - mae: 10523.0732
Epoch 47/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10417.1904 - mae: 10417.1904
Epoch 48/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10216.6621 - mae: 10216.6621
Epoch 49/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10175.2705 - mae: 10175.2705
Epoch 50/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10118.8389 - mae: 10118.8389
Epoch 51/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10046.3213 - mae: 10046.3213
Epoch 52/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9965.5928 - mae: 9965.5928
Epoch 53/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9717.0713 - mae: 9717.0713
Epoch 54/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9660.2812 - mae: 9660.2812
Epoch 55/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9554.7832 - mae: 9554.7832
Epoch 56/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9516.9834 - mae: 9516.9834
Epoch 57/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9451.3848 - mae: 9451.3848
Epoch 58/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9431.0352 - mae: 9431.0352
Epoch 59/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9295.3320 - mae: 9295.3320
Epoch 60/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9257.8047 - mae: 9257.8047
Epoch 61/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9118.7930 - mae: 9118.7930
Epoch 62/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9072.3818 - mae: 9072.3818
Epoch 63/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9118.0801 - mae: 9118.0801
Epoch 64/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8954.1035 - mae: 8954.1035
Epoch 65/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8994.8311 - mae: 8994.8311
Epoch 66/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8912.3037 - mae: 8912.3037
Epoch 67/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8926.8447 - mae: 8926.8447
Epoch 68/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8840.7275 - mae: 8840.7275
Epoch 69/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8734.2773 - mae: 8734.2773
Epoch 70/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8772.3369 - mae: 8772.3369
Epoch 71/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8697.2334 - mae: 8697.2334
Epoch 72/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8672.2236 - mae: 8672.2236
Epoch 73/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8559.6572 - mae: 8559.6572
Epoch 74/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8626.2842 - mae: 8626.2842
Epoch 75/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8547.4277 - mae: 8547.4277
Epoch 76/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8539.3369 - mae: 8539.3369
Epoch 77/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8448.5000 - mae: 8448.5000
Epoch 78/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8411.6699 - mae: 8411.6699
Epoch 79/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8401.5938 - mae: 8401.5938
Epoch 80/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8345.9443 - mae: 8345.9443
Epoch 81/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8304.8320 - mae: 8304.8320
Epoch 82/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8227.7607 - mae: 8227.7607
Epoch 83/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8171.4922 - mae: 8171.4922
Epoch 84/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8109.7529 - mae: 8109.7529
Epoch 85/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8078.8945 - mae: 8078.8945
Epoch 86/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8076.7886 - mae: 8076.7886
Epoch 87/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8061.7842 - mae: 8061.7842
Epoch 88/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8008.7266 - mae: 8008.7266
Epoch 89/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8035.8687 - mae: 8035.8687
Epoch 90/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7977.8276 - mae: 7977.8276
Epoch 91/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7933.9702 - mae: 7933.9702
Epoch 92/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7838.6758 - mae: 7838.6758
Epoch 93/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7849.0303 - mae: 7849.0303
Epoch 94/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7783.1333 - mae: 7783.1333
Epoch 95/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7726.8711 - mae: 7726.8711
Epoch 96/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7673.2656 - mae: 7673.2656
Epoch 97/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7709.8857 - mae: 7709.8857
Epoch 98/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7610.8584 - mae: 7610.8584
Epoch 99/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7670.6504 - mae: 7670.6504
Epoch 100/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7615.4497 - mae: 7615.4497
Epoch 101/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7564.5444 - mae: 7564.5444
Epoch 102/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7595.6680 - mae: 7595.6680
Epoch 103/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7537.3857 - mae: 7537.3857
Epoch 104/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7501.3350 - mae: 7501.3350
Epoch 105/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7456.3921 - mae: 7456.3921
Epoch 106/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7473.4155 - mae: 7473.4155
Epoch 107/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7478.0693 - mae: 7478.0693
Epoch 108/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7440.8555 - mae: 7440.8555
Epoch 109/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7360.4619 - mae: 7360.4619
Epoch 110/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7404.9487 - mae: 7404.9487
Epoch 111/111
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7322.5659 - mae: 7322.5659
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

[I 2026-10-20 12:58:10,196] Trial 7 finished with value: 0.9123745836935865 and parameters: {'epochs': 111, 'batch_size': 32, 'units_layer1': 52, 'units_layer2': 120, 'optimizer': 'rmsprop', 'learning_rate': 0.11719763201449578}. Best is trial 5 with value: 0.9347050753213417.

Epoch 1/107
108/108 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 36897.2109 - mae: 36897.2109
Epoch 2/107
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 21559.9355 - mae: 21559.9355
Epoch 3/107
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20927.1992 - mae: 20927.1973
Epoch 4/107
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20608.1855 - mae: 20608.1855
Epoch 5/107
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20673.3555 - mae: 20673.3555
Epoch 6/107
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20412.9336 - mae: 20412.9336
Epoch 7/107
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20209.4473 - mae: 20209.4473
Epoch 8/107
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20260.5430 - mae: 20260.5449
Epoch 9/107
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19964.3457 - mae: 19964.3457
Epoch 10/107
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20388.1211 - mae: 20388.1211
Epoch 11/107
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20526.0410 - mae: 20526.0410
Epoch 12/107
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19997.8496 - mae: 19997.8477
Epoch 13/107
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19788.8633 - mae: 19788.8633
Epoch 14/107
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19752.4414 - mae: 19752.4414
Epoch 15/107
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 19833.6836 - mae: 19833.6836
Epoch 16/107
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 19877.7148 - mae: 19877.7148
Epoch 17/107
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19610.3242 - mae: 19610.3242
Epoch 18/107
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19442.1992 - mae: 19442.1992
Epoch 19/107
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19321.9629 - mae: 19321.9629
Epoch 20/107
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19376.2734 - mae: 19376.2734
Epoch 21/107
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19543.6484 - mae: 19543.6484
Epoch 22/107
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19107.2227 - mae: 19107.2227
Epoch 23/107
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18122.8633 - mae: 18122.8633
Epoch 24/107
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17218.6152 - mae: 17218.6152
Epoch 25/107
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 16662.2012 - mae: 16662.2012
Epoch 26/107
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15426.8818 - mae: 15426.8818
Epoch 27/107
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15041.6885 - mae: 15041.6885
Epoch 28/107
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13924.3105 - mae: 13924.3105
Epoch 29/107
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13502.1650 - mae: 13502.1650
Epoch 30/107
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13308.1123 - mae: 13308.1123
Epoch 31/107
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12923.8428 - mae: 12923.8428
Epoch 32/107
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12810.0049 - mae: 12810.0049
Epoch 33/107
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12314.8506 - mae: 12314.8506
Epoch 34/107
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12488.7021 - mae: 12488.7021
Epoch 35/107
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12593.0537 - mae: 12593.0537
Epoch 36/107
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12012.4463 - mae: 12012.4463
Epoch 37/107
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12384.0098 - mae: 12384.0098
Epoch 38/107
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12103.1709 - mae: 12103.1709
Epoch 39/107
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11767.0947 - mae: 11767.0947
Epoch 40/107
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11801.9619 - mae: 11801.9619
Epoch 41/107
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11641.3027 - mae: 11641.3027
Epoch 42/107
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11598.5400 - mae: 11598.5400
Epoch 43/107
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11018.6855 - mae: 11018.6855
Epoch 44/107
108/108 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 11193.6182 - mae: 11193.6182
Epoch 45/107
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11101.6729 - mae: 11101.6729
Epoch 46/107
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10634.7783 - mae: 10634.7783
Epoch 47/107
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10359.4639 - mae: 10359.4658
Epoch 48/107
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10449.0449 - mae: 10449.0449
Epoch 49/107
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10524.7920 - mae: 10524.7920
Epoch 50/107
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10522.7295 - mae: 10522.7295
Epoch 51/107
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10003.1553 - mae: 10003.1553
Epoch 52/107
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10183.3896 - mae: 10183.3896
Epoch 53/107
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9957.6182 - mae: 9957.6182
Epoch 54/107
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9888.6084 - mae: 9888.6084
Epoch 55/107
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10054.3154 - mae: 10054.3154
Epoch 56/107
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9455.0693 - mae: 9455.0693
Epoch 57/107
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9553.9512 - mae: 9553.9512
Epoch 58/107
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9478.4893 - mae: 9478.4893
Epoch 59/107
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10206.0518 - mae: 10206.0518
Epoch 60/107
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9255.0146 - mae: 9255.0146
Epoch 61/107
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8072.9526 - mae: 8072.9526
Epoch 184/200
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8107.6187 - mae: 8107.6187
Epoch 185/200
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8139.1260 - mae: 8139.1260
Epoch 186/200
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8071.7300 - mae: 8071.7300
Epoch 187/200
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8036.4175 - mae: 8036.4175
Epoch 188/200
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8115.4463 - mae: 8115.4463
Epoch 189/200
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8066.8599 - mae: 8066.8599
Epoch 190/200
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7911.0625 - mae: 7911.0625
Epoch 191/200
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8269.1338 - mae: 8269.1338
Epoch 192/200
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7975.3638 - mae: 7975.3638
Epoch 193/200
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7883.1855 - mae: 7883.1855
Epoch 194/200
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7916.4858 - mae: 7916.4858
Epoch 195/200
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7868.3462 - mae: 7868.3462
Epoch 196/200
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7893.1909 - mae: 7893.1909
Epoch 197/200
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7895.9043 - mae: 7895.9043
Epoch 198/200
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8018.9531 - mae: 8018.9531
Epoch 199/200
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7774.1294 - mae: 7774.1294
Epoch 200/200
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7823.1699 - mae: 7823.1699
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

[I 2026-10-20 12:59:51,250] Trial 9 finished with value: 0.9218342550043931 and parameters: {'epochs': 200, 'batch_size': 33, 'units_layer1': 108, 'units_layer2': 108, 'optimizer': 'adam', 'learning_rate': 0.029272894672525696}. Best is trial 5 with value: 0.9347050753213417.

Epoch 1/50
335/335 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 29711.1797 - mae: 29711.1797
Epoch 2/50
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 22717.7793 - mae: 22717.7793
Epoch 3/50
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 19746.8984 - mae: 19746.8984
Epoch 4/50
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 18234.0762 - mae: 18234.0762
Epoch 5/50
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 16627.1152 - mae: 16627.1152
Epoch 6/50
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 15873.8008 - mae: 15873.8008
Epoch 7/50
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 15345.9922 - mae: 15345.9922
Epoch 8/50
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 15150.3184 - mae: 15150.3184
Epoch 9/50
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 15330.5488 - mae: 15330.5488
Epoch 10/50
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 14275.6445 - mae: 14275.6445
Epoch 11/50
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 14380.8828 - mae: 14380.8828
Epoch 12/50
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 14257.4150 - mae: 14257.4150
Epoch 13/50
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 14000.8242 - mae: 14000.8242
Epoch 14/50
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 14089.6494 - mae: 14089.6494
Epoch 15/50
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 13743.3252 - mae: 13743.3252
Epoch 16/50
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 13578.8486 - mae: 13578.8486
Epoch 17/50
335/335 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 13669.7539 - mae: 13669.7539
Epoch 18/50
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 13697.3867 - mae: 13697.3867
Epoch 19/50
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 13192.0420 - mae: 13192.0420
Epoch 20/50
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 13287.2637 - mae: 13287.2637
Epoch 21/50
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12687.4727 - mae: 12687.4727
Epoch 22/50
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 13212.2803 - mae: 13212.2803
Epoch 23/50
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12987.4941 - mae: 12987.4941
Epoch 24/50
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12782.1729 - mae: 12782.1729
Epoch 25/50
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12642.2842 - mae: 12642.2842
Epoch 26/50
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12378.5117 - mae: 12378.5117
Epoch 27/50
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12461.0605 - mae: 12461.0605
Epoch 28/50
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12451.7842 - mae: 12451.7842
Epoch 29/50
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12236.3467 - mae: 12236.3467
Epoch 30/50
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12473.1758 - mae: 12473.1758
Epoch 31/50
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12289.5928 - mae: 12289.5928
Epoch 32/50
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 11786.4102 - mae: 11786.4102
Epoch 33/50
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12205.5059 - mae: 12205.5059
Epoch 34/50
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 11898.4082 - mae: 11898.4082
Epoch 35/50
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12257.4854 - mae: 12257.4854
Epoch 36/50
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12608.5449 - mae: 12608.5449
Epoch 37/50
335/335 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 12477.3672 - mae: 12477.3672
Epoch 38/50
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12351.3516 - mae: 12351.3516
Epoch 39/50
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12302.7773 - mae: 12302.7773
Epoch 40/50
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 11897.8594 - mae: 11897.8594
Epoch 41/50
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 11964.8848 - mae: 11964.8848
Epoch 42/50
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12140.9277 - mae: 12140.9277
Epoch 43/50
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12087.0508 - mae: 12087.0508
Epoch 44/50
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 11632.4170 - mae: 11632.4170
Epoch 45/50
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12349.3955 - mae: 12349.3955
Epoch 46/50
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12005.7803 - mae: 12005.7803
Epoch 47/50
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 11955.9336 - mae: 11955.9336
Epoch 48/50
335/335 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 11985.7422 - mae: 11985.7422
Epoch 49/50
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 12085.4658 - mae: 12085.4658
Epoch 50/50
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 11663.6572 - mae: 11663.6572
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

[I 2026-10-20 13:00:24,906] Trial 10 finished with value: 0.8669798345624468 and parameters: {'epochs': 50, 'batch_size': 16, 'units_layer1': 78, 'units_layer2': 87, 'optimizer': 'adam', 'learning_rate': 0.9515333294945074}. Best is trial 5 with value: 0.9347050753213417.

Epoch 1/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 27435.6074 - mae: 27435.6074
Epoch 2/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 21450.8301 - mae: 21450.8301
Epoch 3/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 21362.7129 - mae: 21362.7129
Epoch 4/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19151.4844 - mae: 19151.4824
Epoch 5/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18077.2871 - mae: 18077.2871
Epoch 6/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16971.4062 - mae: 16971.4062
Epoch 7/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 16546.2285 - mae: 16546.2285
Epoch 8/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15235.1445 - mae: 15235.1445
Epoch 9/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 14703.6611 - mae: 14703.6611
Epoch 10/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14737.6787 - mae: 14737.6816
Epoch 11/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 14355.0342 - mae: 14355.0342
Epoch 12/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14039.4756 - mae: 14039.4756
Epoch 13/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14049.5752 - mae: 14049.5752
Epoch 14/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13113.6406 - mae: 13113.6406
Epoch 15/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13118.8164 - mae: 13118.8164
Epoch 16/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12786.1953 - mae: 12786.1953
Epoch 17/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13023.7988 - mae: 13023.7988
Epoch 18/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12700.9053 - mae: 12700.9053
Epoch 19/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12139.9717 - mae: 12139.9717
Epoch 20/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12669.5977 - mae: 12669.5977
Epoch 21/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11913.0547 - mae: 11913.0547
Epoch 22/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11382.1299 - mae: 11382.1299
Epoch 23/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11452.9268 - mae: 11452.9268
Epoch 24/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11103.9414 - mae: 11103.9414
Epoch 25/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10503.8340 - mae: 10503.8340
Epoch 26/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11194.6826 - mae: 11194.6826
Epoch 27/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11164.9375 - mae: 11164.9385
Epoch 28/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10921.4707 - mae: 10921.4707
Epoch 29/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10708.8418 - mae: 10708.8418
Epoch 30/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10344.0400 - mae: 10344.0400
Epoch 31/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10545.8594 - mae: 10545.8594
Epoch 32/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 10353.5537 - mae: 10353.5537
Epoch 33/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10742.4932 - mae: 10742.4932
Epoch 34/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10091.6465 - mae: 10091.6465
Epoch 35/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10074.5176 - mae: 10074.5186
Epoch 36/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9860.2959 - mae: 9860.2959
Epoch 37/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10001.7812 - mae: 10001.7812
Epoch 38/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 10479.2539 - mae: 10479.2539
Epoch 39/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9942.6865 - mae: 9942.6865
Epoch 40/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9517.4473 - mae: 9517.4473
Epoch 41/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9615.1045 - mae: 9615.1045
Epoch 42/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 9911.5850 - mae: 9911.5850
Epoch 43/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9904.7500 - mae: 9904.7500
Epoch 44/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10276.2861 - mae: 10276.2861
Epoch 45/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9784.9863 - mae: 9784.9873
Epoch 46/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9512.7119 - mae: 9512.7119
Epoch 47/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9523.7539 - mae: 9523.7539
Epoch 48/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10069.2031 - mae: 10069.2051
Epoch 49/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9401.2979 - mae: 9401.2979
Epoch 50/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 9829.0889 - mae: 9829.0889
Epoch 51/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 9161.4600 - mae: 9161.4600
Epoch 52/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9083.5752 - mae: 9083.5752
Epoch 53/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 9405.1729 - mae: 9405.1729
Epoch 54/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9766.0488 - mae: 9766.0488
Epoch 55/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9525.5068 - mae: 9525.5068
Epoch 56/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9210.7500 - mae: 9210.7500
Epoch 57/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 9724.8760 - mae: 9724.8760
Epoch 58/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 9432.0420 - mae: 9432.0420
Epoch 59/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9063.7178 - mae: 9063.7178
Epoch 60/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9129.7695 - mae: 9129.7695
Epoch 61/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9220.3818 - mae: 9220.3818
Epoch 62/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8882.9648 - mae: 8882.9648
Epoch 63/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9320.2158 - mae: 9320.2158
Epoch 64/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9297.1396 - mae: 9297.1396
Epoch 65/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9360.5312 - mae: 9360.5312
Epoch 66/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8971.6055 - mae: 8971.6055
Epoch 67/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8911.2695 - mae: 8911.2695
Epoch 68/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8819.2246 - mae: 8819.2246
Epoch 69/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 9315.0684 - mae: 9315.0684
Epoch 70/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9070.8701 - mae: 9070.8701
Epoch 71/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8929.4111 - mae: 8929.4111
Epoch 72/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9295.6182 - mae: 9295.6182
Epoch 73/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8967.5195 - mae: 8967.5195
Epoch 74/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8610.1641 - mae: 8610.1641
Epoch 75/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 9015.1543 - mae: 9015.1543
Epoch 76/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8846.4961 - mae: 8846.4961
Epoch 77/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8792.4639 - mae: 8792.4629
Epoch 78/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8975.4072 - mae: 8975.4072
Epoch 79/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8881.2988 - mae: 8881.2988
Epoch 80/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8661.1104 - mae: 8661.1104
Epoch 81/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8961.5605 - mae: 8961.5605
Epoch 82/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9319.0000 - mae: 9319.0000
Epoch 83/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8814.8564 - mae: 8814.8564
Epoch 84/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8653.1836 - mae: 8653.1836
Epoch 85/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8575.1113 - mae: 8575.1113
Epoch 86/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8883.0498 - mae: 8883.0498
Epoch 87/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8930.9307 - mae: 8930.9307
Epoch 88/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8326.6719 - mae: 8326.6719
Epoch 89/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8730.2832 - mae: 8730.2832
Epoch 90/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8200.6543 - mae: 8200.6543
Epoch 91/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8751.0703 - mae: 8751.0693
Epoch 92/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8659.0664 - mae: 8659.0664
Epoch 93/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8436.9609 - mae: 8436.9609
Epoch 94/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8805.7637 - mae: 8805.7637
Epoch 95/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8968.5430 - mae: 8968.5430
Epoch 96/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8411.5557 - mae: 8411.5557
Epoch 97/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8740.0098 - mae: 8740.0098
Epoch 98/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9036.0938 - mae: 9036.0938
Epoch 99/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8419.0156 - mae: 8419.0156
Epoch 100/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8821.5879 - mae: 8821.5869
Epoch 101/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8449.6143 - mae: 8449.6143
Epoch 102/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9177.4941 - mae: 9177.4941
Epoch 103/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8776.7402 - mae: 8776.7402
Epoch 104/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8693.6406 - mae: 8693.6406
Epoch 105/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8406.6240 - mae: 8406.6240
Epoch 106/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8582.7568 - mae: 8582.7568
Epoch 107/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8154.6299 - mae: 8154.6299
Epoch 108/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8273.5713 - mae: 8273.5713
Epoch 109/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8147.5640 - mae: 8147.5640
Epoch 110/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8425.3213 - mae: 8425.3213
Epoch 111/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8368.8838 - mae: 8368.8838
Epoch 112/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8431.6465 - mae: 8431.6465
Epoch 113/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8793.6621 - mae: 8793.6621
Epoch 114/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8967.1816 - mae: 8967.1816
Epoch 115/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8294.2041 - mae: 8294.2041
Epoch 116/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8424.7500 - mae: 8424.7500
Epoch 117/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8458.5938 - mae: 8458.5938
Epoch 118/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8686.5664 - mae: 8686.5654
Epoch 119/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8575.2217 - mae: 8575.2217
Epoch 120/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8579.2744 - mae: 8579.2744
Epoch 121/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8157.0400 - mae: 8157.0400
Epoch 122/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8542.5586 - mae: 8542.5586
Epoch 123/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8281.8213 - mae: 8281.8213
Epoch 124/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8304.0557 - mae: 8304.0557
Epoch 125/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8023.2749 - mae: 8023.2759
Epoch 126/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8403.2139 - mae: 8403.2139
Epoch 127/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8266.2178 - mae: 8266.2178
Epoch 128/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8105.8403 - mae: 8105.8403
Epoch 129/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8205.9346 - mae: 8205.9346
Epoch 130/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8474.5742 - mae: 8474.5742
Epoch 131/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8225.7246 - mae: 8225.7246
Epoch 132/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8707.4893 - mae: 8707.4883
Epoch 133/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8945.0840 - mae: 8945.0840
Epoch 134/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8068.9976 - mae: 8068.9976
Epoch 135/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8539.2275 - mae: 8539.2275
Epoch 136/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8206.3662 - mae: 8206.3662
Epoch 137/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8106.4980 - mae: 8106.4980
Epoch 138/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8320.9336 - mae: 8320.9336
Epoch 139/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8973.6064 - mae: 8973.6064
Epoch 140/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8323.9287 - mae: 8323.9287
Epoch 141/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8284.5791 - mae: 8284.5791
Epoch 142/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7977.4751 - mae: 7977.4751
Epoch 143/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8119.1929 - mae: 8119.1929
Epoch 144/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8266.3975 - mae: 8266.3975
Epoch 145/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8448.2373 - mae: 8448.2373
Epoch 146/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8238.8652 - mae: 8238.8652
Epoch 147/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8158.7847 - mae: 8158.7847
Epoch 148/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8249.4434 - mae: 8249.4434
Epoch 149/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7983.6333 - mae: 7983.6333
Epoch 150/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8255.6152 - mae: 8255.6152
Epoch 151/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8568.0098 - mae: 8568.0098
Epoch 152/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8811.3613 - mae: 8811.3613
Epoch 153/153
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8376.3809 - mae: 8376.3809
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

[I 2026-10-20 13:01:25,892] Trial 11 finished with value: 0.9191594518431287 and parameters: {'epochs': 153, 'batch_size': 27, 'units_layer1': 127, 'units_layer2': 69, 'optimizer': 'adam', 'learning_rate': 0.6079897044395998}. Best is trial 5 with value: 0.9347050753213417.

Epoch 1/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 27573.8379 - mae: 27573.8379
Epoch 2/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 22065.4512 - mae: 22065.4492
Epoch 3/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 21564.6074 - mae: 21564.6074
Epoch 4/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20695.7148 - mae: 20695.7148
Epoch 5/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 19788.5977 - mae: 19788.5957
Epoch 6/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19265.1309 - mae: 19265.1309
Epoch 7/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18609.5840 - mae: 18609.5840
Epoch 8/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17588.1582 - mae: 17588.1562
Epoch 9/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16234.0918 - mae: 16234.0918
Epoch 10/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15957.7725 - mae: 15957.7725
Epoch 11/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 14862.0322 - mae: 14862.0322
Epoch 12/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 14501.9199 - mae: 14501.9199
Epoch 13/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 13755.1367 - mae: 13755.1367
Epoch 14/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 13782.9922 - mae: 13782.9922
Epoch 15/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13294.7695 - mae: 13294.7695
Epoch 16/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 12946.8877 - mae: 12946.8877
Epoch 17/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12695.2178 - mae: 12695.2178
Epoch 18/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12219.3818 - mae: 12219.3818
Epoch 19/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 12046.7461 - mae: 12046.7461
Epoch 20/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12202.1982 - mae: 12202.1982
Epoch 21/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 11496.2402 - mae: 11496.2412
Epoch 22/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12325.3076 - mae: 12325.3076
Epoch 23/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11392.2109 - mae: 11392.2109
Epoch 24/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11296.5029 - mae: 11296.5029
Epoch 25/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 10924.8281 - mae: 10924.8281
Epoch 26/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 10704.8281 - mae: 10704.8281
Epoch 27/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10267.0312 - mae: 10267.0312
Epoch 28/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 10316.0859 - mae: 10316.0869
Epoch 29/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10136.5654 - mae: 10136.5654
Epoch 30/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 10082.6143 - mae: 10082.6143
Epoch 31/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9834.9111 - mae: 9834.9111
Epoch 32/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 10235.0098 - mae: 10235.0098
Epoch 33/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9995.2725 - mae: 9995.2725
Epoch 34/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9688.0898 - mae: 9688.0898
Epoch 35/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9750.1709 - mae: 9750.1709
Epoch 36/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9544.0010 - mae: 9544.0010
Epoch 37/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9777.8408 - mae: 9777.8408
Epoch 38/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9576.1152 - mae: 9576.1152
Epoch 39/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9451.3945 - mae: 9451.3945
Epoch 40/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9584.0762 - mae: 9584.0762
Epoch 41/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9323.2559 - mae: 9323.2559
Epoch 42/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9402.1543 - mae: 9402.1543
Epoch 43/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9931.5791 - mae: 9931.5791
Epoch 44/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9515.2793 - mae: 9515.2793
Epoch 45/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9291.8359 - mae: 9291.8359
Epoch 46/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 9652.6797 - mae: 9652.6797
Epoch 47/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9091.7041 - mae: 9091.7041
Epoch 48/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9080.9414 - mae: 9080.9414
Epoch 49/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8933.0264 - mae: 8933.0264
Epoch 50/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9212.5254 - mae: 9212.5254
Epoch 51/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9093.3984 - mae: 9093.3984
Epoch 52/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9071.5117 - mae: 9071.5117
Epoch 53/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8764.4482 - mae: 8764.4482
Epoch 54/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9163.7090 - mae: 9163.7090
Epoch 55/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9004.4424 - mae: 9004.4424
Epoch 56/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8814.6572 - mae: 8814.6572
Epoch 57/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8791.4746 - mae: 8791.4746
Epoch 58/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8632.0146 - mae: 8632.0146
Epoch 59/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8595.5430 - mae: 8595.5430
Epoch 60/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8821.9795 - mae: 8821.9795
Epoch 61/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8805.5303 - mae: 8805.5303
Epoch 62/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8660.4521 - mae: 8660.4521
Epoch 63/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8819.8906 - mae: 8819.8906
Epoch 64/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8329.7812 - mae: 8329.7812
Epoch 65/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8582.1221 - mae: 8582.1221
Epoch 66/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8447.4248 - mae: 8447.4248
Epoch 67/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8637.8945 - mae: 8637.8945
Epoch 68/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8884.2969 - mae: 8884.2969
Epoch 69/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8968.1602 - mae: 8968.1602
Epoch 70/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8482.5879 - mae: 8482.5879
Epoch 71/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8349.6182 - mae: 8349.6182
Epoch 72/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8383.1865 - mae: 8383.1875
Epoch 73/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8405.2021 - mae: 8405.2021
Epoch 74/74
244/244 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8190.5015 - mae: 8190.5015
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

[I 2026-10-20 13:02:03,072] Trial 12 finished with value: 0.9217318399367053 and parameters: {'epochs': 74, 'batch_size': 22, 'units_layer1': 86, 'units_layer2': 51, 'optimizer': 'adam', 'learning_rate': 0.3790849330391487}. Best is trial 5 with value: 0.9347050753213417.

Epoch 1/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 29964.4551 - mae: 29964.4590
Epoch 2/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 21484.6152 - mae: 21484.6172
Epoch 3/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 20870.9785 - mae: 20870.9785
Epoch 4/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20869.7070 - mae: 20869.7070
Epoch 5/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20653.7422 - mae: 20653.7461
Epoch 6/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20703.1777 - mae: 20703.1777
Epoch 7/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19623.0156 - mae: 19623.0156
Epoch 8/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20270.6953 - mae: 20270.6914
Epoch 9/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17852.9355 - mae: 17852.9355
Epoch 10/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17531.1641 - mae: 17531.1641
Epoch 11/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16141.8340 - mae: 16141.8340
Epoch 12/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15253.2139 - mae: 15253.2139
Epoch 13/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14133.1826 - mae: 14133.1826
Epoch 14/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14061.2725 - mae: 14061.2725
Epoch 15/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13748.4932 - mae: 13748.4932
Epoch 16/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13060.1299 - mae: 13060.1299
Epoch 17/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13101.8975 - mae: 13101.8975
Epoch 18/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12368.8291 - mae: 12368.8291
Epoch 19/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12470.9229 - mae: 12470.9229
Epoch 20/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 12774.9053 - mae: 12774.9053
Epoch 21/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12433.9375 - mae: 12433.9375
Epoch 22/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12432.1084 - mae: 12432.1084
Epoch 23/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 12006.4365 - mae: 12006.4365
Epoch 24/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 12182.2559 - mae: 12182.2559
Epoch 25/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11975.0215 - mae: 11975.0215
Epoch 26/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11825.6875 - mae: 11825.6875
Epoch 27/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11573.0996 - mae: 11573.0996
Epoch 28/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12260.8730 - mae: 12260.8721
Epoch 29/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11612.4707 - mae: 11612.4707
Epoch 30/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11464.6387 - mae: 11464.6387
Epoch 31/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11509.6885 - mae: 11509.6885
Epoch 32/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11595.6221 - mae: 11595.6211
Epoch 33/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11277.6104 - mae: 11277.6104
Epoch 34/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11430.1133 - mae: 11430.1133
Epoch 35/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10829.1807 - mae: 10829.1807
Epoch 36/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10404.5732 - mae: 10404.5732
Epoch 37/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10798.9092 - mae: 10798.9092
Epoch 38/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11221.6328 - mae: 11221.6328
Epoch 39/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10329.5938 - mae: 10329.5938
Epoch 40/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10520.9297 - mae: 10520.9297
Epoch 41/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10080.7334 - mae: 10080.7334
Epoch 42/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9856.6807 - mae: 9856.6807
Epoch 43/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9977.1406 - mae: 9977.1406
Epoch 44/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10220.8037 - mae: 10220.8037
Epoch 45/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9760.1191 - mae: 9760.1191
Epoch 46/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9231.7783 - mae: 9231.7783
Epoch 47/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9620.3008 - mae: 9620.3008
Epoch 48/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9711.0234 - mae: 9711.0234
Epoch 49/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9634.9678 - mae: 9634.9678
Epoch 50/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9594.4033 - mae: 9594.4033
Epoch 51/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9201.5195 - mae: 9201.5195
Epoch 52/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9063.7832 - mae: 9063.7832
Epoch 53/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9236.6055 - mae: 9236.6055
Epoch 54/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9168.9121 - mae: 9168.9121
Epoch 55/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9114.3594 - mae: 9114.3594
Epoch 56/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9260.5781 - mae: 9260.5781
Epoch 57/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9054.7246 - mae: 9054.7246
Epoch 58/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9051.4170 - mae: 9051.4170
Epoch 59/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8846.2012 - mae: 8846.2012
Epoch 60/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9034.2998 - mae: 9034.2998
Epoch 61/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8766.4424 - mae: 8766.4424
Epoch 62/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8785.2314 - mae: 8785.2314
Epoch 63/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9139.5938 - mae: 9139.5938
Epoch 64/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8904.1465 - mae: 8904.1465
Epoch 65/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9126.9717 - mae: 9126.9717
Epoch 66/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8950.2754 - mae: 8950.2744
Epoch 67/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8607.8906 - mae: 8607.8906
Epoch 68/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8467.5225 - mae: 8467.5225
Epoch 69/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8477.3994 - mae: 8477.3994
Epoch 70/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8362.4004 - mae: 8362.4004
Epoch 71/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8363.7080 - mae: 8363.7080
Epoch 72/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8066.5234 - mae: 8066.5234
Epoch 73/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8611.7246 - mae: 8611.7246
Epoch 74/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8188.5449 - mae: 8188.5449
Epoch 75/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8094.2114 - mae: 8094.2114
Epoch 76/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8524.7432 - mae: 8524.7432
Epoch 77/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8087.5132 - mae: 8087.5132
Epoch 78/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8542.3213 - mae: 8542.3213
Epoch 79/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8795.6279 - mae: 8795.6279
Epoch 80/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8122.8726 - mae: 8122.8726
Epoch 81/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8078.5757 - mae: 8078.5757
Epoch 82/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7988.6636 - mae: 7988.6636
Epoch 83/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8181.5205 - mae: 8181.5205
Epoch 84/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7966.9810 - mae: 7966.9819
Epoch 85/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7819.5366 - mae: 7819.5366
Epoch 86/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7911.5283 - mae: 7911.5283
Epoch 87/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7878.1709 - mae: 7878.1709
Epoch 88/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7784.8472 - mae: 7784.8472
Epoch 89/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7804.9438 - mae: 7804.9438
Epoch 90/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7602.7017 - mae: 7602.7017
Epoch 91/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7658.7158 - mae: 7658.7158
Epoch 92/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7996.2622 - mae: 7996.2622
Epoch 93/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7762.6846 - mae: 7762.6831
Epoch 94/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7501.3296 - mae: 7501.3296
Epoch 95/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7585.9819 - mae: 7585.9819
Epoch 96/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7570.2612 - mae: 7570.2612
Epoch 97/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7757.4478 - mae: 7757.4478
Epoch 98/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7493.7280 - mae: 7493.7280
Epoch 99/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7733.4429 - mae: 7733.4429
Epoch 100/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7491.9463 - mae: 7491.9463
Epoch 101/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7395.3320 - mae: 7395.3320
Epoch 102/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7522.7266 - mae: 7522.7266
Epoch 103/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7356.0605 - mae: 7356.0605
Epoch 104/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7477.2510 - mae: 7477.2510
Epoch 105/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7343.5342 - mae: 7343.5342
Epoch 106/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7358.9780 - mae: 7358.9780
Epoch 107/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7586.9810 - mae: 7586.9810
Epoch 108/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7560.7808 - mae: 7560.7808
Epoch 109/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7092.1006 - mae: 7092.1006
Epoch 110/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7331.5103 - mae: 7331.5103
Epoch 111/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7256.6436 - mae: 7256.6436
Epoch 112/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7291.2505 - mae: 7291.2505
Epoch 113/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7081.7012 - mae: 7081.7012
Epoch 114/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7426.6099 - mae: 7426.6099
Epoch 115/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7472.0679 - mae: 7472.0679
Epoch 116/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7207.0630 - mae: 7207.0630
Epoch 117/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6981.5044 - mae: 6981.5044
Epoch 118/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7395.7378 - mae: 7395.7378
Epoch 119/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7295.6147 - mae: 7295.6147
Epoch 120/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7037.6221 - mae: 7037.6221
Epoch 121/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7122.8384 - mae: 7122.8384
Epoch 122/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7178.7681 - mae: 7178.7681
Epoch 123/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7072.1943 - mae: 7072.1943
Epoch 124/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7030.5576 - mae: 7030.5576
Epoch 125/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7247.7529 - mae: 7247.7529
Epoch 126/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7062.5049 - mae: 7062.5049
Epoch 127/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6915.7759 - mae: 6915.7759
Epoch 128/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7333.7012 - mae: 7333.7012
Epoch 129/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6964.0732 - mae: 6964.0737
Epoch 130/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7095.0420 - mae: 7095.0420
Epoch 131/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7053.4746 - mae: 7053.4746
Epoch 132/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6889.2817 - mae: 6889.2817
Epoch 133/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7192.2681 - mae: 7192.2681
Epoch 134/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7165.2227 - mae: 7165.2236
Epoch 135/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6796.7935 - mae: 6796.7935
Epoch 136/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7105.7583 - mae: 7105.7583
Epoch 137/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7031.6777 - mae: 7031.6777
Epoch 138/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6842.1768 - mae: 6842.1768
Epoch 139/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7081.2275 - mae: 7081.2275
Epoch 140/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7223.8662 - mae: 7223.8662
Epoch 141/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6770.6460 - mae: 6770.6460
Epoch 142/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7150.5635 - mae: 7150.5635
Epoch 143/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6627.8755 - mae: 6627.8755
Epoch 144/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7623.3647 - mae: 7623.3647
Epoch 145/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7360.4951 - mae: 7360.4956
Epoch 146/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6690.1768 - mae: 6690.1768
Epoch 147/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6963.6743 - mae: 6963.6743
Epoch 148/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7035.4497 - mae: 7035.4497
Epoch 149/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7006.5190 - mae: 7006.5190
Epoch 150/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7020.4194 - mae: 7020.4194
Epoch 151/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6918.1484 - mae: 6918.1484
Epoch 152/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6788.8071 - mae: 6788.8071
Epoch 153/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6761.4722 - mae: 6761.4722
Epoch 154/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7013.3843 - mae: 7013.3843
Epoch 155/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6866.7061 - mae: 6866.7061
Epoch 156/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7038.3413 - mae: 7038.3413
Epoch 157/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6763.6924 - mae: 6763.6924
Epoch 158/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6841.7021 - mae: 6841.7021
Epoch 159/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6983.2817 - mae: 6983.2817
Epoch 160/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7081.8364 - mae: 7081.8364
Epoch 161/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7189.4019 - mae: 7189.4019
Epoch 162/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6968.8550 - mae: 6968.8550
Epoch 163/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6869.5059 - mae: 6869.5059
Epoch 164/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7338.1909 - mae: 7338.1909
Epoch 165/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6505.6616 - mae: 6505.6616
Epoch 166/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6549.0542 - mae: 6549.0542
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

[I 2026-10-20 13:02:56,541] Trial 13 finished with value: 0.9435962770533816 and parameters: {'epochs': 166, 'batch_size': 39, 'units_layer1': 87, 'units_layer2': 78, 'optimizer': 'adam', 'learning_rate': 0.3085186122202393}. Best is trial 13 with value: 0.9435962770533816.

Epoch 1/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 36540.5312 - mae: 36540.5312
Epoch 2/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 21115.4648 - mae: 21115.4648
Epoch 3/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20712.4473 - mae: 20712.4473
Epoch 4/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20724.3359 - mae: 20724.3359
Epoch 5/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20407.4199 - mae: 20407.4199
Epoch 6/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19994.2070 - mae: 19994.2070
Epoch 7/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19787.3418 - mae: 19787.3418
Epoch 8/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19514.4336 - mae: 19514.4355
Epoch 9/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19645.9453 - mae: 19645.9453
Epoch 10/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19461.5312 - mae: 19461.5312
Epoch 11/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19506.8691 - mae: 19506.8691
Epoch 12/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19518.0449 - mae: 19518.0449
Epoch 13/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 19356.4629 - mae: 19356.4629
Epoch 14/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19330.2793 - mae: 19330.2793
Epoch 15/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19347.0859 - mae: 19347.0859
Epoch 16/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19298.7168 - mae: 19298.7168
Epoch 17/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18682.4102 - mae: 18682.4102
Epoch 18/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17737.5410 - mae: 17737.5410
Epoch 19/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17460.0586 - mae: 17460.0586
Epoch 20/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17108.5820 - mae: 17108.5820
Epoch 21/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16475.0410 - mae: 16475.0410
Epoch 22/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16105.2979 - mae: 16105.2979
Epoch 23/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15622.9580 - mae: 15622.9580
Epoch 24/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15230.0439 - mae: 15230.0439
Epoch 25/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14710.5293 - mae: 14710.5312
Epoch 26/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14138.9307 - mae: 14138.9307
Epoch 27/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14172.6670 - mae: 14172.6670
Epoch 28/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14145.1426 - mae: 14145.1426
Epoch 29/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13984.0840 - mae: 13984.0840
Epoch 30/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13371.9033 - mae: 13371.9033
Epoch 31/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13046.4736 - mae: 13046.4736
Epoch 32/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12931.8389 - mae: 12931.8389
Epoch 33/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12711.6777 - mae: 12711.6777
Epoch 34/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12144.5420 - mae: 12144.5420
Epoch 35/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12391.2041 - mae: 12391.2041
Epoch 36/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12081.4551 - mae: 12081.4551
Epoch 37/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11595.7324 - mae: 11595.7324
Epoch 38/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11911.1084 - mae: 11911.1084
Epoch 39/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11542.7529 - mae: 11542.7529
Epoch 40/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11029.3447 - mae: 11029.3447
Epoch 41/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11365.6982 - mae: 11365.6982
Epoch 42/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10881.4238 - mae: 10881.4238
Epoch 43/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10852.7373 - mae: 10852.7373
Epoch 44/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10614.9365 - mae: 10614.9365
Epoch 45/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10766.4727 - mae: 10766.4727
Epoch 46/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10706.8584 - mae: 10706.8584
Epoch 47/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10775.6270 - mae: 10775.6270
Epoch 48/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10316.2715 - mae: 10316.2715
Epoch 49/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10311.0410 - mae: 10311.0410
Epoch 50/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10240.5000 - mae: 10240.5000
Epoch 51/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10279.4316 - mae: 10279.4316
Epoch 52/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10037.6865 - mae: 10037.6865
Epoch 53/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10123.0479 - mae: 10123.0469
Epoch 54/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10028.4805 - mae: 10028.4805
Epoch 55/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9750.6123 - mae: 9750.6133
Epoch 56/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9929.4961 - mae: 9929.4971
Epoch 57/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9732.4043 - mae: 9732.4043
Epoch 58/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9607.2734 - mae: 9607.2754
Epoch 59/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9751.5586 - mae: 9751.5586
Epoch 60/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9658.6201 - mae: 9658.6201
Epoch 61/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9786.2705 - mae: 9786.2705
Epoch 62/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9328.4326 - mae: 9328.4326
Epoch 63/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9295.7070 - mae: 9295.7070
Epoch 64/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9457.1201 - mae: 9457.1201
Epoch 65/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9059.8535 - mae: 9059.8535
Epoch 66/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9261.3262 - mae: 9261.3262
Epoch 67/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9145.4326 - mae: 9145.4326
Epoch 68/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9035.4482 - mae: 9035.4482
Epoch 69/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8849.2666 - mae: 8849.2666
Epoch 70/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8973.7061 - mae: 8973.7061
Epoch 71/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9209.8770 - mae: 9209.8770
Epoch 72/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8620.9648 - mae: 8620.9648
Epoch 73/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8953.3555 - mae: 8953.3555
Epoch 74/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8954.4678 - mae: 8954.4678
Epoch 75/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8683.2451 - mae: 8683.2451
Epoch 76/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8769.1797 - mae: 8769.1797
Epoch 77/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8673.6025 - mae: 8673.6025
Epoch 78/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8591.8086 - mae: 8591.8086
Epoch 79/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8829.5166 - mae: 8829.5166
Epoch 80/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8586.2451 - mae: 8586.2451
Epoch 81/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8574.5400 - mae: 8574.5400
Epoch 82/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8589.0508 - mae: 8589.0518
Epoch 83/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8418.2139 - mae: 8418.2139
Epoch 84/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8758.0273 - mae: 8758.0273
Epoch 85/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8329.6309 - mae: 8329.6309
Epoch 86/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8451.4512 - mae: 8451.4512
Epoch 87/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8391.6152 - mae: 8391.6152
Epoch 88/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8378.4014 - mae: 8378.4014
Epoch 89/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8481.7168 - mae: 8481.7168
Epoch 90/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8325.9600 - mae: 8325.9600
Epoch 91/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8321.9893 - mae: 8321.9893
Epoch 92/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8216.2793 - mae: 8216.2783
Epoch 93/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8149.7275 - mae: 8149.7275
Epoch 94/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8384.6152 - mae: 8384.6152
Epoch 95/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8232.9336 - mae: 8232.9336
Epoch 96/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8090.5889 - mae: 8090.5889
Epoch 97/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8125.5103 - mae: 8125.5093
Epoch 98/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8147.5244 - mae: 8147.5244
Epoch 99/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8076.4077 - mae: 8076.4077
Epoch 100/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8025.1846 - mae: 8025.1846
Epoch 101/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8046.5220 - mae: 8046.5220
Epoch 102/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7727.6064 - mae: 7727.6064
Epoch 103/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7782.8628 - mae: 7782.8638
Epoch 104/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8001.7568 - mae: 8001.7568
Epoch 105/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7929.1050 - mae: 7929.1050
Epoch 106/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7674.0933 - mae: 7674.0942
Epoch 107/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7702.9668 - mae: 7702.9668
Epoch 108/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7519.7373 - mae: 7519.7363
Epoch 109/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7368.1924 - mae: 7368.1924
Epoch 110/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7563.1729 - mae: 7563.1729
Epoch 111/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7457.7754 - mae: 7457.7754
Epoch 112/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7419.7632 - mae: 7419.7632
Epoch 113/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7562.5508 - mae: 7562.5522
Epoch 114/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7506.3081 - mae: 7506.3081
Epoch 115/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7327.5469 - mae: 7327.5469
Epoch 116/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7283.4209 - mae: 7283.4209
Epoch 117/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7231.0884 - mae: 7231.0884
Epoch 118/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7196.5474 - mae: 7196.5474
Epoch 119/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7166.2227 - mae: 7166.2227
Epoch 120/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7337.7407 - mae: 7337.7407
Epoch 121/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7365.2451 - mae: 7365.2451
Epoch 122/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7088.2622 - mae: 7088.2622
Epoch 123/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7104.4727 - mae: 7104.4727
Epoch 124/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7011.4551 - mae: 7011.4551
Epoch 125/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7152.5918 - mae: 7152.5918
Epoch 126/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7307.4087 - mae: 7307.4087
Epoch 127/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7285.8550 - mae: 7285.8545
Epoch 128/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7106.8833 - mae: 7106.8833
Epoch 129/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7090.7070 - mae: 7090.7070
Epoch 130/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6938.9707 - mae: 6938.9707
Epoch 131/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7024.7900 - mae: 7024.7900
Epoch 132/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6871.4146 - mae: 6871.4146
Epoch 133/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6921.7505 - mae: 6921.7505
Epoch 134/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6757.2012 - mae: 6757.2012
Epoch 135/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6867.4595 - mae: 6867.4595
Epoch 136/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6850.5078 - mae: 6850.5078
Epoch 137/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6968.8892 - mae: 6968.8892
Epoch 138/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7014.8726 - mae: 7014.8726
Epoch 139/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6932.9004 - mae: 6932.9004
Epoch 140/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6979.2817 - mae: 6979.2817
Epoch 141/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6958.2720 - mae: 6958.2720
Epoch 142/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6704.2725 - mae: 6704.2725
Epoch 143/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6870.2090 - mae: 6870.2090
Epoch 144/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6764.0723 - mae: 6764.0723
Epoch 145/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6680.1860 - mae: 6680.1860
Epoch 146/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6599.8042 - mae: 6599.8042
Epoch 147/147
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6711.7827 - mae: 6711.7827
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step

[I 2026-10-20 13:03:42,996] Trial 14 finished with value: 0.9279884666224634 and parameters: {'epochs': 147, 'batch_size': 38, 'units_layer1': 84, 'units_layer2': 87, 'optimizer': 'adam', 'learning_rate': 0.11593895759099831}. Best is trial 13 with value: 0.9435962770533816.

Epoch 1/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 31857.2598 - mae: 31857.2598
Epoch 2/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 21684.3828 - mae: 21684.3828
Epoch 3/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20886.1465 - mae: 20886.1465
Epoch 4/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20357.6895 - mae: 20357.6895
Epoch 5/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19364.6348 - mae: 19364.6348
Epoch 6/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19265.7090 - mae: 19265.7090
Epoch 7/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19184.4102 - mae: 19184.4102
Epoch 8/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18653.7031 - mae: 18653.7031
Epoch 9/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 17893.8008 - mae: 17893.8008
Epoch 10/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17134.2754 - mae: 17134.2754
Epoch 11/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15871.4756 - mae: 15871.4756
Epoch 12/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14494.1660 - mae: 14494.1660
Epoch 13/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13708.8809 - mae: 13708.8809
Epoch 14/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13631.1777 - mae: 13631.1777
Epoch 15/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13724.1465 - mae: 13724.1465
Epoch 16/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12776.5645 - mae: 12776.5645
Epoch 17/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12678.7910 - mae: 12678.7910
Epoch 18/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12894.2109 - mae: 12894.2109
Epoch 19/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11587.6758 - mae: 11587.6758
Epoch 20/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11438.8008 - mae: 11438.8008
Epoch 21/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11609.5527 - mae: 11609.5518
Epoch 22/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11114.2402 - mae: 11114.2402
Epoch 23/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10630.6182 - mae: 10630.6182
Epoch 24/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10489.1201 - mae: 10489.1201
Epoch 25/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10816.5889 - mae: 10816.5879
Epoch 26/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10101.7578 - mae: 10101.7578
Epoch 27/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10665.3848 - mae: 10665.3848
Epoch 28/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10456.1553 - mae: 10456.1553
Epoch 29/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10065.9980 - mae: 10065.9980
Epoch 30/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9981.1738 - mae: 9981.1738
Epoch 31/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9855.1904 - mae: 9855.1904
Epoch 32/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9473.6045 - mae: 9473.6025
Epoch 33/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9338.4541 - mae: 9338.4541
Epoch 34/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9801.2715 - mae: 9801.2715
Epoch 35/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9230.4189 - mae: 9230.4189
Epoch 36/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9102.3564 - mae: 9102.3564
Epoch 37/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9267.8467 - mae: 9267.8467
Epoch 38/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9278.0088 - mae: 9278.0088
Epoch 39/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9004.1875 - mae: 9004.1875
Epoch 40/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8987.5293 - mae: 8987.5293
Epoch 41/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8911.8145 - mae: 8911.8145
Epoch 42/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8864.5527 - mae: 8864.5527
Epoch 43/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9112.1914 - mae: 9112.1914
Epoch 44/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8609.6426 - mae: 8609.6426
Epoch 45/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8626.9082 - mae: 8626.9082
Epoch 46/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8559.5684 - mae: 8559.5674
Epoch 47/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8526.7754 - mae: 8526.7754
Epoch 48/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7979.5513 - mae: 7979.5513
Epoch 49/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8296.3633 - mae: 8296.3633
Epoch 50/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8407.3174 - mae: 8407.3184
Epoch 51/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8421.9434 - mae: 8421.9434
Epoch 52/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8034.9658 - mae: 8034.9658
Epoch 53/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7870.8428 - mae: 7870.8428
Epoch 54/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7956.8662 - mae: 7956.8662
Epoch 55/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8082.4907 - mae: 8082.4907
Epoch 56/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7832.7217 - mae: 7832.7217
Epoch 57/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7878.4150 - mae: 7878.4150
Epoch 58/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8231.3662 - mae: 8231.3662
Epoch 59/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7848.2964 - mae: 7848.2964
Epoch 60/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7791.5684 - mae: 7791.5684
Epoch 61/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8107.3975 - mae: 8107.3975
Epoch 62/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7821.2925 - mae: 7821.2925
Epoch 63/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7411.2944 - mae: 7411.2944
Epoch 64/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7808.9468 - mae: 7808.9468
Epoch 65/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7848.0801 - mae: 7848.0801
Epoch 66/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7438.5522 - mae: 7438.5522
Epoch 67/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8209.8828 - mae: 8209.8828
Epoch 68/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7361.6665 - mae: 7361.6665
Epoch 69/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7595.3574 - mae: 7595.3574
Epoch 70/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7720.4941 - mae: 7720.4941
Epoch 71/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7479.2041 - mae: 7479.2041
Epoch 72/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7178.5713 - mae: 7178.5713
Epoch 73/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7626.1382 - mae: 7626.1382
Epoch 74/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7194.9312 - mae: 7194.9312
Epoch 75/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7412.7456 - mae: 7412.7456
Epoch 76/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7763.6016 - mae: 7763.6016
Epoch 77/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7078.0322 - mae: 7078.0322
Epoch 78/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7298.8340 - mae: 7298.8340
Epoch 79/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7327.4170 - mae: 7327.4170
Epoch 80/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7533.4380 - mae: 7533.4380
Epoch 81/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7050.0498 - mae: 7050.0498
Epoch 82/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6869.8911 - mae: 6869.8911
Epoch 83/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7411.6484 - mae: 7411.6484
Epoch 84/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6910.0591 - mae: 6910.0591
Epoch 85/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6860.0410 - mae: 6860.0425
Epoch 86/86
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6902.3032 - mae: 6902.3032
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

[I 2026-10-20 13:04:12,803] Trial 15 finished with value: 0.9306801474201816 and parameters: {'epochs': 86, 'batch_size': 40, 'units_layer1': 69, 'units_layer2': 102, 'optimizer': 'adam', 'learning_rate': 0.2809312293491673}. Best is trial 13 with value: 0.9435962770533816.

Epoch 1/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 45437.3594 - mae: 45437.3594
Epoch 2/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 21495.7676 - mae: 21495.7676
Epoch 3/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 21206.5234 - mae: 21206.5234
Epoch 4/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20990.7539 - mae: 20990.7539
Epoch 5/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20625.7969 - mae: 20625.7969
Epoch 6/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20480.1680 - mae: 20480.1680
Epoch 7/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20173.0371 - mae: 20173.0371
Epoch 8/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20014.9883 - mae: 20014.9883
Epoch 9/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19848.7832 - mae: 19848.7832
Epoch 10/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19794.0801 - mae: 19794.0820
Epoch 11/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19631.8730 - mae: 19631.8730
Epoch 12/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19598.6680 - mae: 19598.6680
Epoch 13/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19531.7793 - mae: 19531.7793
Epoch 14/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19498.9473 - mae: 19498.9473
Epoch 15/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19416.8086 - mae: 19416.8086
Epoch 16/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19497.3555 - mae: 19497.3555
Epoch 17/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19445.2734 - mae: 19445.2734
Epoch 18/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 19409.3691 - mae: 19409.3691
Epoch 19/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19295.8457 - mae: 19295.8457
Epoch 20/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19303.5039 - mae: 19303.5039
Epoch 21/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19306.1270 - mae: 19306.1270
Epoch 22/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19277.5156 - mae: 19277.5156
Epoch 23/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19242.9883 - mae: 19242.9883
Epoch 24/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19152.1309 - mae: 19152.1309
Epoch 25/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19171.2656 - mae: 19171.2656
Epoch 26/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19136.4766 - mae: 19136.4766
Epoch 27/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19140.1152 - mae: 19140.1152
Epoch 28/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19071.1445 - mae: 19071.1445
Epoch 29/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19177.6055 - mae: 19177.6055
Epoch 30/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19145.7051 - mae: 19145.7051
Epoch 31/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18615.7812 - mae: 18615.7812
Epoch 32/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17690.5039 - mae: 17690.5039
Epoch 33/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17174.8047 - mae: 17174.8047
Epoch 34/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17114.7988 - mae: 17114.7988
Epoch 35/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 16938.6855 - mae: 16938.6855
Epoch 36/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16815.2012 - mae: 16815.2012
Epoch 37/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16374.7412 - mae: 16374.7412
Epoch 38/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16086.7383 - mae: 16086.7383
Epoch 39/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15796.4795 - mae: 15796.4795
Epoch 40/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15448.3926 - mae: 15448.3945
Epoch 41/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15234.3086 - mae: 15234.3086
Epoch 42/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15027.2881 - mae: 15027.2881
Epoch 43/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14709.1406 - mae: 14709.1406
Epoch 44/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14719.8389 - mae: 14719.8389
Epoch 45/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14227.2686 - mae: 14227.2695
Epoch 46/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13946.5098 - mae: 13946.5098
Epoch 47/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13772.1133 - mae: 13772.1133
Epoch 48/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13457.9111 - mae: 13457.9111
Epoch 49/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13418.5010 - mae: 13418.5010
Epoch 50/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13272.9111 - mae: 13272.9111
Epoch 51/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12918.2744 - mae: 12918.2744
Epoch 52/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12767.6152 - mae: 12767.6152
Epoch 53/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12742.2588 - mae: 12742.2588
Epoch 54/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12715.8340 - mae: 12715.8340
Epoch 55/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12566.9053 - mae: 12566.9053
Epoch 56/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12560.6797 - mae: 12560.6797
Epoch 57/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12178.5273 - mae: 12178.5273
Epoch 58/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12207.7969 - mae: 12207.7969
Epoch 59/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12145.9141 - mae: 12145.9141
Epoch 60/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12213.0928 - mae: 12213.0928
Epoch 61/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12020.0273 - mae: 12020.0273
Epoch 62/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11855.0127 - mae: 11855.0127
Epoch 63/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11910.3828 - mae: 11910.3828
Epoch 64/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11853.8301 - mae: 11853.8301
Epoch 65/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11884.7979 - mae: 11884.7979
Epoch 66/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11701.9346 - mae: 11701.9346
Epoch 67/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11639.4463 - mae: 11639.4463
Epoch 68/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11635.0215 - mae: 11635.0215
Epoch 69/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11532.0205 - mae: 11532.0205
Epoch 70/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11492.8730 - mae: 11492.8730
Epoch 71/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11549.1934 - mae: 11549.1934
Epoch 72/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11454.1406 - mae: 11454.1406
Epoch 73/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11404.2930 - mae: 11404.2930
Epoch 74/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11294.1064 - mae: 11294.1064
Epoch 75/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11173.3301 - mae: 11173.3301
Epoch 76/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11137.9131 - mae: 11137.9131
Epoch 77/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11019.8301 - mae: 11019.8301
Epoch 78/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10961.7285 - mae: 10961.7285
Epoch 79/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10895.2900 - mae: 10895.2900
Epoch 80/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10921.5645 - mae: 10921.5645
Epoch 81/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10777.6768 - mae: 10777.6768
Epoch 82/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10669.0049 - mae: 10669.0049
Epoch 83/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10635.3047 - mae: 10635.3047
Epoch 84/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10610.7490 - mae: 10610.7490
Epoch 85/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10539.8691 - mae: 10539.8691
Epoch 86/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10492.9453 - mae: 10492.9453
Epoch 87/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10489.2373 - mae: 10489.2373
Epoch 88/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10362.2432 - mae: 10362.2432
Epoch 89/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10206.1914 - mae: 10206.1914
Epoch 90/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10197.4502 - mae: 10197.4502
Epoch 91/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10288.9756 - mae: 10288.9756
Epoch 92/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10123.8232 - mae: 10123.8232
Epoch 93/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10141.2441 - mae: 10141.2441
Epoch 94/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10111.1455 - mae: 10111.1455
Epoch 95/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10071.3174 - mae: 10071.3174
Epoch 96/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10004.2881 - mae: 10004.2881
Epoch 97/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 10038.7686 - mae: 10038.7686
Epoch 98/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 9976.7637 - mae: 9976.7637
Epoch 99/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9912.1680 - mae: 9912.1680
Epoch 100/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9872.3105 - mae: 9872.3086
Epoch 101/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9834.2559 - mae: 9834.2559
Epoch 102/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9699.7627 - mae: 9699.7627
Epoch 103/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9920.6055 - mae: 9920.6055
Epoch 104/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9582.7295 - mae: 9582.7295
Epoch 105/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9612.7305 - mae: 9612.7305
Epoch 106/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9595.4736 - mae: 9595.4736
Epoch 107/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9521.6016 - mae: 9521.6016
Epoch 108/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9573.7100 - mae: 9573.7100
Epoch 109/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9640.2959 - mae: 9640.2959
Epoch 110/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9532.1973 - mae: 9532.1973
Epoch 111/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9392.0156 - mae: 9392.0156
Epoch 112/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9350.0088 - mae: 9350.0088
Epoch 113/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9205.8184 - mae: 9205.8184
Epoch 114/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9505.9258 - mae: 9505.9258
Epoch 115/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9645.9785 - mae: 9645.9785
Epoch 116/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9200.0156 - mae: 9200.0156
Epoch 117/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9257.4570 - mae: 9257.4570
Epoch 118/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9149.7100 - mae: 9149.7100
Epoch 119/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9520.0420 - mae: 9520.0420
Epoch 120/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9122.5674 - mae: 9122.5674
Epoch 121/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9249.4736 - mae: 9249.4736
Epoch 122/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9064.2754 - mae: 9064.2754
Epoch 123/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9090.2900 - mae: 9090.2900
Epoch 124/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9215.6787 - mae: 9215.6787
Epoch 125/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9026.6338 - mae: 9026.6338
Epoch 126/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9050.0205 - mae: 9050.0205
Epoch 127/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8950.4639 - mae: 8950.4639
Epoch 128/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8977.5176 - mae: 8977.5176
Epoch 129/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8943.1689 - mae: 8943.1689
Epoch 130/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9056.3633 - mae: 9056.3633
Epoch 131/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8932.3428 - mae: 8932.3428
Epoch 132/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8813.5928 - mae: 8813.5928
Epoch 133/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8759.1436 - mae: 8759.1436
Epoch 134/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9105.4502 - mae: 9105.4502
Epoch 135/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8905.2002 - mae: 8905.2002
Epoch 136/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8848.1318 - mae: 8848.1328
Epoch 137/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8760.4551 - mae: 8760.4551
Epoch 138/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8769.9443 - mae: 8769.9443
Epoch 139/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8714.6260 - mae: 8714.6260
Epoch 140/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8708.6426 - mae: 8708.6426
Epoch 141/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8554.9492 - mae: 8554.9492
Epoch 142/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8470.8203 - mae: 8470.8203
Epoch 143/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8485.5107 - mae: 8485.5107
Epoch 144/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8581.2246 - mae: 8581.2246
Epoch 145/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8743.7422 - mae: 8743.7422
Epoch 146/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8477.9648 - mae: 8477.9648
Epoch 147/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8503.0947 - mae: 8503.0947
Epoch 148/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8510.8447 - mae: 8510.8447
Epoch 149/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8507.2949 - mae: 8507.2949
Epoch 150/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8341.4268 - mae: 8341.4268
Epoch 151/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8347.4600 - mae: 8347.4600
Epoch 152/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8384.0146 - mae: 8384.0146
Epoch 153/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8460.2812 - mae: 8460.2812
Epoch 154/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8478.7920 - mae: 8478.7920
Epoch 155/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8228.4580 - mae: 8228.4580
Epoch 156/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8362.4180 - mae: 8362.4180
Epoch 157/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8146.4316 - mae: 8146.4316
Epoch 158/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8328.6104 - mae: 8328.6104
Epoch 159/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8201.2842 - mae: 8201.2842
Epoch 160/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8227.8496 - mae: 8227.8496
Epoch 161/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8126.8804 - mae: 8126.8804
Epoch 162/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8091.1733 - mae: 8091.1733
Epoch 163/163
134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8012.1187 - mae: 8012.1187
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

[I 2026-10-20 13:05:01,636] Trial 16 finished with value: 0.9214408545386559 and parameters: {'epochs': 163, 'batch_size': 40, 'units_layer1': 96, 'units_layer2': 76, 'optimizer': 'adam', 'learning_rate': 0.06715914469839797}. Best is trial 13 with value: 0.9435962770533816.

Epoch 1/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 29605.5000 - mae: 29605.5000
Epoch 2/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 21699.5293 - mae: 21699.5293
Epoch 3/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20982.5898 - mae: 20982.5898
Epoch 4/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 21147.1973 - mae: 21147.1973
Epoch 5/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20854.6074 - mae: 20854.6074
Epoch 6/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 21055.2227 - mae: 21055.2227
Epoch 7/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20584.5039 - mae: 20584.5039
Epoch 8/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19755.0059 - mae: 19755.0059
Epoch 9/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19817.8281 - mae: 19817.8281
Epoch 10/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18720.2617 - mae: 18720.2617
Epoch 11/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17702.3984 - mae: 17702.3984
Epoch 12/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17252.0840 - mae: 17252.0840
Epoch 13/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16500.8145 - mae: 16500.8145
Epoch 14/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15670.2744 - mae: 15670.2744
Epoch 15/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15354.1758 - mae: 15354.1758
Epoch 16/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14695.3594 - mae: 14695.3594
Epoch 17/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14390.2354 - mae: 14390.2354
Epoch 18/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13761.4619 - mae: 13761.4619
Epoch 19/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13460.0234 - mae: 13460.0234
Epoch 20/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13711.6611 - mae: 13711.6611
Epoch 21/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13385.2842 - mae: 13385.2842
Epoch 22/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12384.0430 - mae: 12384.0430
Epoch 23/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12570.2744 - mae: 12570.2744
Epoch 24/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12649.7471 - mae: 12649.7471
Epoch 25/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12172.2236 - mae: 12172.2236
Epoch 26/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12503.4521 - mae: 12503.4521
Epoch 27/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11420.0596 - mae: 11420.0596
Epoch 28/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11392.0615 - mae: 11392.0615
Epoch 29/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11344.9795 - mae: 11344.9795
Epoch 30/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11031.8896 - mae: 11031.8896
Epoch 31/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11111.2031 - mae: 11111.2031
Epoch 32/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10925.6729 - mae: 10925.6719
Epoch 33/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10767.1748 - mae: 10767.1748
Epoch 34/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10712.0996 - mae: 10712.0996
Epoch 35/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10319.8887 - mae: 10319.8887
Epoch 36/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10390.1885 - mae: 10390.1885
Epoch 37/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10405.0176 - mae: 10405.0176
Epoch 38/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9998.7275 - mae: 9998.7275
Epoch 39/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9636.4082 - mae: 9636.4082
Epoch 40/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10008.8936 - mae: 10008.8936
Epoch 41/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9735.8672 - mae: 9735.8672
Epoch 42/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9585.1650 - mae: 9585.1650
Epoch 43/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9387.1855 - mae: 9387.1855
Epoch 44/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9300.4521 - mae: 9300.4521
Epoch 45/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9345.6475 - mae: 9345.6475
Epoch 46/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9496.9404 - mae: 9496.9404
Epoch 47/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9079.0635 - mae: 9079.0635
Epoch 48/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9304.7109 - mae: 9304.7109
Epoch 49/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9223.4775 - mae: 9223.4775
Epoch 50/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9191.7773 - mae: 9191.7764
Epoch 51/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8965.6875 - mae: 8965.6855
Epoch 52/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9130.0371 - mae: 9130.0371
Epoch 53/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8899.6719 - mae: 8899.6719
Epoch 54/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8760.8203 - mae: 8760.8203
Epoch 55/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8755.0703 - mae: 8755.0703
Epoch 56/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8586.7168 - mae: 8586.7168
Epoch 57/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8358.0381 - mae: 8358.0381
Epoch 58/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8379.5029 - mae: 8379.5029
Epoch 59/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8256.6230 - mae: 8256.6230
Epoch 60/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8073.6782 - mae: 8073.6782
Epoch 61/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8242.8594 - mae: 8242.8594
Epoch 62/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8057.9326 - mae: 8057.9326
Epoch 63/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8081.7349 - mae: 8081.7349
Epoch 64/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8006.3105 - mae: 8006.3105
Epoch 65/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8067.0532 - mae: 8067.0532
Epoch 66/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7883.7476 - mae: 7883.7476
Epoch 67/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7992.3657 - mae: 7992.3657
Epoch 68/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7755.5571 - mae: 7755.5571
Epoch 69/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7814.5747 - mae: 7814.5747
Epoch 70/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7682.4526 - mae: 7682.4526
Epoch 71/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7921.5112 - mae: 7921.5112
Epoch 72/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7528.4180 - mae: 7528.4180
Epoch 73/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7639.3989 - mae: 7639.3989
Epoch 74/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7596.9751 - mae: 7596.9751
Epoch 75/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7507.6250 - mae: 7507.6250
Epoch 76/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7450.1084 - mae: 7450.1084
Epoch 77/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7720.5254 - mae: 7720.5254
Epoch 78/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7368.1748 - mae: 7368.1748
Epoch 79/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7152.8555 - mae: 7152.8555
Epoch 80/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7441.7769 - mae: 7441.7769
Epoch 81/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7581.2744 - mae: 7581.2744
Epoch 82/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7425.7573 - mae: 7425.7573
Epoch 83/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7051.1714 - mae: 7051.1714
Epoch 84/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7141.5239 - mae: 7141.5239
Epoch 85/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7151.0391 - mae: 7151.0391
Epoch 86/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7187.5386 - mae: 7187.5386
Epoch 87/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7552.4238 - mae: 7552.4238
Epoch 88/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7262.4204 - mae: 7262.4204
Epoch 89/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6944.1973 - mae: 6944.1973
Epoch 90/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7126.4419 - mae: 7126.4419
Epoch 91/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7147.4692 - mae: 7147.4692
Epoch 92/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6712.1196 - mae: 6712.1196
Epoch 93/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7398.2598 - mae: 7398.2598
Epoch 94/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6993.2222 - mae: 6993.2222
Epoch 95/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6812.8945 - mae: 6812.8945
Epoch 96/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6735.2065 - mae: 6735.2065
Epoch 97/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6841.4824 - mae: 6841.4824
Epoch 98/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6949.0786 - mae: 6949.0786
Epoch 99/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6808.8696 - mae: 6808.8696
Epoch 100/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6825.0698 - mae: 6825.0698
Epoch 101/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7177.2646 - mae: 7177.2646
Epoch 102/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6977.3101 - mae: 6977.3101
Epoch 103/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6655.2925 - mae: 6655.2925
Epoch 104/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6742.5562 - mae: 6742.5562
Epoch 105/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6791.0942 - mae: 6791.0942
Epoch 106/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6782.1060 - mae: 6782.1060
Epoch 107/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6689.9771 - mae: 6689.9771
Epoch 108/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6801.5493 - mae: 6801.5493
Epoch 109/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6713.8926 - mae: 6713.8926
Epoch 110/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6836.5918 - mae: 6836.5918
Epoch 111/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6800.6772 - mae: 6800.6772
Epoch 112/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6471.0166 - mae: 6471.0166
Epoch 113/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6651.1841 - mae: 6651.1841
Epoch 114/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6739.1685 - mae: 6739.1685
Epoch 115/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6745.6587 - mae: 6745.6587
Epoch 116/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6428.8608 - mae: 6428.8608
Epoch 117/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6610.5601 - mae: 6610.5601
Epoch 118/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6392.5718 - mae: 6392.5718
Epoch 119/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6369.5737 - mae: 6369.5737
Epoch 120/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6466.6553 - mae: 6466.6553
Epoch 121/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6339.1348 - mae: 6339.1348
Epoch 122/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6419.4976 - mae: 6419.4976
Epoch 123/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6214.2832 - mae: 6214.2832
Epoch 124/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6336.7314 - mae: 6336.7314
Epoch 125/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6410.9639 - mae: 6410.9639
Epoch 126/126
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6321.0010 - mae: 6321.0010
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

[I 2026-10-20 13:05:46,522] Trial 17 finished with value: 0.937727010855747 and parameters: {'epochs': 126, 'batch_size': 33, 'units_layer1': 122, 'units_layer2': 118, 'optimizer': 'adam', 'learning_rate': 0.2011463131564543}. Best is trial 13 with value: 0.9435962770533816.

Epoch 1/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 30184.3457 - mae: 30184.3457
Epoch 2/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 21811.7383 - mae: 21811.7383
Epoch 3/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 21238.5156 - mae: 21238.5156
Epoch 4/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 21089.0234 - mae: 21089.0234
Epoch 5/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20864.2285 - mae: 20864.2285
Epoch 6/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20783.3750 - mae: 20783.3750
Epoch 7/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20536.0176 - mae: 20536.0176
Epoch 8/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19968.7520 - mae: 19968.7520
Epoch 9/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19430.9473 - mae: 19430.9473
Epoch 10/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19135.5039 - mae: 19135.5039
Epoch 11/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18763.9961 - mae: 18763.9961
Epoch 12/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18376.3770 - mae: 18376.3770
Epoch 13/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17991.2461 - mae: 17991.2461
Epoch 14/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17495.2617 - mae: 17495.2617
Epoch 15/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16957.3105 - mae: 16957.3105
Epoch 16/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16321.8115 - mae: 16321.8115
Epoch 17/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16148.8496 - mae: 16148.8496
Epoch 18/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15856.1016 - mae: 15856.1016
Epoch 19/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15501.6855 - mae: 15501.6855
Epoch 20/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15400.6582 - mae: 15400.6582
Epoch 21/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15182.2158 - mae: 15182.2158
Epoch 22/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14914.6445 - mae: 14914.6445
Epoch 23/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14915.7598 - mae: 14915.7598
Epoch 24/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14422.5234 - mae: 14422.5234
Epoch 25/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14289.1074 - mae: 14289.1074
Epoch 26/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14206.9580 - mae: 14206.9580
Epoch 27/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14036.1953 - mae: 14036.1953
Epoch 28/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13823.5771 - mae: 13823.5771
Epoch 29/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13694.7188 - mae: 13694.7188
Epoch 30/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13382.2236 - mae: 13382.2236
Epoch 31/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13342.7178 - mae: 13342.7178
Epoch 32/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13224.1748 - mae: 13224.1748
Epoch 33/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12938.5068 - mae: 12938.5068
Epoch 34/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12892.1377 - mae: 12892.1377
Epoch 35/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12849.6826 - mae: 12849.6826
Epoch 36/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12556.0537 - mae: 12556.0537
Epoch 37/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12515.6777 - mae: 12515.6777
Epoch 38/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12399.4219 - mae: 12399.4219
Epoch 39/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12259.4912 - mae: 12259.4912
Epoch 40/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12140.9492 - mae: 12140.9492
Epoch 41/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12002.9121 - mae: 12002.9121
Epoch 42/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11860.4219 - mae: 11860.4229
Epoch 43/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11832.7588 - mae: 11832.7588
Epoch 44/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11733.0107 - mae: 11733.0107
Epoch 45/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11629.6357 - mae: 11629.6357
Epoch 46/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11602.7402 - mae: 11602.7402
Epoch 47/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11285.7744 - mae: 11285.7744
Epoch 48/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11404.1963 - mae: 11404.1953
Epoch 49/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11379.3564 - mae: 11379.3564
Epoch 50/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11192.2900 - mae: 11192.2900
Epoch 51/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11111.2236 - mae: 11111.2236
Epoch 52/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10961.8145 - mae: 10961.8145
Epoch 53/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10906.5732 - mae: 10906.5732
Epoch 54/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10864.7656 - mae: 10864.7656
Epoch 55/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10740.3594 - mae: 10740.3594
Epoch 56/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10676.1191 - mae: 10676.1191
Epoch 57/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10690.2354 - mae: 10690.2354
Epoch 58/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10533.2314 - mae: 10533.2314
Epoch 59/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10355.4121 - mae: 10355.4121
Epoch 60/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10311.6230 - mae: 10311.6230
Epoch 61/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10211.2119 - mae: 10211.2119
Epoch 62/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10156.2158 - mae: 10156.2148
Epoch 63/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10052.3252 - mae: 10052.3252
Epoch 64/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9940.2266 - mae: 9940.2266
Epoch 65/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10003.9609 - mae: 10003.9609
Epoch 66/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9790.5605 - mae: 9790.5605
Epoch 67/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9762.6719 - mae: 9762.6719
Epoch 68/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9681.5244 - mae: 9681.5244
Epoch 69/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9570.6162 - mae: 9570.6162
Epoch 70/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9437.3330 - mae: 9437.3330
Epoch 71/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9510.8965 - mae: 9510.8975
Epoch 72/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9397.7832 - mae: 9397.7832
Epoch 73/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9373.5859 - mae: 9373.5859
Epoch 74/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9260.4072 - mae: 9260.4072
Epoch 75/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9208.8799 - mae: 9208.8799
Epoch 76/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9090.9463 - mae: 9090.9463
Epoch 77/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9004.5752 - mae: 9004.5752
Epoch 78/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9027.4551 - mae: 9027.4551
Epoch 79/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9000.8066 - mae: 9000.8066
Epoch 80/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8935.6221 - mae: 8935.6221
Epoch 81/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8889.5918 - mae: 8889.5918
Epoch 82/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8816.2637 - mae: 8816.2637
Epoch 83/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8689.9531 - mae: 8689.9531
Epoch 84/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8813.8428 - mae: 8813.8428
Epoch 85/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8616.5195 - mae: 8616.5195
Epoch 86/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8593.0947 - mae: 8593.0947
Epoch 87/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8494.6982 - mae: 8494.6982
Epoch 88/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8499.5557 - mae: 8499.5557
Epoch 89/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8416.4004 - mae: 8416.4004
Epoch 90/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8468.5771 - mae: 8468.5771
Epoch 91/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8448.8955 - mae: 8448.8955
Epoch 92/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8366.3916 - mae: 8366.3916
Epoch 93/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8370.4326 - mae: 8370.4326
Epoch 94/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8345.5439 - mae: 8345.5439
Epoch 95/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8259.0127 - mae: 8259.0127
Epoch 96/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8232.6660 - mae: 8232.6660
Epoch 97/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8128.0820 - mae: 8128.0820
Epoch 98/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8193.5996 - mae: 8193.5996
Epoch 99/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8003.3906 - mae: 8003.3906
Epoch 100/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8109.4990 - mae: 8109.4990
Epoch 101/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7999.3228 - mae: 7999.3228
Epoch 102/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8135.5366 - mae: 8135.5366
Epoch 103/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7885.0215 - mae: 7885.0220
Epoch 104/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7967.8179 - mae: 7967.8179
Epoch 105/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7870.6904 - mae: 7870.6904
Epoch 106/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7809.6782 - mae: 7809.6782
Epoch 107/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7864.9487 - mae: 7864.9482
Epoch 108/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7756.9883 - mae: 7756.9883
Epoch 109/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7850.0239 - mae: 7850.0239
Epoch 110/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7765.7109 - mae: 7765.7109
Epoch 111/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7782.3511 - mae: 7782.3511
Epoch 112/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7669.5698 - mae: 7669.5698
Epoch 113/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7586.3921 - mae: 7586.3921
Epoch 114/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7544.3726 - mae: 7544.3726
Epoch 115/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7468.7412 - mae: 7468.7412
Epoch 116/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7486.4985 - mae: 7486.4980
Epoch 117/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7537.8022 - mae: 7537.8022
Epoch 118/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7405.5347 - mae: 7405.5347
Epoch 119/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7484.0674 - mae: 7484.0674
Epoch 120/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7364.4653 - mae: 7364.4653
Epoch 121/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7453.0303 - mae: 7453.0303
Epoch 122/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7373.0229 - mae: 7373.0229
Epoch 123/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7366.7520 - mae: 7366.7520
Epoch 124/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7277.9419 - mae: 7277.9419
Epoch 125/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7249.5728 - mae: 7249.5728
Epoch 126/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7256.5420 - mae: 7256.5420
Epoch 127/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7197.9717 - mae: 7197.9717
Epoch 128/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7198.9565 - mae: 7198.9565
Epoch 129/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7057.0342 - mae: 7057.0342
Epoch 130/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7071.2275 - mae: 7071.2275
Epoch 131/131
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7129.6880 - mae: 7129.6880
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

[I 2026-10-20 13:06:24,640] Trial 18 finished with value: 0.9391719815589764 and parameters: {'epochs': 131, 'batch_size': 43, 'units_layer1': 127, 'units_layer2': 126, 'optimizer': 'rmsprop', 'learning_rate': 0.07224990211475081}. Best is trial 13 with value: 0.9435962770533816.

Epoch 1/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 39356.6289 - mae: 39356.6289
Epoch 2/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 21686.1270 - mae: 21686.1270
Epoch 3/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 21105.4062 - mae: 21105.4062
Epoch 4/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20813.8418 - mae: 20813.8418
Epoch 5/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20586.7676 - mae: 20586.7676
Epoch 6/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20391.6543 - mae: 20391.6543
Epoch 7/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20282.7891 - mae: 20282.7891
Epoch 8/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20162.4434 - mae: 20162.4434
Epoch 9/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20140.2852 - mae: 20140.2852
Epoch 10/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20117.8516 - mae: 20117.8516
Epoch 11/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20069.3535 - mae: 20069.3535
Epoch 12/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20012.5664 - mae: 20012.5664
Epoch 13/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20029.2480 - mae: 20029.2480
Epoch 14/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19941.9160 - mae: 19941.9160
Epoch 15/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19956.4707 - mae: 19956.4707
Epoch 16/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19948.7871 - mae: 19948.7871
Epoch 17/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19752.1562 - mae: 19752.1602
Epoch 18/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19324.6953 - mae: 19324.6953
Epoch 19/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18645.1641 - mae: 18645.1641
Epoch 20/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18200.5117 - mae: 18200.5117
Epoch 21/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17901.5508 - mae: 17901.5508
Epoch 22/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17648.6230 - mae: 17648.6230
Epoch 23/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17338.3398 - mae: 17338.3398
Epoch 24/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 17130.3984 - mae: 17130.3984
Epoch 25/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16867.0898 - mae: 16867.0898
Epoch 26/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16722.3516 - mae: 16722.3516
Epoch 27/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16440.3223 - mae: 16440.3223
Epoch 28/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16135.9121 - mae: 16135.9121
Epoch 29/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15886.4102 - mae: 15886.4102
Epoch 30/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15699.3164 - mae: 15699.3164
Epoch 31/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15450.2266 - mae: 15450.2266
Epoch 32/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15347.8027 - mae: 15347.8027
Epoch 33/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15196.8252 - mae: 15196.8252
Epoch 34/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 15128.6494 - mae: 15128.6494
Epoch 35/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15086.8535 - mae: 15086.8535
Epoch 36/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 14951.7734 - mae: 14951.7734
Epoch 37/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 14937.1934 - mae: 14937.1934
Epoch 38/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 14850.1953 - mae: 14850.1953
Epoch 39/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 14830.1572 - mae: 14830.1572
Epoch 40/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 14713.9141 - mae: 14713.9141
Epoch 41/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14644.6387 - mae: 14644.6387
Epoch 42/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14578.4482 - mae: 14578.4482
Epoch 43/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14485.4346 - mae: 14485.4336
Epoch 44/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14464.2598 - mae: 14464.2598
Epoch 45/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14292.3555 - mae: 14292.3555
Epoch 46/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14255.5625 - mae: 14255.5625
Epoch 47/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14125.8799 - mae: 14125.8799
Epoch 48/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14138.2100 - mae: 14138.2100
Epoch 49/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14101.0762 - mae: 14101.0762
Epoch 50/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13962.4766 - mae: 13962.4766
Epoch 51/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13987.2520 - mae: 13987.2539
Epoch 52/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13790.6455 - mae: 13790.6455
Epoch 53/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13734.5273 - mae: 13734.5273
Epoch 54/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13631.7461 - mae: 13631.7461
Epoch 55/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13640.1973 - mae: 13640.1973
Epoch 56/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13482.1406 - mae: 13482.1406
Epoch 57/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13530.0586 - mae: 13530.0586
Epoch 58/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13516.9990 - mae: 13516.9990
Epoch 59/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13361.4541 - mae: 13361.4541
Epoch 60/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13266.0205 - mae: 13266.0205
Epoch 61/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13256.2520 - mae: 13256.2520
Epoch 62/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13216.8857 - mae: 13216.8857
Epoch 63/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13147.2686 - mae: 13147.2695
Epoch 64/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13103.3047 - mae: 13103.3057
Epoch 65/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13027.2500 - mae: 13027.2500
Epoch 66/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12916.2969 - mae: 12916.2969
Epoch 67/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12951.1162 - mae: 12951.1162
Epoch 68/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12954.3877 - mae: 12954.3877
Epoch 69/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12877.6748 - mae: 12877.6748
Epoch 70/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12880.0557 - mae: 12880.0557
Epoch 71/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12859.0820 - mae: 12859.0801
Epoch 72/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12731.8721 - mae: 12731.8721
Epoch 73/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12742.2305 - mae: 12742.2305
Epoch 74/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12665.7480 - mae: 12665.7480
Epoch 75/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 12580.7031 - mae: 12580.7031
Epoch 76/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12629.7422 - mae: 12629.7422
Epoch 77/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12651.9541 - mae: 12651.9541
Epoch 78/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12560.2959 - mae: 12560.2959
Epoch 79/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12540.1504 - mae: 12540.1504
Epoch 80/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12489.9268 - mae: 12489.9268
Epoch 81/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12500.7080 - mae: 12500.7080
Epoch 82/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12416.5889 - mae: 12416.5889
Epoch 83/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12348.1289 - mae: 12348.1289
Epoch 84/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12418.5947 - mae: 12418.5947
Epoch 85/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12322.4424 - mae: 12322.4414
Epoch 86/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12292.6621 - mae: 12292.6631
Epoch 87/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12214.6055 - mae: 12214.6055
Epoch 88/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12215.9219 - mae: 12215.9219
Epoch 89/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12149.4883 - mae: 12149.4883
Epoch 90/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12091.9258 - mae: 12091.9258
Epoch 91/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 12148.6729 - mae: 12148.6729
Epoch 92/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12057.1074 - mae: 12057.1064
Epoch 93/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12072.2285 - mae: 12072.2295
Epoch 94/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11975.1396 - mae: 11975.1396
Epoch 95/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11985.7480 - mae: 11985.7480
Epoch 96/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11987.9980 - mae: 11987.9980
Epoch 97/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12027.6865 - mae: 12027.6865
Epoch 98/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11871.2139 - mae: 11871.2139
Epoch 99/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11855.0732 - mae: 11855.0732
Epoch 100/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11831.3486 - mae: 11831.3486
Epoch 101/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11830.5801 - mae: 11830.5801
Epoch 102/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11788.6270 - mae: 11788.6270
Epoch 103/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11869.0361 - mae: 11869.0361
Epoch 104/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11822.6309 - mae: 11822.6309
Epoch 105/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11742.0010 - mae: 11742.0010
Epoch 106/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11617.9951 - mae: 11617.9951
Epoch 107/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 11714.7773 - mae: 11714.7773
Epoch 108/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11737.7607 - mae: 11737.7607
Epoch 109/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11645.0410 - mae: 11645.0410
Epoch 110/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11588.5771 - mae: 11588.5771
Epoch 111/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11661.1396 - mae: 11661.1396
Epoch 112/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11640.2012 - mae: 11640.2012
Epoch 113/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11671.0254 - mae: 11671.0254
Epoch 114/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11618.5303 - mae: 11618.5303
Epoch 115/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11575.9248 - mae: 11575.9248
Epoch 116/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11567.4453 - mae: 11567.4453
Epoch 117/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11503.5391 - mae: 11503.5391
Epoch 118/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11505.2246 - mae: 11505.2246
Epoch 119/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11552.3535 - mae: 11552.3535
Epoch 120/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11498.9688 - mae: 11498.9678
Epoch 121/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11528.0869 - mae: 11528.0869
Epoch 122/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11402.9092 - mae: 11402.9092
Epoch 123/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11448.5020 - mae: 11448.5020
Epoch 124/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11398.9141 - mae: 11398.9121
Epoch 125/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 11462.3779 - mae: 11462.3779
Epoch 126/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11455.4033 - mae: 11455.4033
Epoch 127/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11380.1250 - mae: 11380.1250
Epoch 128/128
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 11337.7979 - mae: 11337.7979
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

[I 2026-10-20 13:06:58,067] Trial 19 finished with value: 0.8896841240841109 and parameters: {'epochs': 128, 'batch_size': 44, 'units_layer1': 31, 'units_layer2': 128, 'optimizer': 'rmsprop', 'learning_rate': 0.058503429777570996}. Best is trial 13 with value: 0.9435962770533816.

Epoch 1/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 35659.3125 - mae: 35659.3086
Epoch 2/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 21645.3848 - mae: 21645.3848
Epoch 3/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 21116.1816 - mae: 21116.1816
Epoch 4/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20972.3223 - mae: 20972.3223
Epoch 5/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20823.5039 - mae: 20823.5039
Epoch 6/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20667.8457 - mae: 20667.8457
Epoch 7/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20620.1641 - mae: 20620.1641
Epoch 8/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20370.8867 - mae: 20370.8867
Epoch 9/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19913.0938 - mae: 19913.0938
Epoch 10/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19543.9414 - mae: 19543.9414
Epoch 11/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19219.5117 - mae: 19219.5117
Epoch 12/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19058.8574 - mae: 19058.8574
Epoch 13/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18914.5195 - mae: 18914.5195
Epoch 14/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18800.1914 - mae: 18800.1914
Epoch 15/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 18662.3809 - mae: 18662.3809
Epoch 16/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 18492.3145 - mae: 18492.3145
Epoch 17/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 18468.6094 - mae: 18468.6094
Epoch 18/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18415.3867 - mae: 18415.3867
Epoch 19/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18168.1113 - mae: 18168.1113
Epoch 20/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18076.0098 - mae: 18076.0098
Epoch 21/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17822.7246 - mae: 17822.7246
Epoch 22/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 17715.5996 - mae: 17715.5996
Epoch 23/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17335.0215 - mae: 17335.0215
Epoch 24/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16978.4316 - mae: 16978.4316
Epoch 25/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16657.3145 - mae: 16657.3145
Epoch 26/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16348.6494 - mae: 16348.6514
Epoch 27/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16040.5049 - mae: 16040.5049
Epoch 28/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15815.7012 - mae: 15815.7012
Epoch 29/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15432.4346 - mae: 15432.4346
Epoch 30/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15278.2803 - mae: 15278.2803
Epoch 31/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14963.7715 - mae: 14963.7715
Epoch 32/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14822.1035 - mae: 14822.1035
Epoch 33/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14616.6436 - mae: 14616.6436
Epoch 34/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14457.2480 - mae: 14457.2480
Epoch 35/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14338.5752 - mae: 14338.5752
Epoch 36/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14243.5703 - mae: 14243.5703
Epoch 37/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14093.7705 - mae: 14093.7705
Epoch 38/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13923.3965 - mae: 13923.3965
Epoch 39/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13759.6436 - mae: 13759.6436
Epoch 40/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13577.4004 - mae: 13577.4004
Epoch 41/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13561.9141 - mae: 13561.9141
Epoch 42/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13350.5430 - mae: 13350.5430
Epoch 43/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13095.2373 - mae: 13095.2373
Epoch 44/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13140.9375 - mae: 13140.9375
Epoch 45/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12817.9111 - mae: 12817.9111
Epoch 46/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12938.6934 - mae: 12938.6934
Epoch 47/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12825.0635 - mae: 12825.0635
Epoch 48/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12749.3555 - mae: 12749.3555
Epoch 49/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12503.5752 - mae: 12503.5752
Epoch 50/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12553.1455 - mae: 12553.1455
Epoch 51/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12355.1260 - mae: 12355.1260
Epoch 52/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12402.8887 - mae: 12402.8887
Epoch 53/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12144.2139 - mae: 12144.2139
Epoch 54/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12272.8096 - mae: 12272.8096
Epoch 55/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12027.8271 - mae: 12027.8271
Epoch 56/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11907.3945 - mae: 11907.3945
Epoch 57/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11922.9746 - mae: 11922.9746
Epoch 58/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11845.2920 - mae: 11845.2920
Epoch 59/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11719.9697 - mae: 11719.9697
Epoch 60/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11607.0957 - mae: 11607.0957
Epoch 61/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11647.0127 - mae: 11647.0127
Epoch 62/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11356.5332 - mae: 11356.5332
Epoch 63/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11523.6494 - mae: 11523.6494
Epoch 64/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11500.2676 - mae: 11500.2676
Epoch 65/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11272.9854 - mae: 11272.9854
Epoch 66/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11191.6377 - mae: 11191.6377
Epoch 67/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11215.0244 - mae: 11215.0244
Epoch 68/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11233.6406 - mae: 11233.6406
Epoch 69/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11091.9805 - mae: 11091.9805
Epoch 70/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11108.2246 - mae: 11108.2246
Epoch 71/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11023.1201 - mae: 11023.1201
Epoch 72/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11006.1895 - mae: 11006.1895
Epoch 73/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10925.3398 - mae: 10925.3398
Epoch 74/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10792.6484 - mae: 10792.6465
Epoch 75/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10873.8740 - mae: 10873.8740
Epoch 76/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10776.9902 - mae: 10776.9902
Epoch 77/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10755.2871 - mae: 10755.2871
Epoch 78/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10680.0928 - mae: 10680.0928
Epoch 79/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10650.0498 - mae: 10650.0498
Epoch 80/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10689.2568 - mae: 10689.2568
Epoch 81/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10536.5322 - mae: 10536.5322
Epoch 82/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10554.3398 - mae: 10554.3398
Epoch 83/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10457.6846 - mae: 10457.6846
Epoch 84/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10415.4639 - mae: 10415.4639
Epoch 85/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10566.4355 - mae: 10566.4355
Epoch 86/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10432.2275 - mae: 10432.2275
Epoch 87/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10414.1445 - mae: 10414.1445
Epoch 88/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10392.0283 - mae: 10392.0283
Epoch 89/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10294.0537 - mae: 10294.0537
Epoch 90/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10319.0449 - mae: 10319.0449
Epoch 91/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10215.6953 - mae: 10215.6953
Epoch 92/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10255.5830 - mae: 10255.5830
Epoch 93/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10268.4521 - mae: 10268.4521
Epoch 94/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10167.9395 - mae: 10167.9395
Epoch 95/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10216.4482 - mae: 10216.4482
Epoch 96/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10246.6553 - mae: 10246.6553
Epoch 97/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10081.6934 - mae: 10081.6934
Epoch 98/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10155.7422 - mae: 10155.7422
Epoch 99/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10015.0283 - mae: 10015.0283
Epoch 100/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10145.3096 - mae: 10145.3096
Epoch 101/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9975.3623 - mae: 9975.3623
Epoch 102/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10040.8008 - mae: 10040.8008
Epoch 103/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9844.6094 - mae: 9844.6094
Epoch 104/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9770.5811 - mae: 9770.5811
Epoch 105/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9905.5645 - mae: 9905.5645
Epoch 106/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9862.9609 - mae: 9862.9609
Epoch 107/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9779.2197 - mae: 9779.2197
Epoch 108/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9902.7402 - mae: 9902.7402
Epoch 109/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9645.7842 - mae: 9645.7832
Epoch 110/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9785.0127 - mae: 9785.0127
Epoch 111/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9631.1807 - mae: 9631.1807
Epoch 112/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9564.1533 - mae: 9564.1533
Epoch 113/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9640.2861 - mae: 9640.2861
Epoch 114/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9622.7305 - mae: 9622.7305
Epoch 115/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9628.8438 - mae: 9628.8438
Epoch 116/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9638.2178 - mae: 9638.2178
Epoch 117/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9562.0654 - mae: 9562.0654
Epoch 118/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9627.7480 - mae: 9627.7480
Epoch 119/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9552.9238 - mae: 9552.9238
Epoch 120/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 9477.0791 - mae: 9477.0791
Epoch 121/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9398.9268 - mae: 9398.9268
Epoch 122/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9465.4023 - mae: 9465.4023
Epoch 123/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9501.2363 - mae: 9501.2363
Epoch 124/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9395.0107 - mae: 9395.0107
Epoch 125/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9347.4854 - mae: 9347.4854
Epoch 126/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9378.1025 - mae: 9378.1025
Epoch 127/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9292.9043 - mae: 9292.9043
Epoch 128/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9255.6182 - mae: 9255.6182
Epoch 129/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9254.3916 - mae: 9254.3916
Epoch 130/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9219.9697 - mae: 9219.9697
Epoch 131/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9184.0176 - mae: 9184.0176
Epoch 132/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9023.5137 - mae: 9023.5137
Epoch 133/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9178.0762 - mae: 9178.0762
Epoch 134/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9122.8271 - mae: 9122.8271
Epoch 135/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9125.4482 - mae: 9125.4482
Epoch 136/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9033.0869 - mae: 9033.0869
Epoch 137/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9124.7656 - mae: 9124.7656
Epoch 138/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9102.6611 - mae: 9102.6611
Epoch 139/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9005.6182 - mae: 9005.6182
Epoch 140/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8876.4756 - mae: 8876.4756
Epoch 141/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8926.7119 - mae: 8926.7119
Epoch 142/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8879.5430 - mae: 8879.5449
Epoch 143/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8890.3877 - mae: 8890.3877
Epoch 144/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8845.1211 - mae: 8845.1211
Epoch 145/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8936.2930 - mae: 8936.2930
Epoch 146/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8827.2090 - mae: 8827.2090
Epoch 147/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8796.0400 - mae: 8796.0400
Epoch 148/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8733.9541 - mae: 8733.9541
Epoch 149/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8635.6123 - mae: 8635.6113
Epoch 150/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8651.3203 - mae: 8651.3203
Epoch 151/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8715.3037 - mae: 8715.3037
Epoch 152/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8667.3574 - mae: 8667.3574
Epoch 153/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8661.3994 - mae: 8661.3994
Epoch 154/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8720.2451 - mae: 8720.2451
Epoch 155/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8694.2246 - mae: 8694.2246
Epoch 156/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8437.2236 - mae: 8437.2236
Epoch 157/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8568.0586 - mae: 8568.0586
Epoch 158/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8585.6758 - mae: 8585.6758
Epoch 159/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8456.6006 - mae: 8456.6006
Epoch 160/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8536.4092 - mae: 8536.4092
Epoch 161/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8556.3398 - mae: 8556.3398
Epoch 162/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8335.9043 - mae: 8335.9043
Epoch 163/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8418.2832 - mae: 8418.2832
Epoch 164/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8473.4209 - mae: 8473.4209
Epoch 165/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8311.1143 - mae: 8311.1143
Epoch 166/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8421.4150 - mae: 8421.4150
Epoch 167/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8360.0137 - mae: 8360.0137
Epoch 168/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8324.4385 - mae: 8324.4385
Epoch 169/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8336.5625 - mae: 8336.5625
Epoch 170/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8258.4424 - mae: 8258.4424
Epoch 171/171
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8310.6104 - mae: 8310.6104
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

[I 2026-10-20 13:07:34,345] Trial 20 finished with value: 0.9098939949192602 and parameters: {'epochs': 171, 'batch_size': 60, 'units_layer1': 61, 'units_layer2': 95, 'optimizer': 'rmsprop', 'learning_rate': 0.08740133997695515}. Best is trial 13 with value: 0.9435962770533816.

Epoch 1/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 31714.2031 - mae: 31714.2031
Epoch 2/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 25920.0723 - mae: 25920.0723
Epoch 3/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 22895.2500 - mae: 22895.2500
Epoch 4/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 21338.0156 - mae: 21338.0156
Epoch 5/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19854.5645 - mae: 19854.5645
Epoch 6/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18688.5391 - mae: 18688.5391
Epoch 7/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 17611.5273 - mae: 17611.5273
Epoch 8/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16588.2852 - mae: 16588.2852
Epoch 9/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16209.5664 - mae: 16209.5664
Epoch 10/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15680.4062 - mae: 15680.4062
Epoch 11/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15166.1904 - mae: 15166.1904
Epoch 12/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14972.8467 - mae: 14972.8467
Epoch 13/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14539.2891 - mae: 14539.2891
Epoch 14/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 14149.7197 - mae: 14149.7197
Epoch 15/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13955.9580 - mae: 13955.9580
Epoch 16/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13599.7598 - mae: 13599.7598
Epoch 17/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13391.5400 - mae: 13391.5400
Epoch 18/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13078.6709 - mae: 13078.6709
Epoch 19/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13019.9385 - mae: 13019.9385
Epoch 20/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12732.4004 - mae: 12732.4004
Epoch 21/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12367.5518 - mae: 12367.5518
Epoch 22/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12307.4219 - mae: 12307.4219
Epoch 23/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11976.3408 - mae: 11976.3408
Epoch 24/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11875.6738 - mae: 11875.6738
Epoch 25/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11611.4307 - mae: 11611.4307
Epoch 26/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 11346.1201 - mae: 11346.1201
Epoch 27/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11307.4111 - mae: 11307.4111
Epoch 28/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11165.9014 - mae: 11165.9023
Epoch 29/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10976.0977 - mae: 10976.0977
Epoch 30/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10858.2119 - mae: 10858.2119
Epoch 31/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10641.0830 - mae: 10641.0830
Epoch 32/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10527.3672 - mae: 10527.3672
Epoch 33/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10440.9990 - mae: 10440.9990
Epoch 34/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10330.6738 - mae: 10330.6738
Epoch 35/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10317.7832 - mae: 10317.7832
Epoch 36/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 10074.1406 - mae: 10074.1406
Epoch 37/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10034.9521 - mae: 10034.9521
Epoch 38/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9826.3779 - mae: 9826.3779
Epoch 39/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9767.2793 - mae: 9767.2793
Epoch 40/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9672.8633 - mae: 9672.8633
Epoch 41/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9595.0088 - mae: 9595.0088
Epoch 42/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9561.7373 - mae: 9561.7373
Epoch 43/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9527.0684 - mae: 9527.0684
Epoch 44/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9363.8564 - mae: 9363.8564
Epoch 45/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9337.0947 - mae: 9337.0947
Epoch 46/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9257.9854 - mae: 9257.9854
Epoch 47/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9332.1777 - mae: 9332.1777
Epoch 48/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9183.3926 - mae: 9183.3926
Epoch 49/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9133.8281 - mae: 9133.8281
Epoch 50/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8963.0947 - mae: 8963.0947
Epoch 51/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9016.4121 - mae: 9016.4121
Epoch 52/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9006.9111 - mae: 9006.9111
Epoch 53/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8919.5771 - mae: 8919.5771
Epoch 54/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8833.5996 - mae: 8833.5996
Epoch 55/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8887.1289 - mae: 8887.1289
Epoch 56/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8736.7881 - mae: 8736.7881
Epoch 57/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8738.5596 - mae: 8738.5596
Epoch 58/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8600.0654 - mae: 8600.0654
Epoch 59/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8688.1475 - mae: 8688.1484
Epoch 60/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8639.7783 - mae: 8639.7783
Epoch 61/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8516.2676 - mae: 8516.2676
Epoch 62/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8586.1426 - mae: 8586.1426
Epoch 63/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8553.5879 - mae: 8553.5879
Epoch 64/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8483.1895 - mae: 8483.1895
Epoch 65/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8483.1504 - mae: 8483.1504
Epoch 66/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8420.7559 - mae: 8420.7559
Epoch 67/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8399.4219 - mae: 8399.4219
Epoch 68/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8406.8809 - mae: 8406.8809
Epoch 69/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8276.5322 - mae: 8276.5322
Epoch 70/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8340.0068 - mae: 8340.0068
Epoch 71/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8169.0078 - mae: 8169.0078
Epoch 72/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8244.4189 - mae: 8244.4189
Epoch 73/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8220.0762 - mae: 8220.0762
Epoch 74/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8135.1772 - mae: 8135.1772
Epoch 75/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8206.8896 - mae: 8206.8896
Epoch 76/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8156.1875 - mae: 8156.1875
Epoch 77/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8165.8853 - mae: 8165.8853
Epoch 78/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8102.6211 - mae: 8102.6211
Epoch 79/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8132.0991 - mae: 8132.0991
Epoch 80/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8094.5405 - mae: 8094.5405
Epoch 81/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7935.4414 - mae: 7935.4414
Epoch 82/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8005.8237 - mae: 8005.8237
Epoch 83/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7988.5630 - mae: 7988.5630
Epoch 84/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7921.6655 - mae: 7921.6665
Epoch 85/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8044.1484 - mae: 8044.1484
Epoch 86/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7940.0098 - mae: 7940.0098
Epoch 87/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7966.8228 - mae: 7966.8228
Epoch 88/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7933.3384 - mae: 7933.3384
Epoch 89/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7898.4810 - mae: 7898.4810
Epoch 90/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7892.5420 - mae: 7892.5420
Epoch 91/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7896.0200 - mae: 7896.0200
Epoch 92/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7815.1929 - mae: 7815.1929
Epoch 93/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7810.6943 - mae: 7810.6943
Epoch 94/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7732.2432 - mae: 7732.2432
Epoch 95/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7858.0156 - mae: 7858.0156
Epoch 96/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7881.5088 - mae: 7881.5088
Epoch 97/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7853.8940 - mae: 7853.8940
Epoch 98/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7815.5508 - mae: 7815.5508
Epoch 99/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7780.3657 - mae: 7780.3657
Epoch 100/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7824.2271 - mae: 7824.2271
Epoch 101/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7776.1172 - mae: 7776.1172
Epoch 102/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7732.3540 - mae: 7732.3540
Epoch 103/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7715.8818 - mae: 7715.8818
Epoch 104/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7724.4966 - mae: 7724.4966
Epoch 105/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7726.1694 - mae: 7726.1694
Epoch 106/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7712.3159 - mae: 7712.3159
Epoch 107/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7787.0562 - mae: 7787.0562
Epoch 108/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7760.0181 - mae: 7760.0181
Epoch 109/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7725.1475 - mae: 7725.1475
Epoch 110/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7688.3652 - mae: 7688.3652
Epoch 111/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7657.5430 - mae: 7657.5430
Epoch 112/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7687.7852 - mae: 7687.7852
Epoch 113/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7727.7344 - mae: 7727.7344
Epoch 114/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7693.3052 - mae: 7693.3052
Epoch 115/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7684.8750 - mae: 7684.8750
Epoch 116/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7638.2339 - mae: 7638.2339
Epoch 117/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7696.3755 - mae: 7696.3755
Epoch 118/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7535.1938 - mae: 7535.1938
Epoch 119/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7551.2573 - mae: 7551.2573
Epoch 120/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7623.0220 - mae: 7623.0220
Epoch 121/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7566.9077 - mae: 7566.9077
Epoch 122/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7643.4971 - mae: 7643.4971
Epoch 123/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7546.4331 - mae: 7546.4331
Epoch 124/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7605.3940 - mae: 7605.3940
Epoch 125/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7610.5332 - mae: 7610.5332
Epoch 126/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7517.3164 - mae: 7517.3164
Epoch 127/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7491.1675 - mae: 7491.1675
Epoch 128/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7457.3857 - mae: 7457.3857
Epoch 129/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7503.9419 - mae: 7503.9419
Epoch 130/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7550.6465 - mae: 7550.6465
Epoch 131/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7492.5142 - mae: 7492.5142
Epoch 132/132
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7500.3262 - mae: 7500.3262
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

[I 2026-10-20 13:08:23,648] Trial 21 finished with value: 0.9332549320739447 and parameters: {'epochs': 132, 'batch_size': 30, 'units_layer1': 123, 'units_layer2': 115, 'optimizer': 'rmsprop', 'learning_rate': 0.26314946396439093}. Best is trial 13 with value: 0.9435962770533816.

Epoch 1/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 36761.5898 - mae: 36761.5898
Epoch 2/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 28077.0430 - mae: 28077.0430
Epoch 3/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 23950.2852 - mae: 23950.2852
Epoch 4/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 22554.3281 - mae: 22554.3281
Epoch 5/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20675.8887 - mae: 20675.8887
Epoch 6/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19264.9727 - mae: 19264.9727
Epoch 7/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18552.3145 - mae: 18552.3145
Epoch 8/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17432.1348 - mae: 17432.1367
Epoch 9/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16438.5645 - mae: 16438.5645
Epoch 10/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16263.2158 - mae: 16263.2158
Epoch 11/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15475.5322 - mae: 15475.5322
Epoch 12/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14896.1670 - mae: 14896.1670
Epoch 13/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14686.8770 - mae: 14686.8770
Epoch 14/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14342.1914 - mae: 14342.1934
Epoch 15/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14143.9443 - mae: 14143.9443
Epoch 16/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13633.1436 - mae: 13633.1436
Epoch 17/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13557.7188 - mae: 13557.7188
Epoch 18/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13320.6162 - mae: 13320.6162
Epoch 19/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13192.8271 - mae: 13192.8252
Epoch 20/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13057.0889 - mae: 13057.0889
Epoch 21/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13002.8057 - mae: 13002.8057
Epoch 22/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12585.7197 - mae: 12585.7197
Epoch 23/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12605.9697 - mae: 12605.9697
Epoch 24/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12337.4473 - mae: 12337.4473
Epoch 25/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12177.9258 - mae: 12177.9268
Epoch 26/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11986.0068 - mae: 11986.0068
Epoch 27/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11974.1865 - mae: 11974.1865
Epoch 28/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11601.5225 - mae: 11601.5225
Epoch 29/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 11731.5000 - mae: 11731.5000
Epoch 30/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11433.8154 - mae: 11433.8154
Epoch 31/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11553.2734 - mae: 11553.2734
Epoch 32/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11353.6074 - mae: 11353.6074
Epoch 33/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11325.1367 - mae: 11325.1367
Epoch 34/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11207.6914 - mae: 11207.6914
Epoch 35/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11217.9639 - mae: 11217.9639
Epoch 36/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11288.5371 - mae: 11288.5371
Epoch 37/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11230.3320 - mae: 11230.3320
Epoch 38/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10930.5586 - mae: 10930.5586
Epoch 39/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10836.6250 - mae: 10836.6230
Epoch 40/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10757.6143 - mae: 10757.6143
Epoch 41/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10565.4170 - mae: 10565.4170
Epoch 42/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10883.5928 - mae: 10883.5928
Epoch 43/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10523.4717 - mae: 10523.4717
Epoch 44/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10557.7412 - mae: 10557.7412
Epoch 45/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10227.1826 - mae: 10227.1826
Epoch 46/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10226.8145 - mae: 10226.8145
Epoch 47/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10234.3125 - mae: 10234.3125
Epoch 48/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10110.3311 - mae: 10110.3311
Epoch 49/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9996.0723 - mae: 9996.0723
Epoch 50/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9975.9844 - mae: 9975.9844
Epoch 51/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9892.1162 - mae: 9892.1162
Epoch 52/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9803.9980 - mae: 9803.9980
Epoch 53/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9772.6855 - mae: 9772.6855
Epoch 54/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 9811.5039 - mae: 9811.5039
Epoch 55/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9703.6875 - mae: 9703.6875
Epoch 56/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9576.6201 - mae: 9576.6201
Epoch 57/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9512.0449 - mae: 9512.0449
Epoch 58/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9394.6553 - mae: 9394.6562
Epoch 59/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9403.6338 - mae: 9403.6338
Epoch 60/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9329.1650 - mae: 9329.1650
Epoch 61/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9229.9258 - mae: 9229.9258
Epoch 62/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9218.8887 - mae: 9218.8887
Epoch 63/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9293.4434 - mae: 9293.4434
Epoch 64/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9316.7637 - mae: 9316.7637
Epoch 65/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9279.8623 - mae: 9279.8623
Epoch 66/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9331.7236 - mae: 9331.7236
Epoch 67/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9155.7100 - mae: 9155.7100
Epoch 68/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9119.4561 - mae: 9119.4561
Epoch 69/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9085.8428 - mae: 9085.8428
Epoch 70/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9115.8906 - mae: 9115.8906
Epoch 71/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8973.0361 - mae: 8973.0361
Epoch 72/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8972.7568 - mae: 8972.7568
Epoch 73/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9061.3506 - mae: 9061.3506
Epoch 74/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8974.0742 - mae: 8974.0742
Epoch 75/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 9007.7236 - mae: 9007.7236
Epoch 76/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8858.9688 - mae: 8858.9688
Epoch 77/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8973.3340 - mae: 8973.3340
Epoch 78/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8903.6270 - mae: 8903.6270
Epoch 79/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8821.2002 - mae: 8821.1992
Epoch 80/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8858.0410 - mae: 8858.0410
Epoch 81/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8727.1123 - mae: 8727.1123
Epoch 82/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8687.1514 - mae: 8687.1514
Epoch 83/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8663.5322 - mae: 8663.5322
Epoch 84/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8730.9941 - mae: 8730.9941
Epoch 85/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8744.4316 - mae: 8744.4316
Epoch 86/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8737.2930 - mae: 8737.2920
Epoch 87/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8786.6650 - mae: 8786.6650
Epoch 88/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8739.9541 - mae: 8739.9541
Epoch 89/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8712.8633 - mae: 8712.8633
Epoch 90/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8632.0576 - mae: 8632.0576
Epoch 91/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8624.6729 - mae: 8624.6729
Epoch 92/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8678.8252 - mae: 8678.8252
Epoch 93/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8604.6240 - mae: 8604.6240
Epoch 94/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8560.7627 - mae: 8560.7627
Epoch 95/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8500.5908 - mae: 8500.5908
Epoch 96/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8598.4092 - mae: 8598.4092
Epoch 97/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8415.4307 - mae: 8415.4307
Epoch 98/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8555.7920 - mae: 8555.7920
Epoch 99/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8583.0215 - mae: 8583.0215
Epoch 100/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8481.0859 - mae: 8481.0859
Epoch 101/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8533.6699 - mae: 8533.6699
Epoch 102/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8437.4219 - mae: 8437.4219
Epoch 103/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8405.3457 - mae: 8405.3457
Epoch 104/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8509.7803 - mae: 8509.7803
Epoch 105/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8571.0615 - mae: 8571.0615
Epoch 106/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8525.0381 - mae: 8525.0381
Epoch 107/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8349.0762 - mae: 8349.0762
Epoch 108/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8665.0186 - mae: 8665.0186
Epoch 109/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8415.8301 - mae: 8415.8301
Epoch 110/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8363.1523 - mae: 8363.1523
Epoch 111/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8400.6230 - mae: 8400.6230
Epoch 112/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8390.4648 - mae: 8390.4648
Epoch 113/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8351.7588 - mae: 8351.7588
Epoch 114/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8273.8125 - mae: 8273.8145
Epoch 115/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8333.3125 - mae: 8333.3125
Epoch 116/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8400.4424 - mae: 8400.4424
Epoch 117/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8337.3105 - mae: 8337.3105
Epoch 118/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8405.5615 - mae: 8405.5615
Epoch 119/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8283.6865 - mae: 8283.6865
Epoch 120/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8411.9258 - mae: 8411.9258
Epoch 121/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8472.0010 - mae: 8472.0010
Epoch 122/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8433.1523 - mae: 8433.1523
Epoch 123/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8339.8770 - mae: 8339.8770
Epoch 124/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8400.3848 - mae: 8400.3848
Epoch 125/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8407.5176 - mae: 8407.5176
Epoch 126/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8242.9561 - mae: 8242.9561
Epoch 127/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8304.8311 - mae: 8304.8311
Epoch 128/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8300.6025 - mae: 8300.6025
Epoch 129/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8241.2324 - mae: 8241.2324
Epoch 130/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8337.9531 - mae: 8337.9531
Epoch 131/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8274.5039 - mae: 8274.5039
Epoch 132/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8209.0527 - mae: 8209.0527
Epoch 133/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8273.6221 - mae: 8273.6221
Epoch 134/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8327.6270 - mae: 8327.6270
Epoch 135/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8246.3252 - mae: 8246.3252
Epoch 136/136
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8173.8296 - mae: 8173.8296
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

[I 2026-10-20 13:09:01,079] Trial 22 finished with value: 0.9112069391836117 and parameters: {'epochs': 136, 'batch_size': 43, 'units_layer1': 94, 'units_layer2': 126, 'optimizer': 'rmsprop', 'learning_rate': 0.417356400737723}. Best is trial 13 with value: 0.9435962770533816.

Epoch 1/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 69273.7422 - mae: 69273.7422
Epoch 2/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 21618.9453 - mae: 21618.9453
Epoch 3/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 21070.4688 - mae: 21070.4688
Epoch 4/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20852.8809 - mae: 20852.8809
Epoch 5/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20648.4043 - mae: 20648.4043
Epoch 6/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20397.9414 - mae: 20397.9414
Epoch 7/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20121.1797 - mae: 20121.1797
Epoch 8/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19808.2891 - mae: 19808.2891
Epoch 9/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19434.3164 - mae: 19434.3164
Epoch 10/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19012.3047 - mae: 19012.3047
Epoch 11/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18534.4805 - mae: 18534.4824
Epoch 12/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 18130.6934 - mae: 18130.6934
Epoch 13/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17850.6523 - mae: 17850.6523
Epoch 14/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17636.7734 - mae: 17636.7734
Epoch 15/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17502.3008 - mae: 17502.3008
Epoch 16/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17267.0078 - mae: 17267.0078
Epoch 17/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17206.2441 - mae: 17206.2441
Epoch 18/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17034.5566 - mae: 17034.5566
Epoch 19/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16944.9668 - mae: 16944.9668
Epoch 20/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16842.3867 - mae: 16842.3867
Epoch 21/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16752.3906 - mae: 16752.3906
Epoch 22/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16658.6875 - mae: 16658.6875
Epoch 23/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16635.2363 - mae: 16635.2363
Epoch 24/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16563.3965 - mae: 16563.3965
Epoch 25/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16425.7129 - mae: 16425.7129
Epoch 26/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16371.4668 - mae: 16371.4668
Epoch 27/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16116.5508 - mae: 16116.5508
Epoch 28/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15888.0430 - mae: 15888.0430
Epoch 29/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15642.7969 - mae: 15642.7969
Epoch 30/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15387.2354 - mae: 15387.2354
Epoch 31/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15167.9092 - mae: 15167.9092
Epoch 32/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14952.3086 - mae: 14952.3086
Epoch 33/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14731.5254 - mae: 14731.5254
Epoch 34/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14468.0420 - mae: 14468.0420
Epoch 35/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14333.2695 - mae: 14333.2695
Epoch 36/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14135.0225 - mae: 14135.0225
Epoch 37/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13938.6729 - mae: 13938.6729
Epoch 38/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13814.8281 - mae: 13814.8281
Epoch 39/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13644.5049 - mae: 13644.5049
Epoch 40/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13608.6660 - mae: 13608.6660
Epoch 41/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 13432.9238 - mae: 13432.9238
Epoch 42/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 13327.1846 - mae: 13327.1846
Epoch 43/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 13226.3535 - mae: 13226.3535
Epoch 44/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 13233.2217 - mae: 13233.2217
Epoch 45/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 13053.2500 - mae: 13053.2500
Epoch 46/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 13003.5234 - mae: 13003.5234
Epoch 47/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 12887.0205 - mae: 12887.0205
Epoch 48/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 12861.2822 - mae: 12861.2822
Epoch 49/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 12763.7744 - mae: 12763.7744
Epoch 50/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12689.3613 - mae: 12689.3613
Epoch 51/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 12597.4375 - mae: 12597.4375
Epoch 52/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 12519.4814 - mae: 12519.4814
Epoch 53/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12431.3232 - mae: 12431.3232
Epoch 54/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 12343.1602 - mae: 12343.1602
Epoch 55/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 12332.3340 - mae: 12332.3340
Epoch 56/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 12301.2500 - mae: 12301.2500
Epoch 57/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 12172.6982 - mae: 12172.6982
Epoch 58/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 12160.0107 - mae: 12160.0107
Epoch 59/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12117.2949 - mae: 12117.2949
Epoch 60/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12088.5107 - mae: 12088.5107
Epoch 61/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11933.7451 - mae: 11933.7451
Epoch 62/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 11969.5586 - mae: 11969.5586
Epoch 63/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11881.1523 - mae: 11881.1523
Epoch 64/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11830.7695 - mae: 11830.7695
Epoch 65/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11793.7988 - mae: 11793.7988
Epoch 66/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11806.3604 - mae: 11806.3604
Epoch 67/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11683.7910 - mae: 11683.7910
Epoch 68/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 11737.7471 - mae: 11737.7471
Epoch 69/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 11621.7383 - mae: 11621.7383
Epoch 70/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 11649.4277 - mae: 11649.4287
Epoch 71/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 11512.9141 - mae: 11512.9141
Epoch 72/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 11518.0615 - mae: 11518.0615
Epoch 73/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 11560.2490 - mae: 11560.2490
Epoch 74/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11526.4199 - mae: 11526.4199
Epoch 75/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 11444.8926 - mae: 11444.8926
Epoch 76/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 11378.1318 - mae: 11378.1318
Epoch 77/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 11385.6533 - mae: 11385.6533
Epoch 78/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 11376.3438 - mae: 11376.3438
Epoch 79/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 11267.0420 - mae: 11267.0420
Epoch 80/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 11301.1045 - mae: 11301.1045
Epoch 81/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 11201.0625 - mae: 11201.0625
Epoch 82/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 11258.3613 - mae: 11258.3613
Epoch 83/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 11155.3936 - mae: 11155.3936
Epoch 84/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 11178.9629 - mae: 11178.9629
Epoch 85/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 11130.8633 - mae: 11130.8633
Epoch 86/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 11012.9980 - mae: 11012.9971
Epoch 87/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 11077.1777 - mae: 11077.1777
Epoch 88/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 11029.2461 - mae: 11029.2461
Epoch 89/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 11030.6016 - mae: 11030.6016
Epoch 90/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 10974.1328 - mae: 10974.1328
Epoch 91/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10951.9873 - mae: 10951.9873
Epoch 92/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10894.9961 - mae: 10894.9961
Epoch 93/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11015.3389 - mae: 11015.3389
Epoch 94/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 10943.9268 - mae: 10943.9268
Epoch 95/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10865.0918 - mae: 10865.0918
Epoch 96/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10860.3115 - mae: 10860.3125
Epoch 97/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 10817.8652 - mae: 10817.8652
Epoch 98/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 10816.2461 - mae: 10816.2451
Epoch 99/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 10753.3711 - mae: 10753.3711
Epoch 100/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 10816.0107 - mae: 10816.0107
Epoch 101/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10820.3994 - mae: 10820.3994
Epoch 102/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 10757.4814 - mae: 10757.4814
Epoch 103/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 10523.2188 - mae: 10523.2188
Epoch 104/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 10728.6738 - mae: 10728.6738
Epoch 105/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10557.5068 - mae: 10557.5068
Epoch 106/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10639.0586 - mae: 10639.0586
Epoch 107/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10633.4785 - mae: 10633.4785
Epoch 108/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10557.6045 - mae: 10557.6045
Epoch 109/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10435.5830 - mae: 10435.5830
Epoch 110/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10492.5537 - mae: 10492.5537
Epoch 111/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10488.3750 - mae: 10488.3750
Epoch 112/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 10345.7070 - mae: 10345.7070
Epoch 113/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10314.0664 - mae: 10314.0664
Epoch 114/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10368.8027 - mae: 10368.8027
Epoch 115/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10260.8418 - mae: 10260.8418
Epoch 116/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10223.3945 - mae: 10223.3945
Epoch 117/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10237.2246 - mae: 10237.2246
Epoch 118/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10256.5166 - mae: 10256.5166
Epoch 119/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10210.7041 - mae: 10210.7041
Epoch 120/120
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 10173.1045 - mae: 10173.1045
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

[I 2026-10-20 13:09:34,624] Trial 23 finished with value: 0.9115046431425989 and parameters: {'epochs': 120, 'batch_size': 36, 'units_layer1': 125, 'units_layer2': 115, 'optimizer': 'rmsprop', 'learning_rate': 0.04006823758767663}. Best is trial 13 with value: 0.9435962770533816.

Epoch 1/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 30303.1133 - mae: 30303.1133
Epoch 2/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 21498.9375 - mae: 21498.9375
Epoch 3/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 21278.0371 - mae: 21278.0371
Epoch 4/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 21095.8828 - mae: 21095.8828
Epoch 5/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 20571.6328 - mae: 20571.6328
Epoch 6/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 21361.6348 - mae: 21361.6348
Epoch 7/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20065.8223 - mae: 20065.8223
Epoch 8/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 20717.0391 - mae: 20717.0391
Epoch 9/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20369.3691 - mae: 20369.3691
Epoch 10/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 19413.5898 - mae: 19413.5898
Epoch 11/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 18734.5488 - mae: 18734.5488
Epoch 12/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17707.9336 - mae: 17707.9336
Epoch 13/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 17190.0957 - mae: 17190.0957
Epoch 14/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16339.7236 - mae: 16339.7236
Epoch 15/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 15711.3359 - mae: 15711.3359
Epoch 16/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 14781.0410 - mae: 14781.0410
Epoch 17/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14307.0098 - mae: 14307.0098
Epoch 18/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13844.1104 - mae: 13844.1104
Epoch 19/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 13421.6875 - mae: 13421.6875
Epoch 20/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 13163.9980 - mae: 13163.9980
Epoch 21/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 12901.4707 - mae: 12901.4707
Epoch 22/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 12382.0303 - mae: 12382.0303
Epoch 23/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12169.6084 - mae: 12169.6084
Epoch 24/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11682.0791 - mae: 11682.0791
Epoch 25/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11422.6885 - mae: 11422.6885
Epoch 26/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 10760.7627 - mae: 10760.7627
Epoch 27/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 11140.5547 - mae: 11140.5547
Epoch 28/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 10655.8975 - mae: 10655.8975
Epoch 29/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 10633.4385 - mae: 10633.4385
Epoch 30/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10355.9727 - mae: 10355.9727
Epoch 31/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 10196.4277 - mae: 10196.4277
Epoch 32/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 10059.8467 - mae: 10059.8467
Epoch 33/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9697.3770 - mae: 9697.3770
Epoch 34/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9522.0430 - mae: 9522.0430
Epoch 35/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9587.9355 - mae: 9587.9355
Epoch 36/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 9731.0078 - mae: 9731.0078
Epoch 37/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 9515.6553 - mae: 9515.6553
Epoch 38/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 9314.5752 - mae: 9314.5752
Epoch 39/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 9024.4121 - mae: 9024.4121
Epoch 40/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 9224.4639 - mae: 9224.4639
Epoch 41/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8989.2148 - mae: 8989.2148
Epoch 42/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8906.6328 - mae: 8906.6328
Epoch 43/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8708.1602 - mae: 8708.1602
Epoch 44/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8800.7627 - mae: 8800.7627
Epoch 45/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8523.6182 - mae: 8523.6162
Epoch 46/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8517.8340 - mae: 8517.8340
Epoch 47/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8458.3271 - mae: 8458.3271
Epoch 48/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8437.4092 - mae: 8437.4092
Epoch 49/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8375.3174 - mae: 8375.3174
Epoch 50/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8380.5439 - mae: 8380.5439
Epoch 51/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8525.6328 - mae: 8525.6328
Epoch 52/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8036.5503 - mae: 8036.5503
Epoch 53/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8083.0361 - mae: 8083.0361
Epoch 54/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8450.8740 - mae: 8450.8740
Epoch 55/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7978.6250 - mae: 7978.6250
Epoch 56/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7708.3867 - mae: 7708.3867
Epoch 57/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8020.0410 - mae: 8020.0410
Epoch 58/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7876.8018 - mae: 7876.8018
Epoch 59/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7772.4004 - mae: 7772.4004
Epoch 60/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7506.1523 - mae: 7506.1523
Epoch 61/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7593.3975 - mae: 7593.3975
Epoch 62/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7688.3994 - mae: 7688.3994
Epoch 63/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7676.0913 - mae: 7676.0913
Epoch 64/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7566.1719 - mae: 7566.1719
Epoch 65/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7525.2759 - mae: 7525.2759
Epoch 66/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7888.8286 - mae: 7888.8286
Epoch 67/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7280.9443 - mae: 7280.9443
Epoch 68/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7418.3574 - mae: 7418.3574
Epoch 69/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7383.6768 - mae: 7383.6768
Epoch 70/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7234.5957 - mae: 7234.5957
Epoch 71/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7356.5698 - mae: 7356.5698
Epoch 72/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7318.6016 - mae: 7318.6016
Epoch 73/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7256.7505 - mae: 7256.7505
Epoch 74/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7261.3071 - mae: 7261.3071
Epoch 75/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7267.2480 - mae: 7267.2480
Epoch 76/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6999.6006 - mae: 6999.6006
Epoch 77/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7307.1733 - mae: 7307.1733
Epoch 78/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7267.8584 - mae: 7267.8584
Epoch 79/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7089.7349 - mae: 7089.7349
Epoch 80/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7244.7314 - mae: 7244.7314
Epoch 81/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7242.7466 - mae: 7242.7451
Epoch 82/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7215.4014 - mae: 7215.4014
Epoch 83/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6900.9624 - mae: 6900.9624
Epoch 84/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6887.2109 - mae: 6887.2109
Epoch 85/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6871.3789 - mae: 6871.3789
Epoch 86/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6963.9648 - mae: 6963.9648
Epoch 87/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6888.8242 - mae: 6888.8242
Epoch 88/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6856.6255 - mae: 6856.6255
Epoch 89/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6886.7310 - mae: 6886.7310
Epoch 90/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6835.7798 - mae: 6835.7798
Epoch 91/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6940.1353 - mae: 6940.1353
Epoch 92/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6780.4224 - mae: 6780.4224
Epoch 93/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6741.5796 - mae: 6741.5796
Epoch 94/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6648.7803 - mae: 6648.7803
Epoch 95/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6518.4966 - mae: 6518.4966
Epoch 96/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6608.4053 - mae: 6608.4053
Epoch 97/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6754.3652 - mae: 6754.3652
Epoch 98/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6886.2964 - mae: 6886.2964
Epoch 99/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6576.3682 - mae: 6576.3682
Epoch 100/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6712.4067 - mae: 6712.4067
Epoch 101/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6562.1045 - mae: 6562.1045
Epoch 102/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6518.4321 - mae: 6518.4321
Epoch 103/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6718.2666 - mae: 6718.2666
Epoch 104/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6469.4302 - mae: 6469.4302
Epoch 105/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6531.2495 - mae: 6531.2495
Epoch 106/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6523.0864 - mae: 6523.0864
Epoch 107/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6471.6299 - mae: 6471.6299
Epoch 108/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6465.2637 - mae: 6465.2637
Epoch 109/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6544.2656 - mae: 6544.2656
Epoch 110/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6457.4507 - mae: 6457.4507
Epoch 111/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6339.9067 - mae: 6339.9067
Epoch 112/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6424.4844 - mae: 6424.4844
Epoch 113/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6532.1733 - mae: 6532.1733
Epoch 114/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6396.6279 - mae: 6396.6279
Epoch 115/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6452.8301 - mae: 6452.8301
Epoch 116/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6556.2734 - mae: 6556.2734
Epoch 117/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6233.4424 - mae: 6233.4424
Epoch 118/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6341.2954 - mae: 6341.2954
Epoch 119/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6228.1797 - mae: 6228.1797
Epoch 120/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6271.7373 - mae: 6271.7373
Epoch 121/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6413.6074 - mae: 6413.6074
Epoch 122/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6214.2695 - mae: 6214.2695
Epoch 123/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6460.6084 - mae: 6460.6084
Epoch 124/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6325.5366 - mae: 6325.5366
Epoch 125/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6384.8921 - mae: 6384.8921
Epoch 126/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6154.5063 - mae: 6154.5063
Epoch 127/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6127.2061 - mae: 6127.2061
Epoch 128/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6253.0435 - mae: 6253.0435
Epoch 129/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6243.5098 - mae: 6243.5098
Epoch 130/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6066.3911 - mae: 6066.3911
Epoch 131/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6119.4487 - mae: 6119.4487
Epoch 132/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6244.0659 - mae: 6244.0659
Epoch 133/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6217.2715 - mae: 6217.2715
Epoch 134/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6214.6045 - mae: 6214.6045
Epoch 135/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6042.3921 - mae: 6042.3921
Epoch 136/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6156.1401 - mae: 6156.1401
Epoch 137/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6085.4048 - mae: 6085.4043
Epoch 138/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 5960.4907 - mae: 5960.4907
Epoch 139/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6065.8813 - mae: 6065.8813
Epoch 140/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6048.7920 - mae: 6048.7920
Epoch 141/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6163.7563 - mae: 6163.7563
Epoch 142/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6175.0708 - mae: 6175.0708
Epoch 143/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6079.2686 - mae: 6079.2686
Epoch 144/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6100.9565 - mae: 6100.9565
Epoch 145/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 5906.2466 - mae: 5906.2466
Epoch 146/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6050.9331 - mae: 6050.9331
Epoch 147/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6134.0825 - mae: 6134.0825
Epoch 148/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 5918.1626 - mae: 5918.1626
Epoch 149/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 5996.9185 - mae: 5996.9185
Epoch 150/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6199.9849 - mae: 6199.9849
Epoch 151/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6068.5078 - mae: 6068.5078
Epoch 152/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 5794.0195 - mae: 5794.0195
Epoch 153/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6139.0088 - mae: 6139.0088
Epoch 154/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 5956.0659 - mae: 5956.0659
Epoch 155/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 5931.1670 - mae: 5931.1670
Epoch 156/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 5744.6704 - mae: 5744.6704
Epoch 157/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 5708.9058 - mae: 5708.9058
Epoch 158/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 5844.7930 - mae: 5844.7930
Epoch 159/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 5994.3696 - mae: 5994.3696
Epoch 160/160
185/185 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 5772.9775 - mae: 5772.9780
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

[I 2026-10-20 13:10:21,838] Trial 24 finished with value: 0.9418194705390103 and parameters: {'epochs': 160, 'batch_size': 29, 'units_layer1': 117, 'units_layer2': 108, 'optimizer': 'adam', 'learning_rate': 0.19115463025921536}. Best is trial 13 with value: 0.9435962770533816.

Epoch 1/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 31793.2930 - mae: 31793.2930
Epoch 2/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 21130.4766 - mae: 21130.4805
Epoch 3/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20716.4082 - mae: 20716.4082
Epoch 4/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20402.3945 - mae: 20402.3945
Epoch 5/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20011.6797 - mae: 20011.6797
Epoch 6/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20429.5430 - mae: 20429.5430
Epoch 7/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20293.0039 - mae: 20293.0039
Epoch 8/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20096.9355 - mae: 20096.9355
Epoch 9/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19781.6172 - mae: 19781.6172
Epoch 10/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19739.9648 - mae: 19739.9648
Epoch 11/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 19792.2539 - mae: 19792.2539
Epoch 12/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19801.4746 - mae: 19801.4766
Epoch 13/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 19611.0156 - mae: 19611.0156
Epoch 14/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19403.5273 - mae: 19403.5273
Epoch 15/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19487.6953 - mae: 19487.6953
Epoch 16/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19017.0566 - mae: 19017.0566
Epoch 17/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18251.6660 - mae: 18251.6660
Epoch 18/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17745.4453 - mae: 17745.4453
Epoch 19/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17620.4160 - mae: 17620.4160
Epoch 20/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 16720.8438 - mae: 16720.8438
Epoch 21/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 16047.1299 - mae: 16047.1299
Epoch 22/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14995.5957 - mae: 14995.5957
Epoch 23/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15112.8926 - mae: 15112.8926
Epoch 24/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 14200.8213 - mae: 14200.8213
Epoch 25/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13764.5000 - mae: 13764.5000
Epoch 26/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13655.1553 - mae: 13655.1553
Epoch 27/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 12825.4785 - mae: 12825.4785
Epoch 28/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12382.2168 - mae: 12382.2168
Epoch 29/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12637.0283 - mae: 12637.0283
Epoch 30/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11730.9453 - mae: 11730.9453
Epoch 31/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11918.9834 - mae: 11918.9834
Epoch 32/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11608.5596 - mae: 11608.5596
Epoch 33/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 11519.2793 - mae: 11519.2793
Epoch 34/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 11226.9473 - mae: 11226.9473
Epoch 35/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11077.0791 - mae: 11077.0791
Epoch 36/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10961.5732 - mae: 10961.5732
Epoch 37/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11245.1201 - mae: 11245.1201
Epoch 38/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 10820.3203 - mae: 10820.3203
Epoch 39/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10891.8867 - mae: 10891.8867
Epoch 40/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10287.3896 - mae: 10287.3896
Epoch 41/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10973.8242 - mae: 10973.8242
Epoch 42/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10438.3213 - mae: 10438.3213
Epoch 43/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10219.2148 - mae: 10219.2148
Epoch 44/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 10290.4795 - mae: 10290.4795
Epoch 45/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9981.8682 - mae: 9981.8682
Epoch 46/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9986.9307 - mae: 9986.9307
Epoch 47/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 10245.7920 - mae: 10245.7920
Epoch 48/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10057.1172 - mae: 10057.1172
Epoch 49/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9825.3779 - mae: 9825.3779
Epoch 50/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9420.7822 - mae: 9420.7822
Epoch 51/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 9464.5830 - mae: 9464.5830
Epoch 52/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9559.3662 - mae: 9559.3662
Epoch 53/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9445.1816 - mae: 9445.1816
Epoch 54/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9296.9365 - mae: 9296.9365
Epoch 55/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8997.4385 - mae: 8997.4385
Epoch 56/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 9568.8447 - mae: 9568.8447
Epoch 57/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9032.2227 - mae: 9032.2227
Epoch 58/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 9006.0635 - mae: 9006.0635
Epoch 59/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 9238.8701 - mae: 9238.8691
Epoch 60/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8921.7666 - mae: 8921.7666
Epoch 61/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8825.0918 - mae: 8825.0918
Epoch 62/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8839.9443 - mae: 8839.9443
Epoch 63/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 9014.6924 - mae: 9014.6924
Epoch 64/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8998.9443 - mae: 8998.9443
Epoch 65/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8627.7490 - mae: 8627.7490
Epoch 66/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8455.9717 - mae: 8455.9717
Epoch 67/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8484.6631 - mae: 8484.6631
Epoch 68/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8525.6738 - mae: 8525.6738
Epoch 69/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8322.1709 - mae: 8322.1709
Epoch 70/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8211.8047 - mae: 8211.8047
Epoch 71/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7925.6855 - mae: 7925.6855
Epoch 72/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8241.5703 - mae: 8241.5703
Epoch 73/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8158.1597 - mae: 8158.1597
Epoch 74/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7953.7627 - mae: 7953.7627
Epoch 75/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7872.4019 - mae: 7872.4019
Epoch 76/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7941.4922 - mae: 7941.4922
Epoch 77/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7804.5361 - mae: 7804.5361
Epoch 78/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7862.4712 - mae: 7862.4712
Epoch 79/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7645.4482 - mae: 7645.4482
Epoch 80/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7800.9277 - mae: 7800.9277
Epoch 81/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7822.1343 - mae: 7822.1343
Epoch 82/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7801.7427 - mae: 7801.7427
Epoch 83/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7617.7773 - mae: 7617.7773
Epoch 84/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7405.1689 - mae: 7405.1689
Epoch 85/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7303.2178 - mae: 7303.2178
Epoch 86/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7380.7607 - mae: 7380.7607
Epoch 87/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7392.0200 - mae: 7392.0200
Epoch 88/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7182.2231 - mae: 7182.2231
Epoch 89/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7262.6338 - mae: 7262.6338
Epoch 90/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7223.7178 - mae: 7223.7178
Epoch 91/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7129.5288 - mae: 7129.5288
Epoch 92/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7081.7744 - mae: 7081.7744
Epoch 93/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6945.1855 - mae: 6945.1855
Epoch 94/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7064.8345 - mae: 7064.8345
Epoch 95/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6847.8491 - mae: 6847.8491
Epoch 96/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6966.5151 - mae: 6966.5151
Epoch 97/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6925.0840 - mae: 6925.0840
Epoch 98/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7073.6431 - mae: 7073.6431
Epoch 99/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7044.3501 - mae: 7044.3511
Epoch 100/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6883.2378 - mae: 6883.2378
Epoch 101/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6789.4536 - mae: 6789.4536
Epoch 102/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6819.6187 - mae: 6819.6187
Epoch 103/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6798.1851 - mae: 6798.1851
Epoch 104/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6881.9644 - mae: 6881.9644
Epoch 105/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6618.8892 - mae: 6618.8892
Epoch 106/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6695.8042 - mae: 6695.8042
Epoch 107/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6716.4316 - mae: 6716.4316
Epoch 108/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6740.6973 - mae: 6740.6973
Epoch 109/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6636.0083 - mae: 6636.0083
Epoch 110/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6453.7432 - mae: 6453.7432
Epoch 111/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6335.9468 - mae: 6335.9468
Epoch 112/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6454.4487 - mae: 6454.4478
Epoch 113/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6427.3101 - mae: 6427.3101
Epoch 114/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6513.4819 - mae: 6513.4819
Epoch 115/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6442.7695 - mae: 6442.7695
Epoch 116/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6387.7202 - mae: 6387.7202
Epoch 117/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6299.6147 - mae: 6299.6147
Epoch 118/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6181.8721 - mae: 6181.8721
Epoch 119/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6321.1465 - mae: 6321.1465
Epoch 120/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6391.3452 - mae: 6391.3452
Epoch 121/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6123.5889 - mae: 6123.5889
Epoch 122/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6075.2495 - mae: 6075.2495
Epoch 123/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6367.0371 - mae: 6367.0371
Epoch 124/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6045.2261 - mae: 6045.2261
Epoch 125/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6116.3213 - mae: 6116.3213
Epoch 126/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6061.9722 - mae: 6061.9722
Epoch 127/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 5954.4995 - mae: 5954.4995
Epoch 128/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5999.9150 - mae: 5999.9150
Epoch 129/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 5895.3701 - mae: 5895.3701
Epoch 130/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6099.6304 - mae: 6099.6304
Epoch 131/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5915.2671 - mae: 5915.2666
Epoch 132/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5806.4414 - mae: 5806.4414
Epoch 133/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5862.5474 - mae: 5862.5474
Epoch 134/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5960.4785 - mae: 5960.4785
Epoch 135/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5937.4019 - mae: 5937.4019
Epoch 136/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5952.2827 - mae: 5952.2827
Epoch 137/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 5829.4175 - mae: 5829.4175
Epoch 138/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5843.4956 - mae: 5843.4956
Epoch 139/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5825.9531 - mae: 5825.9531
Epoch 140/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5878.2461 - mae: 5878.2461
Epoch 141/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5926.7915 - mae: 5926.7915
Epoch 142/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 5939.5073 - mae: 5939.5073
Epoch 143/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 5740.0498 - mae: 5740.0493
Epoch 144/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 5938.2754 - mae: 5938.2754
Epoch 145/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5845.4668 - mae: 5845.4668
Epoch 146/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5563.7446 - mae: 5563.7446
Epoch 147/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 5679.2095 - mae: 5679.2095
Epoch 148/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 5669.5537 - mae: 5669.5537
Epoch 149/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 5526.4014 - mae: 5526.4014
Epoch 150/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 5636.7227 - mae: 5636.7231
Epoch 151/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5567.5264 - mae: 5567.5264
Epoch 152/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5663.4570 - mae: 5663.4570
Epoch 153/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5560.9600 - mae: 5560.9600
Epoch 154/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5535.5000 - mae: 5535.5000
Epoch 155/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5904.1177 - mae: 5904.1177
Epoch 156/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5436.0991 - mae: 5436.0991
Epoch 157/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5807.8638 - mae: 5807.8638
Epoch 158/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5554.0088 - mae: 5554.0088
Epoch 159/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5393.3716 - mae: 5393.3716
Epoch 160/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5365.8384 - mae: 5365.8384
Epoch 161/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5373.7725 - mae: 5373.7725
Epoch 162/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5519.6631 - mae: 5519.6631
Epoch 163/163
199/199 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5578.5854 - mae: 5578.5854
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

[I 2026-10-20 13:11:18,909] Trial 25 finished with value: 0.9431995051220691 and parameters: {'epochs': 163, 'batch_size': 27, 'units_layer1': 98, 'units_layer2': 106, 'optimizer': 'adam', 'learning_rate': 0.1143041620626616}. Best is trial 13 with value: 0.9435962770533816.

Epoch 1/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 29733.7578 - mae: 29733.7578
Epoch 2/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 21739.8438 - mae: 21739.8438
Epoch 3/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 21133.5098 - mae: 21133.5098
Epoch 4/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20461.8359 - mae: 20461.8359
Epoch 5/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20326.2637 - mae: 20326.2637
Epoch 6/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20305.2461 - mae: 20305.2461
Epoch 7/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 20271.5273 - mae: 20271.5273
Epoch 8/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 20111.4512 - mae: 20111.4512
Epoch 9/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19916.0293 - mae: 19916.0293
Epoch 10/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19903.9004 - mae: 19903.9004
Epoch 11/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19872.7793 - mae: 19872.7793
Epoch 12/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19952.9473 - mae: 19952.9473
Epoch 13/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19777.5508 - mae: 19777.5508
Epoch 14/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18909.0312 - mae: 18909.0312
Epoch 15/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18272.1172 - mae: 18272.1172
Epoch 16/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17697.2266 - mae: 17697.2266
Epoch 17/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16604.6309 - mae: 16604.6309
Epoch 18/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16010.5713 - mae: 16010.5713
Epoch 19/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15562.7051 - mae: 15562.7051
Epoch 20/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14728.3848 - mae: 14728.3848
Epoch 21/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 14305.0049 - mae: 14305.0049
Epoch 22/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13532.9033 - mae: 13532.9033
Epoch 23/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12977.6621 - mae: 12977.6621
Epoch 24/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12846.7666 - mae: 12846.7666
Epoch 25/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 12653.9541 - mae: 12653.9541
Epoch 26/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12053.2217 - mae: 12053.2217
Epoch 27/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 12206.8643 - mae: 12206.8643
Epoch 28/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 12087.5117 - mae: 12087.5117
Epoch 29/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12063.8076 - mae: 12063.8076
Epoch 30/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11694.5283 - mae: 11694.5283
Epoch 31/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11496.0527 - mae: 11496.0527
Epoch 32/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11495.9121 - mae: 11495.9121
Epoch 33/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 11483.8779 - mae: 11483.8779
Epoch 34/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11380.1963 - mae: 11380.1963
Epoch 35/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11137.8389 - mae: 11137.8389
Epoch 36/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 11386.6162 - mae: 11386.6162
Epoch 37/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11015.1602 - mae: 11015.1611
Epoch 38/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10874.5381 - mae: 10874.5381
Epoch 39/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10704.0645 - mae: 10704.0645
Epoch 40/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 10744.0557 - mae: 10744.0557
Epoch 41/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11055.1270 - mae: 11055.1270
Epoch 42/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 10439.3545 - mae: 10439.3545
Epoch 43/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10222.1689 - mae: 10222.1689
Epoch 44/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10261.4307 - mae: 10261.4307
Epoch 45/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10531.0537 - mae: 10531.0537
Epoch 46/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 10093.7744 - mae: 10093.7734
Epoch 47/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9793.5293 - mae: 9793.5293
Epoch 48/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 9934.6797 - mae: 9934.6797
Epoch 49/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9913.3145 - mae: 9913.3154
Epoch 50/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9407.5645 - mae: 9407.5645
Epoch 51/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9474.5654 - mae: 9474.5654
Epoch 52/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9396.2686 - mae: 9396.2686
Epoch 53/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9098.1338 - mae: 9098.1338
Epoch 54/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9015.9766 - mae: 9015.9766
Epoch 55/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8914.6465 - mae: 8914.6465
Epoch 56/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8759.2139 - mae: 8759.2139
Epoch 57/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8740.5879 - mae: 8740.5879
Epoch 58/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8454.1006 - mae: 8454.1006
Epoch 59/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8552.5215 - mae: 8552.5215
Epoch 60/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8743.7188 - mae: 8743.7188
Epoch 61/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8596.9619 - mae: 8596.9619
Epoch 62/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8297.6719 - mae: 8297.6719
Epoch 63/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8399.3770 - mae: 8399.3770
Epoch 64/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8351.3955 - mae: 8351.3955
Epoch 65/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8218.1855 - mae: 8218.1855
Epoch 66/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8080.8735 - mae: 8080.8735
Epoch 67/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8035.8784 - mae: 8035.8784
Epoch 68/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7800.7808 - mae: 7800.7808
Epoch 69/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7878.5474 - mae: 7878.5474
Epoch 70/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7586.7393 - mae: 7586.7393
Epoch 71/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7815.4492 - mae: 7815.4492
Epoch 72/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7737.1841 - mae: 7737.1841
Epoch 73/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7576.7056 - mae: 7576.7056
Epoch 74/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7572.1792 - mae: 7572.1792
Epoch 75/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7292.2246 - mae: 7292.2246
Epoch 76/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7264.4688 - mae: 7264.4688
Epoch 77/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7498.3643 - mae: 7498.3643
Epoch 78/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7218.8789 - mae: 7218.8789
Epoch 79/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7570.9546 - mae: 7570.9546
Epoch 80/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7323.9180 - mae: 7323.9180
Epoch 81/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7359.0122 - mae: 7359.0122
Epoch 82/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7374.6943 - mae: 7374.6943
Epoch 83/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7118.7168 - mae: 7118.7168
Epoch 84/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7097.2886 - mae: 7097.2886
Epoch 85/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7145.3027 - mae: 7145.3027
Epoch 86/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7190.4668 - mae: 7190.4668
Epoch 87/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6900.9546 - mae: 6900.9546
Epoch 88/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6944.9976 - mae: 6944.9976
Epoch 89/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7020.2075 - mae: 7020.2070
Epoch 90/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7014.4097 - mae: 7014.4097
Epoch 91/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7028.0127 - mae: 7028.0127
Epoch 92/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6882.5239 - mae: 6882.5239
Epoch 93/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6848.1182 - mae: 6848.1182
Epoch 94/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6787.2891 - mae: 6787.2886
Epoch 95/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7030.8105 - mae: 7030.8105
Epoch 96/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6555.2578 - mae: 6555.2578
Epoch 97/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6936.1733 - mae: 6936.1733
Epoch 98/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6904.6577 - mae: 6904.6577
Epoch 99/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6717.5156 - mae: 6717.5161
Epoch 100/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6824.8794 - mae: 6824.8794
Epoch 101/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6669.6982 - mae: 6669.6982
Epoch 102/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6857.2764 - mae: 6857.2783
Epoch 103/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6476.9653 - mae: 6476.9653
Epoch 104/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6572.8398 - mae: 6572.8398
Epoch 105/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6691.4116 - mae: 6691.4116
Epoch 106/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6529.7139 - mae: 6529.7139
Epoch 107/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6595.2954 - mae: 6595.2954
Epoch 108/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6504.1001 - mae: 6504.1001
Epoch 109/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6728.8394 - mae: 6728.8394
Epoch 110/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6471.5269 - mae: 6471.5269
Epoch 111/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6782.1680 - mae: 6782.1680
Epoch 112/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6473.0459 - mae: 6473.0459
Epoch 113/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6461.6626 - mae: 6461.6626
Epoch 114/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6559.5752 - mae: 6559.5762
Epoch 115/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6403.5317 - mae: 6403.5317
Epoch 116/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6375.1733 - mae: 6375.1733
Epoch 117/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6510.5825 - mae: 6510.5825
Epoch 118/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6524.7100 - mae: 6524.7100
Epoch 119/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6458.8145 - mae: 6458.8145
Epoch 120/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6230.4731 - mae: 6230.4731
Epoch 121/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6268.2529 - mae: 6268.2529
Epoch 122/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6397.6440 - mae: 6397.6440
Epoch 123/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6278.6548 - mae: 6278.6548
Epoch 124/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6453.1831 - mae: 6453.1831
Epoch 125/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6285.5923 - mae: 6285.5923
Epoch 126/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6275.8506 - mae: 6275.8506
Epoch 127/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6230.9424 - mae: 6230.9424
Epoch 128/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6258.4199 - mae: 6258.4199
Epoch 129/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6202.8354 - mae: 6202.8354
Epoch 130/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6154.8394 - mae: 6154.8394
Epoch 131/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6303.2192 - mae: 6303.2192
Epoch 132/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6345.1812 - mae: 6345.1812
Epoch 133/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6156.0020 - mae: 6156.0020
Epoch 134/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6257.6030 - mae: 6257.6030
Epoch 135/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6170.0479 - mae: 6170.0479
Epoch 136/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6417.5586 - mae: 6417.5586
Epoch 137/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6333.0200 - mae: 6333.0200
Epoch 138/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6205.4590 - mae: 6205.4590
Epoch 139/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6071.6338 - mae: 6071.6338
Epoch 140/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6174.9180 - mae: 6174.9185
Epoch 141/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6135.5605 - mae: 6135.5605
Epoch 142/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6044.1499 - mae: 6044.1504
Epoch 143/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6076.6812 - mae: 6076.6812
Epoch 144/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6236.5518 - mae: 6236.5518
Epoch 145/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6016.2910 - mae: 6016.2910
Epoch 146/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6161.1069 - mae: 6161.1069
Epoch 147/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6035.0166 - mae: 6035.0166
Epoch 148/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6042.6729 - mae: 6042.6729
Epoch 149/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 5764.5488 - mae: 5764.5488
Epoch 150/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5958.8403 - mae: 5958.8403
Epoch 151/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6063.4717 - mae: 6063.4727
Epoch 152/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5921.4116 - mae: 5921.4116
Epoch 153/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6034.0137 - mae: 6034.0137
Epoch 154/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6099.4888 - mae: 6099.4893
Epoch 155/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6100.4858 - mae: 6100.4858
Epoch 156/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5998.5601 - mae: 5998.5601
Epoch 157/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5820.7437 - mae: 5820.7427
Epoch 158/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6004.2915 - mae: 6004.2915
Epoch 159/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 5795.6270 - mae: 5795.6270
Epoch 160/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 5974.9609 - mae: 5974.9609
Epoch 161/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6049.6606 - mae: 6049.6606
Epoch 162/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5758.7964 - mae: 5758.7964
Epoch 163/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5942.0732 - mae: 5942.0732
Epoch 164/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5977.7788 - mae: 5977.7788
Epoch 165/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5958.4619 - mae: 5958.4619
Epoch 166/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5748.2710 - mae: 5748.2710
Epoch 167/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6116.1318 - mae: 6116.1318
Epoch 168/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5766.0479 - mae: 5766.0479
Epoch 169/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 5953.7378 - mae: 5953.7368
Epoch 170/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5903.8833 - mae: 5903.8833
Epoch 171/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5690.9102 - mae: 5690.9102
Epoch 172/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5752.6001 - mae: 5752.6001
Epoch 173/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5870.9453 - mae: 5870.9453
Epoch 174/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5675.6172 - mae: 5675.6172
Epoch 175/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 5758.5728 - mae: 5758.5737
Epoch 176/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 5716.7388 - mae: 5716.7383
Epoch 177/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5623.7412 - mae: 5623.7412
Epoch 178/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5764.6641 - mae: 5764.6641
Epoch 179/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5712.1284 - mae: 5712.1284
Epoch 180/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5782.9419 - mae: 5782.9419
Epoch 181/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 5598.0488 - mae: 5598.0488
Epoch 182/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5592.2734 - mae: 5592.2734
Epoch 183/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5649.7788 - mae: 5649.7788
Epoch 184/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5647.2241 - mae: 5647.2241
Epoch 185/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5611.0444 - mae: 5611.0444
Epoch 186/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 5640.0024 - mae: 5640.0024
Epoch 187/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 5565.2109 - mae: 5565.2109
Epoch 188/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 5775.6562 - mae: 5775.6562
Epoch 189/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5802.6899 - mae: 5802.6899
Epoch 190/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 5685.9575 - mae: 5685.9575
Epoch 191/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 5549.2954 - mae: 5549.2954
Epoch 192/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 5724.0635 - mae: 5724.0635
Epoch 193/193
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 5883.1567 - mae: 5883.1562
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

[I 2026-10-20 13:12:47,839] Trial 26 finished with value: 0.9399138480495194 and parameters: {'epochs': 193, 'batch_size': 21, 'units_layer1': 91, 'units_layer2': 106, 'optimizer': 'adam', 'learning_rate': 0.11972250640005075}. Best is trial 13 with value: 0.9435962770533816.

Epoch 1/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 29990.1484 - mae: 29990.1484
Epoch 2/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 21224.5195 - mae: 21224.5195
Epoch 3/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19591.4512 - mae: 19591.4512
Epoch 4/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 18663.4492 - mae: 18663.4492
Epoch 5/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16396.5859 - mae: 16396.5859
Epoch 6/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15748.3408 - mae: 15748.3408
Epoch 7/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15230.6797 - mae: 15230.6797
Epoch 8/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15249.4980 - mae: 15249.4980
Epoch 9/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14322.4453 - mae: 14322.4453
Epoch 10/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 13824.8330 - mae: 13824.8330
Epoch 11/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14049.3711 - mae: 14049.3711
Epoch 12/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13232.3662 - mae: 13232.3662
Epoch 13/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14431.9854 - mae: 14431.9834
Epoch 14/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13759.6846 - mae: 13759.6846
Epoch 15/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13057.2588 - mae: 13057.2588
Epoch 16/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12913.0244 - mae: 12913.0244
Epoch 17/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12324.4473 - mae: 12324.4473
Epoch 18/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12866.1846 - mae: 12866.1846
Epoch 19/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12745.5410 - mae: 12745.5410
Epoch 20/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12344.6133 - mae: 12344.6133
Epoch 21/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11882.4551 - mae: 11882.4551
Epoch 22/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12018.5967 - mae: 12018.5967
Epoch 23/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11799.5566 - mae: 11799.5566
Epoch 24/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11974.1025 - mae: 11974.1025
Epoch 25/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11313.9443 - mae: 11313.9443
Epoch 26/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11419.9736 - mae: 11419.9736
Epoch 27/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11382.8027 - mae: 11382.8027
Epoch 28/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11412.9492 - mae: 11412.9492
Epoch 29/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11624.4590 - mae: 11624.4590
Epoch 30/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11167.2412 - mae: 11167.2412
Epoch 31/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11547.4668 - mae: 11547.4668
Epoch 32/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11116.4893 - mae: 11116.4893
Epoch 33/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 11551.1318 - mae: 11551.1318
Epoch 34/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11187.9922 - mae: 11187.9922
Epoch 35/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11448.1738 - mae: 11448.1738
Epoch 36/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 11705.2852 - mae: 11705.2852
Epoch 37/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 10598.5449 - mae: 10598.5449
Epoch 38/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 10724.6572 - mae: 10724.6572
Epoch 39/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 10595.4658 - mae: 10595.4658
Epoch 40/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10641.2754 - mae: 10641.2754
Epoch 41/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 10861.7256 - mae: 10861.7256
Epoch 42/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10943.6885 - mae: 10943.6885
Epoch 43/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10899.5840 - mae: 10899.5840
Epoch 44/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11134.9336 - mae: 11134.9336
Epoch 45/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10565.7666 - mae: 10565.7666
Epoch 46/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10892.9619 - mae: 10892.9619
Epoch 47/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 10967.5547 - mae: 10967.5547
Epoch 48/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 10374.3525 - mae: 10374.3525
Epoch 49/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11090.5186 - mae: 11090.5186
Epoch 50/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10789.4375 - mae: 10789.4375
Epoch 51/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10548.5957 - mae: 10548.5957
Epoch 52/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10775.8076 - mae: 10775.8076
Epoch 53/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10491.9551 - mae: 10491.9551
Epoch 54/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10902.8574 - mae: 10902.8574
Epoch 55/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10832.2930 - mae: 10832.2930
Epoch 56/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10793.4873 - mae: 10793.4873
Epoch 57/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10871.7891 - mae: 10871.7891
Epoch 58/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 10782.3516 - mae: 10782.3516
Epoch 59/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 10999.9795 - mae: 10999.9795
Epoch 60/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 11017.9287 - mae: 11017.9287
Epoch 61/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 10817.2627 - mae: 10817.2627
Epoch 62/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10677.8252 - mae: 10677.8252
Epoch 63/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10414.6357 - mae: 10414.6357
Epoch 64/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10145.7861 - mae: 10145.7861
Epoch 65/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 10324.3623 - mae: 10324.3623
Epoch 66/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10330.9102 - mae: 10330.9111
Epoch 67/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10928.4551 - mae: 10928.4551
Epoch 68/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 10077.9316 - mae: 10077.9316
Epoch 69/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 10221.8301 - mae: 10221.8301
Epoch 70/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10204.7930 - mae: 10204.7930
Epoch 71/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10071.1836 - mae: 10071.1836
Epoch 72/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 10219.0029 - mae: 10219.0029
Epoch 73/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 10839.7764 - mae: 10839.7764
Epoch 74/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10189.6699 - mae: 10189.6699
Epoch 75/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10457.4844 - mae: 10457.4844
Epoch 76/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10255.8740 - mae: 10255.8740
Epoch 77/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9955.0830 - mae: 9955.0830
Epoch 78/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 10067.5449 - mae: 10067.5449
Epoch 79/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9988.3867 - mae: 9988.3867
Epoch 80/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9939.7168 - mae: 9939.7168
Epoch 81/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9806.2158 - mae: 9806.2158
Epoch 82/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10019.2705 - mae: 10019.2705
Epoch 83/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10764.5205 - mae: 10764.5205
Epoch 84/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10319.1689 - mae: 10319.1689
Epoch 85/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10618.6973 - mae: 10618.6973
Epoch 86/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 10130.0693 - mae: 10130.0693
Epoch 87/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10195.0205 - mae: 10195.0205
Epoch 88/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10090.0615 - mae: 10090.0615
Epoch 89/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 10198.7783 - mae: 10198.7783
Epoch 90/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10167.0254 - mae: 10167.0254
Epoch 91/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10379.7881 - mae: 10379.7881
Epoch 92/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10186.0625 - mae: 10186.0625
Epoch 93/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10226.0967 - mae: 10226.0967
Epoch 94/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9598.0439 - mae: 9598.0439
Epoch 95/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9956.2295 - mae: 9956.2295
Epoch 96/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9837.2529 - mae: 9837.2529
Epoch 97/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10308.8467 - mae: 10308.8467
Epoch 98/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10415.1494 - mae: 10415.1494
Epoch 99/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10030.1816 - mae: 10030.1816
Epoch 100/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9976.8242 - mae: 9976.8242
Epoch 101/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9864.1328 - mae: 9864.1328
Epoch 102/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10021.9541 - mae: 10021.9541
Epoch 103/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9891.4531 - mae: 9891.4531
Epoch 104/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 10081.0381 - mae: 10081.0381
Epoch 105/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10490.2832 - mae: 10490.2832
Epoch 106/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9752.0596 - mae: 9752.0605
Epoch 107/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9659.0234 - mae: 9659.0234
Epoch 108/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 9441.0254 - mae: 9441.0254
Epoch 109/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9984.0762 - mae: 9984.0752
Epoch 110/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9805.7441 - mae: 9805.7441
Epoch 111/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10448.9912 - mae: 10448.9912
Epoch 112/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9890.1973 - mae: 9890.1973
Epoch 113/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9909.2168 - mae: 9909.2168
Epoch 114/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 10315.1299 - mae: 10315.1299
Epoch 115/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9647.3838 - mae: 9647.3838
Epoch 116/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9838.9863 - mae: 9838.9863
Epoch 117/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10165.0381 - mae: 10165.0381
Epoch 118/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10212.5654 - mae: 10212.5654
Epoch 119/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9750.5264 - mae: 9750.5264
Epoch 120/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9917.2891 - mae: 9917.2891
Epoch 121/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10066.2168 - mae: 10066.2168
Epoch 122/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10000.4512 - mae: 10000.4512
Epoch 123/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9670.7080 - mae: 9670.7080
Epoch 124/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 10072.2012 - mae: 10072.2012
Epoch 125/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9985.7197 - mae: 9985.7197
Epoch 126/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9643.1582 - mae: 9643.1582
Epoch 127/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 9500.8496 - mae: 9500.8486
Epoch 128/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9622.4697 - mae: 9622.4697
Epoch 129/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10186.0537 - mae: 10186.0537
Epoch 130/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10348.3936 - mae: 10348.3936
Epoch 131/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9909.8193 - mae: 9909.8193
Epoch 132/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9464.3311 - mae: 9464.3311
Epoch 133/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9827.7227 - mae: 9827.7227
Epoch 134/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10042.9033 - mae: 10042.9023
Epoch 135/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9953.5879 - mae: 9953.5879
Epoch 136/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10307.3281 - mae: 10307.3281
Epoch 137/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 9989.3262 - mae: 9989.3262
Epoch 138/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9568.8359 - mae: 9568.8359
Epoch 139/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10104.1113 - mae: 10104.1113
Epoch 140/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9982.5088 - mae: 9982.5088
Epoch 141/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10500.6953 - mae: 10500.6953
Epoch 142/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9594.3057 - mae: 9594.3057
Epoch 143/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9547.3105 - mae: 9547.3105
Epoch 144/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9440.3828 - mae: 9440.3828
Epoch 145/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 9793.1240 - mae: 9793.1240
Epoch 146/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9864.2998 - mae: 9864.2998
Epoch 147/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 9645.7441 - mae: 9645.7441
Epoch 148/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10328.4082 - mae: 10328.4082
Epoch 149/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10077.7891 - mae: 10077.7891
Epoch 150/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 10219.7334 - mae: 10219.7334
Epoch 151/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10121.6621 - mae: 10121.6621
Epoch 152/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10322.1094 - mae: 10322.1094
Epoch 153/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10455.5264 - mae: 10455.5264
Epoch 154/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9881.2354 - mae: 9881.2354
Epoch 155/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9730.0605 - mae: 9730.0605
Epoch 156/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9740.1504 - mae: 9740.1504
Epoch 157/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9753.4619 - mae: 9753.4619
Epoch 158/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9798.4355 - mae: 9798.4355
Epoch 159/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9700.3779 - mae: 9700.3779
Epoch 160/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9964.3076 - mae: 9964.3076
Epoch 161/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10313.4785 - mae: 10313.4775
Epoch 162/162
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9698.5889 - mae: 9698.5889
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

[I 2026-10-20 13:13:46,749] Trial 27 finished with value: 0.910311701027384 and parameters: {'epochs': 162, 'batch_size': 28, 'units_layer1': 76, 'units_layer2': 110, 'optimizer': 'adam', 'learning_rate': 0.8792270843268954}. Best is trial 13 with value: 0.9435962770533816.

Epoch 1/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 27467.5527 - mae: 27467.5527
Epoch 2/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 21915.3613 - mae: 21915.3613
Epoch 3/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 21160.9277 - mae: 21160.9277
Epoch 4/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 19332.4902 - mae: 19332.4902
Epoch 5/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 17944.2676 - mae: 17944.2676
Epoch 6/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 16884.6445 - mae: 16884.6445
Epoch 7/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 15896.4766 - mae: 15896.4766
Epoch 8/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 14772.6133 - mae: 14772.6133
Epoch 9/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 15034.1289 - mae: 15034.1289
Epoch 10/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 13313.1094 - mae: 13313.1094
Epoch 11/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 13842.4727 - mae: 13842.4727
Epoch 12/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 13526.0215 - mae: 13526.0215
Epoch 13/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12892.2031 - mae: 12892.2031
Epoch 14/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12584.4404 - mae: 12584.4404
Epoch 15/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12680.5088 - mae: 12680.5088
Epoch 16/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12002.5947 - mae: 12002.5947
Epoch 17/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12295.1035 - mae: 12295.1035
Epoch 18/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 11805.3906 - mae: 11805.3906
Epoch 19/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 11683.3613 - mae: 11683.3613
Epoch 20/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 11355.2168 - mae: 11355.2168
Epoch 21/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 11496.0781 - mae: 11496.0781
Epoch 22/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 11584.3281 - mae: 11584.3281
Epoch 23/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 11390.8330 - mae: 11390.8330
Epoch 24/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 11097.3887 - mae: 11097.3887
Epoch 25/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 10922.3008 - mae: 10922.3008
Epoch 26/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 10771.6279 - mae: 10771.6279
Epoch 27/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 10816.5791 - mae: 10816.5791
Epoch 28/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 10841.3936 - mae: 10841.3936
Epoch 29/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 10582.2979 - mae: 10582.2979
Epoch 30/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 10456.2998 - mae: 10456.2998
Epoch 31/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 10250.8730 - mae: 10250.8730
Epoch 32/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 10318.5205 - mae: 10318.5205
Epoch 33/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 10068.4766 - mae: 10068.4766
Epoch 34/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9959.6992 - mae: 9959.6992
Epoch 35/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9796.0244 - mae: 9796.0244
Epoch 36/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 10120.0742 - mae: 10120.0742
Epoch 37/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 9954.3125 - mae: 9954.3125
Epoch 38/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9694.5938 - mae: 9694.5938
Epoch 39/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9849.1816 - mae: 9849.1816
Epoch 40/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9551.6914 - mae: 9551.6914
Epoch 41/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9596.4189 - mae: 9596.4189
Epoch 42/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9387.1104 - mae: 9387.1104
Epoch 43/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9492.6572 - mae: 9492.6572
Epoch 44/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9644.6992 - mae: 9644.6992
Epoch 45/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9223.6865 - mae: 9223.6865
Epoch 46/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9196.7539 - mae: 9196.7539
Epoch 47/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9299.6387 - mae: 9299.6387
Epoch 48/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9566.7627 - mae: 9566.7627
Epoch 49/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9141.9414 - mae: 9141.9414
Epoch 50/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9077.2871 - mae: 9077.2871
Epoch 51/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9301.3164 - mae: 9301.3164
Epoch 52/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 9019.2920 - mae: 9019.2920
Epoch 53/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9268.6035 - mae: 9268.6035
Epoch 54/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9113.3105 - mae: 9113.3105
Epoch 55/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8743.9531 - mae: 8743.9531
Epoch 56/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8984.9316 - mae: 8984.9316
Epoch 57/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 9185.2930 - mae: 9185.2930
Epoch 58/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9121.8047 - mae: 9121.8047
Epoch 59/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8824.8926 - mae: 8824.8926
Epoch 60/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8883.2461 - mae: 8883.2461
Epoch 61/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9281.3584 - mae: 9281.3584
Epoch 62/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8953.2881 - mae: 8953.2881
Epoch 63/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 8474.2197 - mae: 8474.2197
Epoch 64/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9012.0742 - mae: 9012.0742
Epoch 65/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8785.3799 - mae: 8785.3799
Epoch 66/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8618.6338 - mae: 8618.6338
Epoch 67/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8970.8398 - mae: 8970.8398
Epoch 68/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8517.7148 - mae: 8517.7148
Epoch 69/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8554.9766 - mae: 8554.9766
Epoch 70/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8712.3193 - mae: 8712.3193
Epoch 71/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8689.8848 - mae: 8689.8848
Epoch 72/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8649.0820 - mae: 8649.0820
Epoch 73/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 8648.5547 - mae: 8648.5547
Epoch 74/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8320.4102 - mae: 8320.4102
Epoch 75/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8698.7666 - mae: 8698.7666
Epoch 76/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8591.3740 - mae: 8591.3740
Epoch 77/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 8615.2441 - mae: 8615.2441
Epoch 78/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8504.2773 - mae: 8504.2773
Epoch 79/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8351.7959 - mae: 8351.7959
Epoch 80/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8520.9229 - mae: 8520.9229
Epoch 81/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8463.5762 - mae: 8463.5762
Epoch 82/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8456.2783 - mae: 8456.2783
Epoch 83/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8665.4014 - mae: 8665.4014
Epoch 84/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8132.6333 - mae: 8132.6333
Epoch 85/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8493.2168 - mae: 8493.2168
Epoch 86/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8084.7505 - mae: 8084.7505
Epoch 87/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8287.0889 - mae: 8287.0889
Epoch 88/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8171.4326 - mae: 8171.4326
Epoch 89/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8495.3857 - mae: 8495.3857
Epoch 90/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 8459.9834 - mae: 8459.9834
Epoch 91/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8312.0986 - mae: 8312.0986
Epoch 92/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8446.2559 - mae: 8446.2559
Epoch 93/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8425.4102 - mae: 8425.4102
Epoch 94/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8480.2588 - mae: 8480.2588
Epoch 95/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8150.8867 - mae: 8150.8867
Epoch 96/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8187.0669 - mae: 8187.0669
Epoch 97/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 8471.1699 - mae: 8471.1699
Epoch 98/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8473.8750 - mae: 8473.8750
Epoch 99/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8310.5967 - mae: 8310.5967
Epoch 100/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8354.0332 - mae: 8354.0332
Epoch 101/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 7979.6597 - mae: 7979.6597
Epoch 102/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8302.9434 - mae: 8302.9434
Epoch 103/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 8056.9146 - mae: 8056.9146
Epoch 104/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8155.9863 - mae: 8155.9863
Epoch 105/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8169.3257 - mae: 8169.3257
Epoch 106/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 8280.1035 - mae: 8280.1035
Epoch 107/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8062.0254 - mae: 8062.0254
Epoch 108/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 8151.1357 - mae: 8151.1357
Epoch 109/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8380.1357 - mae: 8380.1357
Epoch 110/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8129.6553 - mae: 8129.6553
Epoch 111/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8043.0771 - mae: 8043.0771
Epoch 112/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8458.6670 - mae: 8458.6670
Epoch 113/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8459.0967 - mae: 8459.0967
Epoch 114/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8254.4434 - mae: 8254.4434
Epoch 115/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8332.2949 - mae: 8332.2949
Epoch 116/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8147.1968 - mae: 8147.1968
Epoch 117/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 8460.7500 - mae: 8460.7500
Epoch 118/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7995.8730 - mae: 7995.8730
Epoch 119/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8146.9048 - mae: 8146.9048
Epoch 120/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8260.9902 - mae: 8260.9902
Epoch 121/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8333.1025 - mae: 8333.1025
Epoch 122/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8152.2031 - mae: 8152.2031
Epoch 123/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 7980.8945 - mae: 7980.8945
Epoch 124/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7796.2739 - mae: 7796.2739
Epoch 125/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8008.1167 - mae: 8008.1167
Epoch 126/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8051.8882 - mae: 8051.8882
Epoch 127/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7814.2988 - mae: 7814.2988
Epoch 128/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8020.1973 - mae: 8020.1973
Epoch 129/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7911.6304 - mae: 7911.6304
Epoch 130/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 8183.0908 - mae: 8183.0908
Epoch 131/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 8126.6309 - mae: 8126.6309
Epoch 132/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 7674.5181 - mae: 7674.5181
Epoch 133/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8357.1562 - mae: 8357.1562
Epoch 134/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7913.1855 - mae: 7913.1855
Epoch 135/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 7955.2637 - mae: 7955.2637
Epoch 136/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7901.2085 - mae: 7901.2085
Epoch 137/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8297.9980 - mae: 8297.9980
Epoch 138/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8078.8115 - mae: 8078.8115
Epoch 139/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8327.4346 - mae: 8327.4346
Epoch 140/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7766.6934 - mae: 7766.6934
Epoch 141/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7876.7563 - mae: 7876.7563
Epoch 142/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7987.8140 - mae: 7987.8140
Epoch 143/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7890.0142 - mae: 7890.0142
Epoch 144/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 8099.5059 - mae: 8099.5059
Epoch 145/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7977.1104 - mae: 7977.1104
Epoch 146/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7990.4951 - mae: 7990.4951
Epoch 147/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7881.0684 - mae: 7881.0684
Epoch 148/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7910.7935 - mae: 7910.7935
Epoch 149/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7947.8438 - mae: 7947.8438
Epoch 150/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7905.5220 - mae: 7905.5220
Epoch 151/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7956.4375 - mae: 7956.4375
Epoch 152/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7650.1055 - mae: 7650.1055
Epoch 153/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8177.4536 - mae: 8177.4536
Epoch 154/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 7969.4019 - mae: 7969.4019
Epoch 155/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8038.1274 - mae: 8038.1274
Epoch 156/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7766.0596 - mae: 7766.0596
Epoch 157/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7902.9526 - mae: 7902.9526
Epoch 158/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7755.9253 - mae: 7755.9253
Epoch 159/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 8019.4326 - mae: 8019.4326
Epoch 160/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7827.9194 - mae: 7827.9194
Epoch 161/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7782.6719 - mae: 7782.6719
Epoch 162/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7717.0659 - mae: 7717.0659
Epoch 163/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7936.4712 - mae: 7936.4712
Epoch 164/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 7803.5991 - mae: 7803.5991
Epoch 165/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8042.2314 - mae: 8042.2314
Epoch 166/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7441.0073 - mae: 7441.0073
Epoch 167/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 7716.3496 - mae: 7716.3496
Epoch 168/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7937.9819 - mae: 7937.9819
Epoch 169/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7617.6108 - mae: 7617.6108
Epoch 170/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 7769.3213 - mae: 7769.3213
Epoch 171/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7762.7808 - mae: 7762.7808
Epoch 172/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 7723.6123 - mae: 7723.6123
Epoch 173/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8292.8506 - mae: 8292.8506
Epoch 174/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 8130.8169 - mae: 8130.8169
Epoch 175/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7975.4526 - mae: 7975.4526
Epoch 176/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8155.2007 - mae: 8155.2007
Epoch 177/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7620.3076 - mae: 7620.3076
Epoch 178/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7457.6475 - mae: 7457.6475
Epoch 179/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7989.8770 - mae: 7989.8770
Epoch 180/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7971.5635 - mae: 7971.5635
Epoch 181/181
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 7871.4438 - mae: 7871.4438
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

[I 2026-10-20 13:15:35,214] Trial 28 finished with value: 0.9126069452187145 and parameters: {'epochs': 181, 'batch_size': 16, 'units_layer1': 102, 'units_layer2': 90, 'optimizer': 'adam', 'learning_rate': 0.3486662896693304}. Best is trial 13 with value: 0.9435962770533816.

Epoch 1/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 28848.9316 - mae: 28848.9316
Epoch 2/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 21033.5684 - mae: 21033.5684
Epoch 3/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20654.8770 - mae: 20654.8770
Epoch 4/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 20471.2090 - mae: 20471.2090
Epoch 5/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20198.3730 - mae: 20198.3730
Epoch 6/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20181.3730 - mae: 20181.3730
Epoch 7/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 20157.8477 - mae: 20157.8457
Epoch 8/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 20211.1914 - mae: 20211.1914
Epoch 9/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 20091.3965 - mae: 20091.3965
Epoch 10/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19388.7344 - mae: 19388.7324
Epoch 11/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17585.7129 - mae: 17585.7129
Epoch 12/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 16004.4180 - mae: 16004.4180
Epoch 13/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15155.3281 - mae: 15155.3281
Epoch 14/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 14115.1680 - mae: 14115.1680
Epoch 15/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 13684.2490 - mae: 13684.2490
Epoch 16/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 13089.2305 - mae: 13089.2305
Epoch 17/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 13076.4150 - mae: 13076.4150
Epoch 18/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12626.7295 - mae: 12626.7295
Epoch 19/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12518.3438 - mae: 12518.3438
Epoch 20/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12595.2686 - mae: 12595.2686
Epoch 21/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 11955.4482 - mae: 11955.4482
Epoch 22/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 11948.1445 - mae: 11948.1445
Epoch 23/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11630.3818 - mae: 11630.3818
Epoch 24/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 11484.4873 - mae: 11484.4873
Epoch 25/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 11310.6230 - mae: 11310.6240
Epoch 26/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 11066.7471 - mae: 11066.7471
Epoch 27/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 11170.5459 - mae: 11170.5459
Epoch 28/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11435.7988 - mae: 11435.7988
Epoch 29/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 10863.5635 - mae: 10863.5635
Epoch 30/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10724.5068 - mae: 10724.5068
Epoch 31/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 10471.0322 - mae: 10471.0322
Epoch 32/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10635.0205 - mae: 10635.0205
Epoch 33/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 10302.0068 - mae: 10302.0068
Epoch 34/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 10309.6631 - mae: 10309.6631
Epoch 35/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10508.1611 - mae: 10508.1611
Epoch 36/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 10077.8291 - mae: 10077.8291
Epoch 37/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9857.2744 - mae: 9857.2744
Epoch 38/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9810.9004 - mae: 9810.9004
Epoch 39/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9804.9170 - mae: 9804.9170
Epoch 40/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9461.8770 - mae: 9461.8770
Epoch 41/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9555.4033 - mae: 9555.4033
Epoch 42/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9329.2324 - mae: 9329.2314
Epoch 43/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9186.4512 - mae: 9186.4512
Epoch 44/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9112.4111 - mae: 9112.4111
Epoch 45/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9162.5723 - mae: 9162.5723
Epoch 46/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9023.7510 - mae: 9023.7510
Epoch 47/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9035.2930 - mae: 9035.2930
Epoch 48/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8693.1113 - mae: 8693.1113
Epoch 49/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8986.1123 - mae: 8986.1123
Epoch 50/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8581.4941 - mae: 8581.4941
Epoch 51/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8914.5908 - mae: 8914.5908
Epoch 52/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8484.4355 - mae: 8484.4355
Epoch 53/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 9001.2285 - mae: 9001.2285
Epoch 54/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8497.9492 - mae: 8497.9492
Epoch 55/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8334.3086 - mae: 8334.3086
Epoch 56/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8711.2480 - mae: 8711.2480
Epoch 57/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8470.6680 - mae: 8470.6680
Epoch 58/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8437.6514 - mae: 8437.6514
Epoch 59/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8375.4727 - mae: 8375.4727
Epoch 60/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8425.2295 - mae: 8425.2295
Epoch 61/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8531.3389 - mae: 8531.3389
Epoch 62/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8003.7329 - mae: 8003.7329
Epoch 63/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8020.1099 - mae: 8020.1099
Epoch 64/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8160.7725 - mae: 8160.7725
Epoch 65/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7868.7363 - mae: 7868.7363
Epoch 66/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8093.1304 - mae: 8093.1304
Epoch 67/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7871.6567 - mae: 7871.6567
Epoch 68/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8003.7812 - mae: 8003.7812
Epoch 69/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8274.4561 - mae: 8274.4561
Epoch 70/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7648.4492 - mae: 7648.4492
Epoch 71/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7783.0347 - mae: 7783.0347
Epoch 72/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7637.9800 - mae: 7637.9800
Epoch 73/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7766.2979 - mae: 7766.2979
Epoch 74/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7740.2769 - mae: 7740.2769
Epoch 75/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7840.3950 - mae: 7840.3940
Epoch 76/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7694.9946 - mae: 7694.9946
Epoch 77/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7848.3994 - mae: 7848.3994
Epoch 78/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7881.3955 - mae: 7881.3955
Epoch 79/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7513.0327 - mae: 7513.0327
Epoch 80/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7410.6748 - mae: 7410.6743
Epoch 81/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7544.1562 - mae: 7544.1562
Epoch 82/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7874.7725 - mae: 7874.7725
Epoch 83/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7438.9390 - mae: 7438.9390
Epoch 84/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8134.2593 - mae: 8134.2593
Epoch 85/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7368.1562 - mae: 7368.1562
Epoch 86/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7429.0869 - mae: 7429.0879
Epoch 87/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7711.4028 - mae: 7711.4028
Epoch 88/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7415.7065 - mae: 7415.7065
Epoch 89/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7392.7817 - mae: 7392.7817
Epoch 90/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7495.4463 - mae: 7495.4453
Epoch 91/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7271.9731 - mae: 7271.9736
Epoch 92/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7265.2480 - mae: 7265.2480
Epoch 93/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7510.1118 - mae: 7510.1118
Epoch 94/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7431.6401 - mae: 7431.6411
Epoch 95/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7485.5723 - mae: 7485.5723
Epoch 96/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7228.4121 - mae: 7228.4121
Epoch 97/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7350.1216 - mae: 7350.1216
Epoch 98/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7185.5254 - mae: 7185.5254
Epoch 99/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7310.3623 - mae: 7310.3623
Epoch 100/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7181.6650 - mae: 7181.6650
Epoch 101/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7254.4985 - mae: 7254.4985
Epoch 102/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7281.9307 - mae: 7281.9307
Epoch 103/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7030.9673 - mae: 7030.9673
Epoch 104/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6932.0298 - mae: 6932.0298
Epoch 105/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7068.8584 - mae: 7068.8584
Epoch 106/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7300.3794 - mae: 7300.3794
Epoch 107/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7195.4541 - mae: 7195.4541
Epoch 108/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7162.3555 - mae: 7162.3555
Epoch 109/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6976.4697 - mae: 6976.4697
Epoch 110/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7001.3721 - mae: 7001.3721
Epoch 111/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6813.8867 - mae: 6813.8867
Epoch 112/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6783.3687 - mae: 6783.3687
Epoch 113/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7113.7446 - mae: 7113.7446
Epoch 114/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7001.3320 - mae: 7001.3320
Epoch 115/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6779.4067 - mae: 6779.4067
Epoch 116/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6687.7837 - mae: 6687.7837
Epoch 117/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6873.1338 - mae: 6873.1338
Epoch 118/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6958.3545 - mae: 6958.3545
Epoch 119/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6902.0239 - mae: 6902.0244
Epoch 120/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7131.5229 - mae: 7131.5229
Epoch 121/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6930.4487 - mae: 6930.4487
Epoch 122/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6742.4971 - mae: 6742.4971
Epoch 123/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7040.1943 - mae: 7040.1943
Epoch 124/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6923.4507 - mae: 6923.4507
Epoch 125/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6846.2383 - mae: 6846.2383
Epoch 126/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6820.4746 - mae: 6820.4746
Epoch 127/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7055.3999 - mae: 7055.3999
Epoch 128/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6733.7881 - mae: 6733.7881
Epoch 129/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6420.8818 - mae: 6420.8818
Epoch 130/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6646.4292 - mae: 6646.4292
Epoch 131/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6608.6567 - mae: 6608.6567
Epoch 132/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6755.6284 - mae: 6755.6284
Epoch 133/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6978.1606 - mae: 6978.1606
Epoch 134/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6537.3887 - mae: 6537.3887
Epoch 135/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6375.2510 - mae: 6375.2510
Epoch 136/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6812.6899 - mae: 6812.6899
Epoch 137/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6517.4653 - mae: 6517.4653
Epoch 138/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6508.8145 - mae: 6508.8145
Epoch 139/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6548.8115 - mae: 6548.8120
Epoch 140/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6610.7510 - mae: 6610.7510
Epoch 141/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6798.0957 - mae: 6798.0957
Epoch 142/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6609.8193 - mae: 6609.8193
Epoch 143/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6644.2974 - mae: 6644.2974
Epoch 144/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6332.0532 - mae: 6332.0532
Epoch 145/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6325.3633 - mae: 6325.3633
Epoch 146/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6352.4375 - mae: 6352.4375
Epoch 147/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6467.9282 - mae: 6467.9282
Epoch 148/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6643.5215 - mae: 6643.5220
Epoch 149/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6415.0840 - mae: 6415.0840
Epoch 150/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6206.5718 - mae: 6206.5718
Epoch 151/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6266.8472 - mae: 6266.8472
Epoch 152/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6223.8716 - mae: 6223.8716
Epoch 153/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6314.1753 - mae: 6314.1753
Epoch 154/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6438.6665 - mae: 6438.6665
Epoch 155/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6124.7490 - mae: 6124.7490
Epoch 156/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6340.5347 - mae: 6340.5347
Epoch 157/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6470.5845 - mae: 6470.5854
Epoch 158/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6245.0957 - mae: 6245.0957
Epoch 159/159
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6229.7065 - mae: 6229.7065
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

[I 2026-10-20 13:16:50,623] Trial 29 finished with value: 0.9380337474346381 and parameters: {'epochs': 159, 'batch_size': 21, 'units_layer1': 116, 'units_layer2': 97, 'optimizer': 'adam', 'learning_rate': 0.14187455163534665}. Best is trial 13 with value: 0.9435962770533816.

Best trial: 0.9435962770533816
Best hyperparameters: {'epochs': 166, 'batch_size': 39, 'units_layer1': 87, 'units_layer2': 78, 'optimizer': 'adam', 'learning_rate': 0.3085186122202393}

{'epochs': 166,
 'batch_size': 39,
 'units_layer1': 87,
 'units_layer2': 78,
 'optimizer': 'adam',
 'learning_rate': 0.3085186122202393}

# 10. Train and evaluate the final model with the best hyperparameters

In [11]:
# Train the final model with the best hyperparameters

best_model = Sequential()
best_model.add(Dense(units=best_params['units_layer1'], activation='relu'))
best_model.add(Dense(units=best_params['units_layer2'], activation='relu'))
best_model.add(Dense(1, activation='relu'))

if best_params['optimizer'] == 'adam':
    best_optimizer = Adam(learning_rate=best_params['learning_rate'])
elif best_params['optimizer'] == 'sgd':
    best_optimizer = SGD(learning_rate=best_params['learning_rate'])
elif best_params['optimizer'] == 'rmsprop':
    best_optimizer = RMSprop(learning_rate=best_params['learning_rate'])
elif best_params['optimizer'] == 'adagrad':
    best_optimizer = Adagrad(learning_rate=best_params['learning_rate'])

best_model.compile(optimizer=best_optimizer, loss='mae', metrics=['mae'])


def evaluate(model, X_train, y_train, X_test, y_test):
    
    model.fit(X_train, y_train, epochs=best_params['epochs'], batch_size=best_params['batch_size'])
    
    '''Predictions for the training set'''
    
    y_train_pred = model.predict(X_train)

    '''Predictions for the test set'''
    
    y_test_pred = model.predict(X_test)

    '''Calculate metrics for the training set''' 
    
    r2_train = r2_score(y_train, y_train_pred)

    '''Calculate metrics for the test set'''
    
    r2_test = r2_score(y_test, y_test_pred)
    

    results = pd.DataFrame({
        'Dataset': ['Train', 'Test'],
        'R2': [r2_train, r2_test],
    
    })

    return results


evaluate(best_model, X_train_scaled, y_train, X_test_scaled, y_test)

Epoch 1/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 29921.7441 - mae: 29921.7441
Epoch 2/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 21926.0156 - mae: 21926.0176
Epoch 3/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 21123.0273 - mae: 21123.0254
Epoch 4/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 21066.0059 - mae: 21066.0059
Epoch 5/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20809.1230 - mae: 20809.1211
Epoch 6/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19847.8242 - mae: 19847.8242
Epoch 7/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18707.4512 - mae: 18707.4512
Epoch 8/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19097.4434 - mae: 19097.4414
Epoch 9/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17431.1309 - mae: 17431.1309
Epoch 10/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16399.7637 - mae: 16399.7637
Epoch 11/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16449.0039 - mae: 16449.0039
Epoch 12/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15742.2305 - mae: 15742.2305
Epoch 13/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 15457.0566 - mae: 15457.0566
Epoch 14/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14568.3311 - mae: 14568.3311
Epoch 15/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14147.2129 - mae: 14147.2129
Epoch 16/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14990.2959 - mae: 14990.2959
Epoch 17/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 14172.4932 - mae: 14172.4932
Epoch 18/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13351.3584 - mae: 13351.3584
Epoch 19/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13143.1709 - mae: 13143.1709
Epoch 20/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12747.5322 - mae: 12747.5322
Epoch 21/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 12943.6699 - mae: 12943.6699
Epoch 22/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12856.3223 - mae: 12856.3223
Epoch 23/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12484.7969 - mae: 12484.7969
Epoch 24/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12334.6963 - mae: 12334.6963
Epoch 25/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11754.1191 - mae: 11754.1191
Epoch 26/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11512.5781 - mae: 11512.5781
Epoch 27/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11038.8174 - mae: 11038.8184
Epoch 28/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11917.3086 - mae: 11917.3086
Epoch 29/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11221.9004 - mae: 11221.9004
Epoch 30/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10913.7227 - mae: 10913.7227
Epoch 31/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11003.9746 - mae: 11003.9756
Epoch 32/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 10662.4092 - mae: 10662.4092
Epoch 33/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10534.7285 - mae: 10534.7285
Epoch 34/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10132.6592 - mae: 10132.6592
Epoch 35/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10434.6484 - mae: 10434.6484
Epoch 36/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9880.1855 - mae: 9880.1855
Epoch 37/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10105.3066 - mae: 10105.3066
Epoch 38/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9678.8848 - mae: 9678.8857
Epoch 39/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10239.8750 - mae: 10239.8750
Epoch 40/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9839.5264 - mae: 9839.5264
Epoch 41/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9528.7188 - mae: 9528.7188
Epoch 42/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9731.4570 - mae: 9731.4570
Epoch 43/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9731.0010 - mae: 9731.0010
Epoch 44/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9482.9131 - mae: 9482.9131
Epoch 45/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9524.5244 - mae: 9524.5244
Epoch 46/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9272.4639 - mae: 9272.4629
Epoch 47/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9039.0703 - mae: 9039.0723
Epoch 48/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9324.3125 - mae: 9324.3125
Epoch 49/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9256.5410 - mae: 9256.5410
Epoch 50/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9055.5684 - mae: 9055.5684
Epoch 51/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9073.5527 - mae: 9073.5527
Epoch 52/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9097.5332 - mae: 9097.5332
Epoch 53/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8999.9375 - mae: 8999.9375
Epoch 54/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8922.0312 - mae: 8922.0312
Epoch 55/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9052.9238 - mae: 9052.9238
Epoch 56/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 9305.7090 - mae: 9305.7090
Epoch 57/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9029.2988 - mae: 9029.2988
Epoch 58/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8696.3398 - mae: 8696.3398
Epoch 59/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8528.8115 - mae: 8528.8115
Epoch 60/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8694.5762 - mae: 8694.5762
Epoch 61/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8864.9033 - mae: 8864.9033
Epoch 62/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8498.6211 - mae: 8498.6211
Epoch 63/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8678.5625 - mae: 8678.5625
Epoch 64/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8416.7334 - mae: 8416.7334
Epoch 65/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8755.2217 - mae: 8755.2217
Epoch 66/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8816.3457 - mae: 8816.3457
Epoch 67/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8446.5625 - mae: 8446.5625
Epoch 68/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8261.9004 - mae: 8261.9004
Epoch 69/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8287.7539 - mae: 8287.7539
Epoch 70/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8494.9463 - mae: 8494.9453
Epoch 71/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8131.3350 - mae: 8131.3350
Epoch 72/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8442.0039 - mae: 8442.0039
Epoch 73/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8019.2788 - mae: 8019.2788
Epoch 74/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8892.7080 - mae: 8892.7080
Epoch 75/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8066.3530 - mae: 8066.3530
Epoch 76/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8129.9746 - mae: 8129.9746
Epoch 77/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8010.6172 - mae: 8010.6172
Epoch 78/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7862.2964 - mae: 7862.2964
Epoch 79/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8205.9209 - mae: 8205.9199
Epoch 80/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8025.0327 - mae: 8025.0327
Epoch 81/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7949.6807 - mae: 7949.6807
Epoch 82/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7923.9761 - mae: 7923.9761
Epoch 83/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8037.2788 - mae: 8037.2788
Epoch 84/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8151.4214 - mae: 8151.4214
Epoch 85/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7799.4380 - mae: 7799.4380
Epoch 86/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7898.2847 - mae: 7898.2847
Epoch 87/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7697.4224 - mae: 7697.4224
Epoch 88/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7670.5615 - mae: 7670.5615
Epoch 89/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7598.0596 - mae: 7598.0596
Epoch 90/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7868.9263 - mae: 7868.9263
Epoch 91/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7729.5049 - mae: 7729.5049
Epoch 92/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7401.9248 - mae: 7401.9248
Epoch 93/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7626.0244 - mae: 7626.0244
Epoch 94/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7391.2954 - mae: 7391.2954
Epoch 95/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7576.9580 - mae: 7576.9580
Epoch 96/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8024.0483 - mae: 8024.0483
Epoch 97/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7660.4272 - mae: 7660.4277
Epoch 98/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7404.5254 - mae: 7404.5254
Epoch 99/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7829.0229 - mae: 7829.0229
Epoch 100/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7498.9614 - mae: 7498.9614
Epoch 101/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7463.6821 - mae: 7463.6821
Epoch 102/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7726.9302 - mae: 7726.9302
Epoch 103/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7619.5581 - mae: 7619.5581
Epoch 104/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7621.8052 - mae: 7621.8052
Epoch 105/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7533.1519 - mae: 7533.1519
Epoch 106/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7425.8125 - mae: 7425.8125
Epoch 107/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7384.7295 - mae: 7384.7295
Epoch 108/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7137.7725 - mae: 7137.7725
Epoch 109/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7440.8623 - mae: 7440.8623
Epoch 110/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7651.9883 - mae: 7651.9883
Epoch 111/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7538.6680 - mae: 7538.6680
Epoch 112/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7363.1914 - mae: 7363.1914
Epoch 113/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7500.0591 - mae: 7500.0591
Epoch 114/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7063.1787 - mae: 7063.1787
Epoch 115/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7284.0801 - mae: 7284.0801
Epoch 116/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7188.4478 - mae: 7188.4478
Epoch 117/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7547.6016 - mae: 7547.6016
Epoch 118/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7257.4878 - mae: 7257.4878
Epoch 119/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7242.7480 - mae: 7242.7480
Epoch 120/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7126.9922 - mae: 7126.9922
Epoch 121/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7162.5142 - mae: 7162.5142
Epoch 122/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7147.0557 - mae: 7147.0547
Epoch 123/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7266.0420 - mae: 7266.0420
Epoch 124/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7100.4995 - mae: 7100.4995
Epoch 125/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7064.2271 - mae: 7064.2271
Epoch 126/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7224.1284 - mae: 7224.1284
Epoch 127/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7283.1704 - mae: 7283.1704
Epoch 128/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7180.7817 - mae: 7180.7817
Epoch 129/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7099.9771 - mae: 7099.9771
Epoch 130/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6767.1406 - mae: 6767.1406
Epoch 131/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6778.2148 - mae: 6778.2148
Epoch 132/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7047.1333 - mae: 7047.1333
Epoch 133/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7492.5664 - mae: 7492.5664
Epoch 134/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6917.8179 - mae: 6917.8179
Epoch 135/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6877.4097 - mae: 6877.4097
Epoch 136/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7191.5103 - mae: 7191.5103
Epoch 137/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7047.5386 - mae: 7047.5386
Epoch 138/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6814.5479 - mae: 6814.5479
Epoch 139/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7113.2378 - mae: 7113.2378
Epoch 140/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7095.4888 - mae: 7095.4888
Epoch 141/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6866.0947 - mae: 6866.0942
Epoch 142/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7185.1182 - mae: 7185.1182
Epoch 143/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6694.3208 - mae: 6694.3208
Epoch 144/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6881.5952 - mae: 6881.5952
Epoch 145/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6764.4785 - mae: 6764.4785
Epoch 146/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6741.2529 - mae: 6741.2529
Epoch 147/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7034.0425 - mae: 7034.0425
Epoch 148/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6882.0498 - mae: 6882.0498
Epoch 149/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6849.7065 - mae: 6849.7065
Epoch 150/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6839.1211 - mae: 6839.1211
Epoch 151/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6596.8486 - mae: 6596.8486
Epoch 152/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6887.2861 - mae: 6887.2861
Epoch 153/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6833.7378 - mae: 6833.7378
Epoch 154/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6697.3892 - mae: 6697.3892
Epoch 155/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6829.3540 - mae: 6829.3540
Epoch 156/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6683.2417 - mae: 6683.2417
Epoch 157/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6771.2559 - mae: 6771.2559
Epoch 158/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6821.3438 - mae: 6821.3438
Epoch 159/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7019.4834 - mae: 7019.4834
Epoch 160/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6924.4897 - mae: 6924.4897
Epoch 161/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6800.5845 - mae: 6800.5845
Epoch 162/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6653.1167 - mae: 6653.1167
Epoch 163/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6640.4434 - mae: 6640.4434
Epoch 164/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6545.8970 - mae: 6545.8970
Epoch 165/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6761.9434 - mae: 6761.9434
Epoch 166/166
138/138 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6988.2358 - mae: 6988.2358
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

  Dataset        R2
0   Train  0.944383
1    Test  0.930239